import type { ProjectDNA, WorkspaceArtifact } from '../types';

export interface ExportBranding { institutionName?: string; footer?: string }

export function projectExportHtml(project:ProjectDNA,artifacts:WorkspaceArtifact[]=[],branding:ExportBranding={}){
  const e=(v:unknown)=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
  const list=(items:string[])=>`<ul>${items.map(x=>`<li>${x}</li>`).join('')}</ul>`;
  return `<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><style>@page{size:A4;margin:18mm}*{box-sizing:border-box}body{font-family:Arial,"Noto Sans Arabic",sans-serif;color:#17211e;line-height:1.7;font-size:11pt}h1{font-size:25pt;margin:0 0 6mm}h2{font-size:15pt;margin:8mm 0 3mm;border-bottom:1px solid #d9dfdc;padding-bottom:2mm}.meta{display:grid;grid-template-columns:1fr 1fr;gap:2mm 8mm;background:#f6f7f5;padding:4mm;border-radius:3mm}.muted{color:#66736e}.badge{display:inline-block;border:1px solid #cdd6d2;border-radius:999px;padding:1mm 3mm;margin:0 0 1mm 1mm}li{margin-bottom:1.5mm}.footer{margin-top:12mm;border-top:1px solid #d9dfdc;padding-top:3mm;font-size:8.5pt;color:#66736e}</style></head><body>${branding.institutionName?`<div class="muted">${e(branding.institutionName)}</div>`:''}<h1>${e(project.title)}</h1><div class="muted">AcademicOS — From Assignment to Evidence</div><div class="meta"><div><strong>المقرر</strong><br>${e(project.course)}</div><div><strong>النوع</strong><br>${e(project.projectType)}</div><div><strong>الحالة</strong><br>${e(project.status)} — ${e(project.progress)}%</div><div><strong>الموعد</strong><br>${e(project.deadlines.final||'Needs confirmation')}</div><div><strong>AI Policy</strong><br>Level ${e(project.aiPolicy.level)} — ${e(project.aiPolicy.summary)}</div><div><strong>المجال</strong><br>${e(project.academicDomain)}</div></div><h2>المخرجات</h2>${list(project.deliverables.map(d=>`<strong>${e(d.title)}</strong> — ${e(d.format)} — ${e(d.status)}`))}<h2>المتطلبات</h2>${list(project.requirements.map(r=>`<strong>${e(r.label)}</strong>: ${e(r.value)} <span class="muted">(${e(r.confidence)})</span>`))}<h2>الخطة</h2>${list(project.tasks.map(t=>`<strong>${e(t.title)}</strong> — ${e(t.status)}`))}<h2>الـRubric</h2>${list(project.rubric.length?project.rubric.map(r=>`<strong>${e(r.title)}</strong> (${e(r.weighting)}%) — ${e(r.readiness||'not evidenced')}`):['لا يوجد Rubric مورّد أو مكتشف.'])}<h2>مساحة العمل</h2>${list(artifacts.length?artifacts.map(a=>`<strong>${e(a.title)}</strong> — ${e(a.module)} / ${e(a.status)}${a.isCanonical?' — canonical':''}`):['لا توجد عناصر محفوظة.'])}<h2>المخاطر والتأكيدات</h2>${list(project.riskFlags.length?project.riskFlags.map(e):['لا توجد مخاطر مسجلة حاليًا.'])}<div class="footer">تم إنشاء هذا السجل من AcademicOS بتاريخ ${e(new Date().toISOString())}. هذا التقرير ليس توقعًا للدرجة النهائية.${branding.footer?` ${e(branding.footer)}`:''}</div></body></html>`;
}

function markdown(project: ProjectDNA, artifacts: WorkspaceArtifact[] = [], branding:ExportBranding={}) {
  const lines = [
    ...(branding.institutionName?[`**Institution:** ${branding.institutionName}`,'']:[]),`# ${project.title}`,'',`- **Course:** ${project.course}`,`- **Project type:** ${project.projectType}`,`- **Status:** ${project.status}`,`- **Progress:** ${project.progress}%`,
    `- **Deadline:** ${project.deadlines.final || 'Needs confirmation'}`,`- **AI policy:** Level ${project.aiPolicy.level} — ${project.aiPolicy.summary}`,'','## Deliverables',
    ...project.deliverables.map(d => `- [${d.status === 'completed' || d.status === 'ready' ? 'x' : ' '}] ${d.title} — ${d.format}`),'','## Requirements',
    ...project.requirements.map(r => `- **${r.label}:** ${r.value} (${r.confidence})`),'','## Tasks',...project.tasks.map(t => `- [${t.status === 'completed' ? 'x' : ' '}] ${t.title} — ${t.status}`),'','## Rubric',
    ...(project.rubric.length ? project.rubric.map(r => `- **${r.title}** (${r.weighting}%): ${r.description || 'No description'} — ${r.readiness || 'not_evidenced'}`) : ['- No rubric was supplied or detected.']),'','## Risks / confirmations',
    ...(project.riskFlags.length ? project.riskFlags.map(r => `- ${r}`) : ['- None currently recorded.']),'','## Adaptive workspace artifacts',
    ...(artifacts.length ? artifacts.map(a => `- **${a.title}** — ${a.module} / ${a.status}${a.deliverableId ? ` → deliverable ${a.deliverableId}` : ''}${a.rubricIds?.length ? ` → rubric ${a.rubricIds.join(', ')}` : ''}${a.isCanonical ? ' — canonical work item' : ''}`) : ['- No saved workspace artifacts.']),'','---',
    `Exported from AcademicOS at ${new Date().toISOString()}. This export is a project record, not a grade prediction.`,
  ]; return lines.join('\n');
}

function crc32(input: Buffer) {let crc=0xffffffff;for(const byte of input){crc^=byte;for(let i=0;i<8;i+=1)crc=(crc>>>1)^(0xedb88320&-(crc&1));}return(crc^0xffffffff)>>>0;}
export function zipStore(files:Array<{name:string;data:Buffer}>){const chunks:Buffer[]=[];const central:Buffer[]=[];let offset=0;for(const file of files){const name=Buffer.from(file.name,'utf8');const crc=crc32(file.data);const local=Buffer.alloc(30);local.writeUInt32LE(0x04034b50,0);local.writeUInt16LE(20,4);local.writeUInt16LE(0x0800,6);local.writeUInt16LE(0,8);local.writeUInt32LE(crc,14);local.writeUInt32LE(file.data.length,18);local.writeUInt32LE(file.data.length,22);local.writeUInt16LE(name.length,26);chunks.push(local,name,file.data);const c=Buffer.alloc(46);c.writeUInt32LE(0x02014b50,0);c.writeUInt16LE(20,4);c.writeUInt16LE(20,6);c.writeUInt16LE(0x0800,8);c.writeUInt16LE(0,10);c.writeUInt32LE(crc,16);c.writeUInt32LE(file.data.length,20);c.writeUInt32LE(file.data.length,24);c.writeUInt16LE(name.length,28);c.writeUInt32LE(offset,42);central.push(c,name);offset+=local.length+name.length+file.data.length;}const centralBuffer=Buffer.concat(central);const eocd=Buffer.alloc(22);eocd.writeUInt32LE(0x06054b50,0);eocd.writeUInt16LE(files.length,8);eocd.writeUInt16LE(files.length,10);eocd.writeUInt32LE(centralBuffer.length,12);eocd.writeUInt32LE(offset,16);return Buffer.concat([...chunks,centralBuffer,eocd]);}

function xml(value:unknown){return String(value??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;');}
function b(value:string){return Buffer.from(value,'utf8');}
function projectRows(project:ProjectDNA,branding:ExportBranding={}){return [
  ['Field','Value'],...(branding.institutionName?[['Institution',branding.institutionName]]:[]),['Title',project.title],['Course',project.course],['Project type',project.projectType],['Academic domain',project.academicDomain],['Status',project.status],['Progress',`${project.progress}%`],['Deadline',project.deadlines.final||'Needs confirmation'],['AI policy',`Level ${project.aiPolicy.level} — ${project.aiPolicy.summary}`],
  ...project.deliverables.map(d=>[`Deliverable: ${d.title}`,`${d.format} — ${d.status}`]),...project.tasks.map(t=>[`Task: ${t.title}`,t.status]),...project.rubric.map(r=>[`Rubric: ${r.title}`,`${r.weighting}% — ${r.readiness||'not evidenced'}`]),
];}

function docx(project:ProjectDNA,artifacts:WorkspaceArtifact[],branding:ExportBranding={}){
  const paras=[...(branding.institutionName?[branding.institutionName]:[]),project.title,`Course: ${project.course}`,`Project type: ${project.projectType}`,`Status: ${project.status} · ${project.progress}%`,`Deadline: ${project.deadlines.final||'Needs confirmation'}`,'Deliverables',...project.deliverables.map(d=>`${d.title} — ${d.format} — ${d.status}`),'Requirements',...project.requirements.map(r=>`${r.label}: ${r.value} (${r.confidence})`),'Tasks',...project.tasks.map(t=>`${t.title} — ${t.status}`),'Rubric',...project.rubric.map(r=>`${r.title} (${r.weighting}%): ${r.description||''} — ${r.readiness||'not evidenced'}`),'Workspace',...artifacts.map(a=>`${a.title} — ${a.module} — ${a.status}`)];
  const p=paras.map((t,i)=>`<w:p${i===0?' w:rsidR="00000000"':''}><w:pPr><w:bidi/><w:jc w:val="${i===0?'center':'right'}"/></w:pPr><w:r><w:rPr>${i===0?'<w:b/>':''}<w:rtl/></w:rPr><w:t xml:space="preserve">${xml(t)}</w:t></w:r></w:p>`).join('');
  return zipStore([
    {name:'[Content_Types].xml',data:b(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/></Types>`)},
    {name:'_rels/.rels',data:b(`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/></Relationships>`)},
    {name:'word/document.xml',data:b(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${p}<w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440"/></w:sectPr></w:body></w:document>`)},
    {name:'docProps/core.xml',data:b(`<?xml version="1.0" encoding="UTF-8"?><cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/"><dc:title>${xml(project.title)}</dc:title><dc:creator>AcademicOS</dc:creator><dcterms:created xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="dcterms:W3CDTF">${new Date().toISOString()}</dcterms:created></cp:coreProperties>`)},
  ]);
}

function pptx(project:ProjectDNA,branding:ExportBranding={}){
  const slides=[
    [project.title,`${branding.institutionName?branding.institutionName+' · ':''}${project.course} · ${project.projectType}`],
    ['Deliverables',project.deliverables.map(d=>`${d.title} — ${d.status}`).join('\n')||'No deliverables'],
    ['Rubric readiness',project.rubric.map(r=>`${r.title}: ${r.readiness||'not evidenced'}`).join('\n')||'No rubric supplied'],
    ['Next action',project.nextAction||'Review the project plan and requirements.'],
  ];
  const files:Array<{name:string;data:Buffer}>=[
    {name:'[Content_Types].xml',data:b(`<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/ppt/presentation.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml"/>${slides.map((_,i)=>`<Override PartName="/ppt/slides/slide${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slide+xml"/>`).join('')}<Override PartName="/ppt/slideMasters/slideMaster1.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slideMaster+xml"/><Override PartName="/ppt/slideLayouts/slideLayout1.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slideLayout+xml"/><Override PartName="/ppt/theme/theme1.xml" ContentType="application/vnd.openxmlformats-officedocument.theme+xml"/></Types>`)},
    {name:'_rels/.rels',data:b(`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="ppt/presentation.xml"/></Relationships>`)},
    {name:'ppt/presentation.xml',data:b(`<?xml version="1.0" encoding="UTF-8"?><p:presentation xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"><p:sldMasterIdLst><p:sldMasterId id="2147483648" r:id="rId1"/></p:sldMasterIdLst><p:sldIdLst>${slides.map((_,i)=>`<p:sldId id="${256+i}" r:id="rId${i+2}"/>`).join('')}</p:sldIdLst><p:sldSz cx="12192000" cy="6858000" type="screen16x9"/><p:notesSz cx="6858000" cy="9144000"/></p:presentation>`)},
    {name:'ppt/_rels/presentation.xml.rels',data:b(`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideMaster" Target="slideMasters/slideMaster1.xml"/>${slides.map((_,i)=>`<Relationship Id="rId${i+2}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide" Target="slides/slide${i+1}.xml"/>`).join('')}</Relationships>`)},
    {name:'ppt/slideMasters/slideMaster1.xml',data:b(`<?xml version="1.0" encoding="UTF-8"?><p:sldMaster xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"><p:cSld><p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr><a:xfrm/></p:grpSpPr></p:spTree></p:cSld><p:sldLayoutIdLst><p:sldLayoutId id="1" r:id="rId1"/></p:sldLayoutIdLst><p:txStyles><p:titleStyle/><p:bodyStyle/><p:otherStyle/></p:txStyles></p:sldMaster>`)},
    {name:'ppt/slideMasters/_rels/slideMaster1.xml.rels',data:b(`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideLayout" Target="../slideLayouts/slideLayout1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/theme" Target="../theme/theme1.xml"/></Relationships>`)},
    {name:'ppt/slideLayouts/slideLayout1.xml',data:b(`<?xml version="1.0" encoding="UTF-8"?><p:sldLayout xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main" type="blank"><p:cSld name="Blank"><p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr><a:xfrm/></p:grpSpPr></p:spTree></p:cSld></p:sldLayout>`)},
    {name:'ppt/slideLayouts/_rels/slideLayout1.xml.rels',data:b(`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideMaster" Target="../slideMasters/slideMaster1.xml"/></Relationships>`)},
    {name:'ppt/theme/theme1.xml',data:b(`<?xml version="1.0" encoding="UTF-8"?><a:theme xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" name="AcademicOS"><a:themeElements><a:clrScheme name="AcademicOS"><a:dk1><a:srgbClr val="111111"/></a:dk1><a:lt1><a:srgbClr val="FFFFFF"/></a:lt1><a:dk2><a:srgbClr val="333333"/></a:dk2><a:lt2><a:srgbClr val="F6F5F1"/></a:lt2><a:accent1><a:srgbClr val="335C55"/></a:accent1><a:accent2><a:srgbClr val="6B7A74"/></a:accent2><a:accent3><a:srgbClr val="8D755B"/></a:accent3><a:accent4><a:srgbClr val="566A85"/></a:accent4><a:accent5><a:srgbClr val="7B6B85"/></a:accent5><a:accent6><a:srgbClr val="92706C"/></a:accent6><a:hlink><a:srgbClr val="335C55"/></a:hlink><a:folHlink><a:srgbClr val="6B7A74"/></a:folHlink></a:clrScheme><a:fontScheme name="AcademicOS"><a:majorFont><a:latin typeface="Arial"/><a:ea typeface=""/><a:cs typeface="Arial"/></a:majorFont><a:minorFont><a:latin typeface="Arial"/><a:ea typeface=""/><a:cs typeface="Arial"/></a:minorFont></a:fontScheme><a:fmtScheme name="AcademicOS"><a:fillStyleLst/><a:lnStyleLst/><a:effectStyleLst/><a:bgFillStyleLst/></a:fmtScheme></a:themeElements></a:theme>`)},
  ];
  slides.forEach(([title,body],i)=>{const shape=(id:number,name:string,text:string,y:number,size:number)=>`<p:sp><p:nvSpPr><p:cNvPr id="${id}" name="${name}"/><p:cNvSpPr/><p:nvPr/></p:nvSpPr><p:spPr><a:xfrm><a:off x="762000" y="${y}"/><a:ext cx="10668000" cy="${id===2?1000000:4300000}"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom><a:noFill/><a:ln><a:noFill/></a:ln></p:spPr><p:txBody><a:bodyPr rtlCol="1"/><a:lstStyle/><a:p><a:pPr algn="r" rtl="1"/><a:r><a:rPr lang="ar-SA" sz="${size}"/><a:t>${xml(text)}</a:t></a:r></a:p></p:txBody></p:sp>`;files.push({name:`ppt/slides/slide${i+1}.xml`,data:b(`<?xml version="1.0" encoding="UTF-8"?><p:sld xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"><p:cSld><p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr><a:xfrm/></p:grpSpPr>${shape(2,'Title',title,600000,2800)}${shape(3,'Body',body,1800000,1600)}</p:spTree></p:cSld><p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr></p:sld>`)});files.push({name:`ppt/slides/_rels/slide${i+1}.xml.rels`,data:b(`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideLayout" Target="../slideLayouts/slideLayout1.xml"/></Relationships>`)})});
  return zipStore(files);
}

function xlsx(project:ProjectDNA,branding:ExportBranding={}){
  const rows=projectRows(project,branding);const sheet=rows.map((row,r)=>`<row r="${r+1}">${row.map((cell,c)=>`<c r="${String.fromCharCode(65+c)}${r+1}" t="inlineStr"><is><t>${xml(cell)}</t></is></c>`).join('')}</row>`).join('');
  return zipStore([
    {name:'[Content_Types].xml',data:b(`<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>`)},
    {name:'_rels/.rels',data:b(`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>`)},
    {name:'xl/workbook.xml',data:b(`<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Project" sheetId="1" r:id="rId1"/></sheets></workbook>`)},
    {name:'xl/_rels/workbook.xml.rels',data:b(`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>`)},
    {name:'xl/worksheets/sheet1.xml',data:b(`<?xml version="1.0" encoding="UTF-8"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView rightToLeft="1" workbookViewId="0"/></sheetViews><sheetData>${sheet}</sheetData></worksheet>`)},
  ]);
}

export function safeCsvCell(value:unknown){const raw=String(value??'');const literal=/^[\u0009\u000d\u000a ]*[=+\-@]/.test(raw)?`'${raw}`:raw;return `"${literal.replace(/"/g,'""')}"`;}
function csv(project:ProjectDNA,branding:ExportBranding={}){return Buffer.from('\uFEFF'+projectRows(project,branding).map(row=>row.map(safeCsvCell).join(',')).join('\r\n'),'utf8');}

export function exportProject(project: ProjectDNA, format: string, artifacts: WorkspaceArtifact[] = [], branding:ExportBranding={}) {
  const safe = project.title.replace(/[^\p{L}\p{N}._ -]+/gu, '_').slice(0, 80) || 'AcademicOS-project';
  const json = Buffer.from(JSON.stringify({ ...project, workspaceArtifacts: artifacts }, null, 2), 'utf8');const artifactsJson=Buffer.from(JSON.stringify(artifacts,null,2),'utf8');const md=Buffer.from(markdown(project,artifacts,branding),'utf8');
  if(format==='json')return{data:json,contentType:'application/json; charset=utf-8',filename:`${safe}.json`};
  if(format==='md'||format==='markdown')return{data:md,contentType:'text/markdown; charset=utf-8',filename:`${safe}.md`};
  if(format==='csv')return{data:csv(project,branding),contentType:'text/csv; charset=utf-8',filename:`${safe}.csv`};
  if(format==='docx')return{data:docx(project,artifacts,branding),contentType:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',filename:`${safe}.docx`};
  if(format==='pptx')return{data:pptx(project,branding),contentType:'application/vnd.openxmlformats-officedocument.presentationml.presentation',filename:`${safe}.pptx`};
  if(format==='xlsx')return{data:xlsx(project,branding),contentType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',filename:`${safe}.xlsx`};
  if(format==='pdf')throw Object.assign(new Error('PDF export requires the isolated PDF renderer configured by PDF_RENDER_SERVICE_URL; AcademicOS does not fake a PDF renderer.'),{status:503,code:'PDF_RENDER_NOT_CONFIGURED'});
  if(format==='zip'){
    const manifest=Buffer.from(JSON.stringify({schemaVersion:1,projectId:project.id,title:project.title,exportedAt:new Date().toISOString(),files:['project.json','project.md','workspace-artifacts.json','project.csv','project.docx','project.pptx','project.xlsx'],deliverables:project.deliverables.map(d=>({id:d.id,title:d.title,format:d.format,status:d.status,ownerId:d.ownerId||null})),branding:{institutionName:branding.institutionName||null,footer:branding.footer||null},aiDisclosure:{required:Boolean(project.aiPolicy?.disclosureRequired),policyLevel:project.aiPolicy?.level,summary:project.aiPolicy?.summary||''}},null,2),'utf8');
    const readme=Buffer.from('AcademicOS Submission Package\n\nThis package contains editable Office exports plus canonical JSON/Markdown/CSV representations. Verify filenames and course submission requirements before final submission. AI disclosure requirements remain governed by the project policy in submission-manifest.json.\n','utf8');
    return{data:zipStore([{name:'README.txt',data:readme},{name:'submission-manifest.json',data:manifest},{name:'project.json',data:json},{name:'project.md',data:md},{name:'workspace-artifacts.json',data:artifactsJson},{name:'project.csv',data:csv(project,branding)},{name:'project.docx',data:docx(project,artifacts,branding)},{name:'project.pptx',data:pptx(project,branding)},{name:'project.xlsx',data:xlsx(project,branding)}]),contentType:'application/zip',filename:`${safe}.zip`};
  }
  throw Object.assign(new Error('Supported exports: JSON, Markdown, CSV, DOCX, PPTX, XLSX, ZIP. PDF requires the configured isolated renderer.'),{status:400,code:'EXPORT_FORMAT_UNSUPPORTED'});
}

export function exportCitations(evidence: Array<{id:string;type:string;title:string;detail:string;sourceUrl?:string;verification:string}>, format='ris') {
  const sources=evidence.filter(x=>x.type==='source'||Boolean(x.sourceUrl));
  const safeTitle=(v:string)=>String(v||'Untitled source').replace(/[{}]/g,'');
  if(format==='json')return{data:Buffer.from(JSON.stringify({sources},null,2),'utf8'),contentType:'application/json; charset=utf-8',filename:'AcademicOS-bibliography.json'};
  if(format==='bib'||format==='bibtex'){
    const text=sources.map((x,i)=>`@misc{academicos_${i+1},\n  title = {${safeTitle(x.title)}},${x.sourceUrl?`\n  howpublished = {\\url{${x.sourceUrl}}},`:''}\n  note = {Verification: ${x.verification}; ${safeTitle(x.detail).slice(0,500)}}\n}`).join('\n\n');
    return{data:Buffer.from(text,'utf8'),contentType:'application/x-bibtex; charset=utf-8',filename:'AcademicOS-bibliography.bib'};
  }
  const ris=sources.map(x=>['TY  - ELEC',`TI  - ${x.title}`,x.sourceUrl?`UR  - ${x.sourceUrl}`:'',`N1  - Verification: ${x.verification}; ${x.detail.replace(/\r?\n/g,' ').slice(0,500)}`,'ER  -'].filter(Boolean).join('\r\n')).join('\r\n\r\n');
  return{data:Buffer.from(ris,'utf8'),contentType:'application/x-research-info-systems; charset=utf-8',filename:'AcademicOS-bibliography.ris'};
}

export function exportLearningEvidenceReport(project:ProjectDNA,evidence:Array<{source:string;summary:string;evidence:Array<{label:string;value:string}>;createdAt:string}>,format='md'){
  const payload={project:{id:project.id,title:project.title,course:project.course},generatedAt:new Date().toISOString(),learningEvidence:evidence,notice:'Learning evidence documents observed demonstrations and does not predict a final grade.'};
  if(format==='json')return{data:Buffer.from(JSON.stringify(payload,null,2),'utf8'),contentType:'application/json; charset=utf-8',filename:'AcademicOS-learning-evidence.json'};
  const lines=[`# Learning Evidence — ${project.title}`,'',`Course: ${project.course}`,'','This report documents observed learning evidence. It is not an AI-detector score or a final-grade prediction.','',...evidence.flatMap((x,i)=>[`## Evidence ${i+1} — ${x.source}`,x.summary,`Created: ${x.createdAt}`,...x.evidence.map(e=>`- **${e.label}:** ${e.value}`),''])];
  return{data:Buffer.from(lines.join('\n'),'utf8'),contentType:'text/markdown; charset=utf-8',filename:'AcademicOS-learning-evidence.md'};
}

export function exportCourseArchive(course:{id:string;code:string;title:string;term?:string;outcomes:string[];aiPolicy:unknown;status:string;createdAt:string;updatedAt:string},assignments:Array<Record<string,unknown>>){
  const archive={schemaVersion:1,exportedAt:new Date().toISOString(),course,assignments};
  const md=[`# ${course.code} — ${course.title}`,course.term?`Term: ${course.term}`:'',`Status: ${course.status}`,'','## Outcomes',...course.outcomes.map(x=>`- ${x}`),'','## Assignments',...assignments.map((x:any)=>`- ${x.title||x.id} — ${x.status||'unknown'}`)].filter(Boolean).join('\n');
  const manifest={schemaVersion:1,courseId:course.id,files:['course.json','course.md','assignments.json'],records:{assignments:assignments.length},exportedAt:new Date().toISOString()};
  return{data:zipStore([{name:'course.json',data:Buffer.from(JSON.stringify(course,null,2),'utf8')},{name:'course.md',data:Buffer.from(md,'utf8')},{name:'assignments.json',data:Buffer.from(JSON.stringify(assignments,null,2),'utf8')},{name:'archive-manifest.json',data:Buffer.from(JSON.stringify(manifest,null,2),'utf8')}]),contentType:'application/zip',filename:`${course.code.replace(/[^A-Za-z0-9._-]+/g,'_')||'AcademicOS-course'}-archive.zip`};
}
