import { createHash, createPrivateKey, createPublicKey, sign as cryptoSign, verify as cryptoVerify } from 'node:crypto';
import type {
  AcademicTimeMachine, AcademicTimeMachineEvent, AcademicTrustGraph, CourseAssignmentRecord, CourseRecord, CurriculumTwinSimulation,
  CurriculumTwinSnapshot, EvidenceCapsule, LearningBrain, LearningBrainSkill, LearningEvidenceRecord, MissionControlAction, MissionControlPlan,
  PlatformRecord, ProjectActivityRecord, ProjectDNA, ProjectEvidence, ProjectVersionRecord, SkillEvidence, UserProfile, WorkspaceArtifact,
} from '../types';

function isoNow(){ return new Date().toISOString(); }
function normalize(value:string){ return value.trim().replace(/\s+/g,' ').toLocaleLowerCase('en'); }
function dayDiff(date?:string, now=Date.now()){ if(!date)return Number.POSITIVE_INFINITY; return Math.ceil((new Date(date).getTime()-now)/86400000); }
function dateInTimezone(now:number,timezone?:string){
  try{return new Intl.DateTimeFormat('en-CA',{timeZone:timezone||'UTC',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(now));}catch{return new Date(now).toISOString().slice(0,10);}
}
function unique<T>(items:T[]){ return [...new Set(items)]; }
function asStringArray(value:unknown){ return Array.isArray(value)?value.map(String).map(x=>x.trim()).filter(Boolean):[]; }
function stable(value:unknown):unknown{
  if(Array.isArray(value))return value.map(stable);
  if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>[k,stable(v)]));
  return value;
}

export function buildLearningBrain(projects:ProjectDNA[],skills:SkillEvidence[],learning:LearningEvidenceRecord[]):LearningBrain{
  const required=new Map<string,{label:string;count:number;projectIds:Set<string>}>();
  for(const project of projects)for(const label of project.requiredSkills){const key=normalize(label);if(!key)continue;const x=required.get(key)||{label,count:0,projectIds:new Set<string>()};x.count+=1;x.projectIds.add(project.id);required.set(key,x);}
  const evidence=new Map<string,{count:number;institution:number;latest?:string;projectIds:Set<string>}>();
  for(const item of skills){const key=normalize(item.skill);const x=evidence.get(key)||{count:0,institution:0,projectIds:new Set<string>()};x.count+=1;if(item.verificationLevel==='institution')x.institution+=1;if(!x.latest||item.date>x.latest)x.latest=item.date;x.projectIds.add(item.projectId);evidence.set(key,x);}
  const allKeys=unique([...required.keys(),...evidence.keys()]);
  const rows:LearningBrainSkill[]=allKeys.map(key=>{const r=required.get(key),e=evidence.get(key);const evidenceCount=e?.count||0;const institutionVerifiedCount=e?.institution||0;return{skill:r?.label||skills.find(x=>normalize(x.skill)===key)?.skill||key,requiredInProjects:r?.count||0,evidenceCount,institutionVerifiedCount,latestEvidenceAt:e?.latest,state:institutionVerifiedCount>0||evidenceCount>=2?'established':evidenceCount===1?'developing':'needed',projectIds:unique([...(r?.projectIds||[]),...(e?.projectIds||[])])};});
  const strengths=rows.filter(x=>x.evidenceCount>0).sort((a,b)=>b.institutionVerifiedCount-a.institutionVerifiedCount||b.evidenceCount-a.evidenceCount||b.requiredInProjects-a.requiredInProjects).slice(0,6);
  const growthAreas=rows.filter(x=>x.requiredInProjects>0&&x.state!=='established').sort((a,b)=>b.requiredInProjects-a.requiredInProjects||a.evidenceCount-b.evidenceCount).slice(0,6);
  const patterns=new Map<string,{label:string;occurrences:number;projectIds:Set<string>}>();
  for(const p of projects)for(const risk of p.riskFlags){const key=normalize(risk);if(!key)continue;const x=patterns.get(key)||{label:risk,occurrences:0,projectIds:new Set<string>()};x.occurrences+=1;x.projectIds.add(p.id);patterns.set(key,x);}
  const recurringPatterns=[...patterns.values()].filter(x=>x.occurrences>=2).sort((a,b)=>b.occurrences-a.occurrences).slice(0,5).map(x=>({label:x.label,occurrences:x.occurrences,projectIds:[...x.projectIds]}));
  const recentCutoff=Date.now()-30*86400000;const recentLearning=learning.filter(x=>new Date(x.createdAt).getTime()>=recentCutoff).length;const completed=projects.filter(x=>x.status==='completed').length;const completedTasks=projects.reduce((n,p)=>n+p.tasks.filter(t=>t.status==='completed').length,0);
  const momentum:LearningBrain['momentum']=[{label:'مشاريع مكتملة',value:String(completed),tone:completed?'positive':'neutral'},{label:'أدلة تعلم خلال 30 يومًا',value:String(recentLearning),tone:recentLearning?'positive':'neutral'},{label:'مهام مكتملة موثقة',value:String(completedTasks),tone:completedTasks?'positive':'neutral'}];
  const active=projects.filter(p=>p.status!=='completed');
  const recommendedFocus=growthAreas.slice(0,3).map(skill=>{const project=active.find(p=>p.requiredSkills.some(x=>normalize(x)===normalize(skill.skill)));return{skill:skill.skill,reason:skill.evidenceCount?`هذه المهارة مطلوبة في ${skill.requiredInProjects} مشروع/مشاريع ولها دليل واحد فقط حتى الآن.`:`هذه المهارة مطلوبة في ${skill.requiredInProjects} مشروع/مشاريع ولا يوجد لها دليل تعلم محفوظ حتى الآن.`,projectId:project?.id,projectTitle:project?.title};});
  return{generatedAt:isoNow(),projectsAnalyzed:projects.length,completedProjects:completed,evidenceItems:learning.length+skills.length,strengths,growthAreas,recurringPatterns,momentum,recommendedFocus,basis:'يبنى هذا النموذج من مشاريع المستخدم، المهارات المرتبطة بنشاط فعلي، ودليل التعلم المحفوظ فقط. لا يستنتج سمات نفسية أو قدرات شخصية حساسة.'};
}

export function buildMissionControl(projects:ProjectDNA[],profile:UserProfile,brain:LearningBrain,now=Date.now()):MissionControlPlan{
  const configured=Number(profile.dailyStudyMinutes||0);const availableMinutes=configured>=30&&configured<=720?Math.round(configured):150;const source=configured>=30&&configured<=720?'profile':'default';
  const candidates:Array<MissionControlAction&{score:number}>=[];
  for(const project of projects.filter(p=>p.status!=='completed')){
    const days=dayDiff(project.deadlines.final,now);const deadlineScore=days<=1?120:days<=3?95:days<=7?70:days<=14?45:25;const riskScore=Math.min(30,project.riskFlags.length*8);
    const tasks=project.tasks.filter(t=>t.status!=='completed').sort((a,b)=>({in_progress:0,ready:1,needs_review:2,blocked:3,not_started:4} as Record<string,number>)[a.status]-({in_progress:0,ready:1,needs_review:2,blocked:3,not_started:4} as Record<string,number>)[b.status]).slice(0,2);
    for(const task of tasks){const statusScore=task.status==='in_progress'?25:task.status==='ready'?20:task.status==='needs_review'?15:task.status==='blocked'?-15:5;const estimate=Math.max(20,Math.min(120,Number(task.estimatedMinutes||45)));const focus=brain.recommendedFocus.find(x=>x.projectId===project.id)?.skill;let reason=days<=0?'الموعد مستحق أو متجاوز؛ هذه أعلى أولوية الآن.':days<=7?`بقي ${Math.max(0,days)} أيام على التسليم.`:'هذه هي الخطوة الجاهزة التالية في خطة المشروع.';if(project.riskFlags.length)reason+=` يوجد ${project.riskFlags.length} تنبيه/تنبيهات مفتوحة.`;candidates.push({id:`${project.id}_${task.id}`,projectId:project.id,projectTitle:project.title,title:task.title,reason,estimatedMinutes:estimate,priority:days<=2?'critical':days<=7||project.riskFlags.length>1?'important':'normal',taskId:task.id,module:task.module,dueAt:task.dueDate||project.deadlines.final,skillFocus:focus,path:`/app/project/${encodeURIComponent(project.id)}?focus=tasks&task=${encodeURIComponent(task.id)}`,score:deadlineScore+riskScore+statusScore});}
    if(!tasks.length&&project.nextAction)candidates.push({id:`${project.id}_next`,projectId:project.id,projectTitle:project.title,title:project.nextAction,reason:days<=7?`المشروع قريب من موعده النهائي (${Math.max(0,days)} أيام).`:'الخطوة التالية محفوظة في Project DNA.',estimatedMinutes:45,priority:days<=2?'critical':days<=7?'important':'normal',dueAt:project.deadlines.final,path:`/app/project/${encodeURIComponent(project.id)}`,score:deadlineScore+riskScore});
  }
  candidates.sort((a,b)=>b.score-a.score||String(a.dueAt||'').localeCompare(String(b.dueAt||'')));
  const actions:MissionControlAction[]=[];let spent=0;
  for(const item of candidates){if(actions.filter(a=>a.projectId===item.projectId).length>=2)continue;const remaining=availableMinutes-spent;if(remaining<20)break;const allocation=Math.min(item.estimatedMinutes,remaining);const{score:_,...base}=item;const action:MissionControlAction={...base,estimatedMinutes:allocation,reason:allocation<item.estimatedMinutes?`${item.reason} ابدأ اليوم بجلسة تركيز ${allocation} دقيقة من هذه المهمة.`:item.reason};actions.push(action);spent+=allocation;if(spent>=availableMinutes)break;}
  const selectedProjects=new Set(actions.map(x=>x.projectId));const deferred=projects.filter(p=>p.status!=='completed'&&!selectedProjects.has(p.id)).slice(0,6).map(p=>({projectId:p.id,projectTitle:p.title,reason:dayDiff(p.deadlines.final,now)>7?'موعده أبعد من أولويات اليوم الحالية.':'لم يدخل ضمن ميزانية الوقت اليومية بعد ترتيب المخاطر والخطوات الجاهزة.'}));
  const dueWithinSevenDays=projects.filter(p=>p.status!=='completed'&&dayDiff(p.deadlines.final,now)>=0&&dayDiff(p.deadlines.final,now)<=7).length;const pressure=dueWithinSevenDays>=3?{level:'critical' as const,message:`لديك ${dueWithinSevenDays} تسليمات خلال 7 أيام. رتبت اليوم لتقليل مخاطر التزاحم.`,dueWithinSevenDays}:dueWithinSevenDays>=1?{level:'busy' as const,message:`لديك ${dueWithinSevenDays} تسليم/تسليمات خلال 7 أيام.`,dueWithinSevenDays}:{level:'calm' as const,message:'لا توجد تسليمات نهائية خلال 7 أيام؛ يمكن الاستثمار في التقدم العميق بدل الإطفاء السريع.',dueWithinSevenDays};
  const topFocus=brain.recommendedFocus[0];return{generatedAt:isoNow(),date:dateInTimezone(now,profile.timezone),availableMinutes,availableMinutesSource:source,suggestedMinutes:spent,pressure,actions,deferred,brainFocus:topFocus?{skill:topFocus.skill,reason:topFocus.reason}:undefined};
}

function activityLabel(action:string){
  const map:Record<string,{kind:AcademicTimeMachineEvent['kind'];title:string;actorType:AcademicTimeMachineEvent['actorType']}>= {
    'project.create':{kind:'created',title:'إنشاء المشروع',actorType:'human'},'project.update':{kind:'plan',title:'تحديث خطة المشروع',actorType:'human'},'workspace.artifact.upsert':{kind:'work',title:'حفظ عنصر عمل',actorType:'human'},'workspace.artifact.restore':{kind:'version',title:'استعادة إصدار عنصر',actorType:'human'},'workspace.artifact.recycle':{kind:'version',title:'نقل عنصر إلى السلة',actorType:'human'},'evidence.create':{kind:'evidence',title:'إضافة Evidence',actorType:'human'},'learning_evidence.create':{kind:'viva',title:'إنشاء Proof of Learning',actorType:'system'},'viva.start':{kind:'viva',title:'بدء Viva',actorType:'human'},'submission.audit':{kind:'submission',title:'فحص التسليم',actorType:'system'},'ai.faculty.run':{kind:'ai',title:'مراجعة AI Faculty',actorType:'ai'},'comment.create':{kind:'review',title:'تعليق / مراجعة',actorType:'human'},'project.member.upsert':{kind:'work',title:'تحديث فريق المشروع',actorType:'human'},
  };return map[action]||{kind:'system' as const,title:action.replace(/[._]/g,' '),actorType:'system' as const};
}

export function buildTimeMachine(project:ProjectDNA,activity:ProjectActivityRecord[],versions:ProjectVersionRecord[],artifacts:WorkspaceArtifact[],evidence:ProjectEvidence[],learning:LearningEvidenceRecord[],aiRuns:Array<Record<string,unknown>>):AcademicTimeMachine{
  const events:AcademicTimeMachineEvent[]=[{id:`created_${project.id}`,at:project.createdAt,kind:'created',title:'بدأ المشروع',detail:`${project.title} · ${project.course}`,actorType:'human',actor:project.userId,source:'project'}];
  for(const a of activity){const mapped=activityLabel(a.action);events.push({id:`audit_${a.id}`,at:a.timestamp,kind:mapped.kind,title:mapped.title,detail:a.reason||a.action,actorType:mapped.actorType,actor:a.actor,source:'audit'});}
  for(const v of versions)events.push({id:`version_${v.id}`,at:v.createdAt,kind:'version',title:`نسخة المشروع v${v.versionNumber}`,detail:v.summary||'Project state version',actorType:'human',actor:v.actorId,source:'project_version',version:v.versionNumber});
  for(const item of artifacts)events.push({id:`artifact_${item.id}`,at:item.updatedAt,kind:'work',title:item.title,detail:`${item.module} · ${item.status}${item.isCanonical?' · مرجع معتمد':''}`,actorType:'human',actor:item.updatedBy,source:'artifact',version:item.revision});
  for(const item of evidence)events.push({id:`evidence_${item.id}`,at:item.updatedAt,kind:'evidence',title:item.title,detail:`${item.type} · ${item.verification}`,actorType:'human',actor:item.userId,source:'evidence'});
  for(const item of learning)events.push({id:`learning_${item.id}`,at:item.createdAt,kind:item.source==='viva'?'viva':'evidence',title:'دليل تعلم',detail:item.summary,actorType:'human',actor:item.userId,source:'learning_evidence'});
  for(const run of aiRuns){const at=String(run.createdAt||'');if(!at)continue;events.push({id:`ai_${String(run.id||createHash('sha1').update(JSON.stringify(run)).digest('hex').slice(0,12))}`,at,kind:'ai',title:'AI assistance',detail:`${String(run.provider||'provider')} · ${String(run.model||'model')} · ${String(run.taskType||run.type||'academic task')}`,actorType:'ai',actor:String(run.userId||''),source:'ai_run'});}
  const dedup=new Map<string,AcademicTimeMachineEvent>();for(const e of events){const key=`${e.at}|${e.title}|${e.source}|${e.actor||''}`;if(!dedup.has(key))dedup.set(key,e);}const sorted=[...dedup.values()].sort((a,b)=>a.at.localeCompare(b.at));
  return{projectId:project.id,generatedAt:isoNow(),events:sorted,summary:{humanEvents:sorted.filter(x=>x.actorType==='human').length,aiEvents:sorted.filter(x=>x.actorType==='ai').length,evidenceEvents:sorted.filter(x=>x.kind==='evidence'||x.kind==='viva').length,versions:versions.length,firstAt:sorted[0]?.at,latestAt:sorted[sorted.length-1]?.at}};
}

export function buildTrustGraph(project:ProjectDNA,artifacts:WorkspaceArtifact[],evidence:ProjectEvidence[],learning:LearningEvidenceRecord[],skills:SkillEvidence[]):AcademicTrustGraph{
  const nodes:AcademicTrustGraph['nodes']=[];const edges:AcademicTrustGraph['edges']=[];const addNode=(node:AcademicTrustGraph['nodes'][number])=>{if(!nodes.some(x=>x.id===node.id))nodes.push(node)};const addEdge=(edge:AcademicTrustGraph['edges'][number])=>{if(!edges.some(x=>x.id===edge.id))edges.push(edge)};
  addNode({id:`project_${project.id}`,type:'project',label:project.title,trust:'recorded',meta:{course:project.course,status:project.status}});
  for(const d of project.deliverables){const id=`deliverable_${d.id}`;addNode({id,type:'deliverable',label:d.title,trust:'recorded',meta:{format:d.format,status:d.status}});addEdge({id:`project_${project.id}__${id}`,from:`project_${project.id}`,to:id,relation:'requires',basis:'explicit'});}
  for(const r of project.rubric){const id=`rubric_${r.id}`;addNode({id,type:'rubric',label:r.title,trust:'recorded',meta:{weighting:r.weighting,readiness:r.readiness||'not_evidenced'}});addEdge({id:`project_${project.id}__${id}`,from:`project_${project.id}`,to:id,relation:'measures',basis:'explicit'});}
  for(const a of artifacts){const id=`artifact_${a.id}`;addNode({id,type:'artifact',label:a.title,trust:'recorded',meta:{module:a.module,status:a.status,canonical:Boolean(a.isCanonical),revision:a.revision||0}});addEdge({id:`${id}__project`,from:id,to:`project_${project.id}`,relation:'belongs_to',basis:'explicit'});if(a.deliverableId)addEdge({id:`${id}__deliverable_${a.deliverableId}`,from:id,to:`deliverable_${a.deliverableId}`,relation:'supports',basis:'explicit'});for(const rid of a.rubricIds||[])addEdge({id:`${id}__rubric_${rid}`,from:id,to:`rubric_${rid}`,relation:'satisfies',basis:'explicit'});}
  for(const e of evidence){const id=`evidence_${e.id}`;addNode({id,type:'evidence',label:e.title,trust:e.verification==='institution_verified'?'institution_verified':e.verification==='user_verified'?'user_verified':'recorded',meta:{type:e.type,verification:e.verification,hasSourceUrl:Boolean(e.sourceUrl)}});addEdge({id:`${id}__project`,from:id,to:`project_${project.id}`,relation:'supports',basis:'explicit'});}
  for(const e of evidence){const id=`evidence_${e.id}`;for(const related of e.relatedEvidenceIds||[])if(evidence.some(x=>x.id===related))addEdge({id:`${id}__evidence_${related}`,from:id,to:`evidence_${related}`,relation:'derived_from',basis:'explicit'});if(e.artifactId&&artifacts.some(x=>x.id===e.artifactId))addEdge({id:`${id}__artifact_${e.artifactId}`,from:id,to:`artifact_${e.artifactId}`,relation:'supports',basis:'explicit'});if(e.deliverableId&&project.deliverables.some(x=>x.id===e.deliverableId))addEdge({id:`${id}__deliverable_${e.deliverableId}`,from:id,to:`deliverable_${e.deliverableId}`,relation:'supports',basis:'explicit'});for(const rid of e.rubricIds||[])if(project.rubric.some(x=>x.id===rid))addEdge({id:`${id}__rubric_${rid}`,from:id,to:`rubric_${rid}`,relation:'satisfies',basis:'explicit'});}
  const projectSkills=skills.filter(s=>s.projectId===project.id);for(const label of project.requiredSkills){const id=`skill_${createHash('sha1').update(normalize(label)).digest('hex').slice(0,12)}`;addNode({id,type:'skill',label,trust:'recorded'});addEdge({id:`project_${project.id}__${id}`,from:`project_${project.id}`,to:id,relation:'requires',basis:'explicit'});}for(const s of projectSkills){const sid=`skill_${createHash('sha1').update(normalize(s.skill)).digest('hex').slice(0,12)}`,eid=`skill_evidence_${s.id}`;addNode({id:sid,type:'skill',label:s.skill,trust:'recorded'});addNode({id:eid,type:'evidence',label:`Skill evidence · ${s.skill}`,trust:s.verificationLevel==='institution'?'institution_verified':'derived',meta:{verificationLevel:s.verificationLevel,date:s.date}});addEdge({id:`${eid}__${sid}`,from:eid,to:sid,relation:'proves',basis:'system_derived'});}
  for(const l of learning){const id=`learning_${l.id}`;addNode({id,type:'learning_evidence',label:l.summary.slice(0,100)||'Proof of Learning',trust:'recorded',meta:{source:l.source}});addEdge({id:`${id}__project`,from:id,to:`project_${project.id}`,relation:'proves',basis:'explicit'});}
  const canonicalSources=artifacts.filter(a=>a.isCanonical).map(a=>({artifactId:a.id,title:a.title,module:a.module,updatedAt:a.updatedAt,linkedDeliverable:project.deliverables.find(d=>d.id===a.deliverableId)?.title,linkedRubric:(a.rubricIds||[]).map(id=>project.rubric.find(r=>r.id===id)?.title||id)}));
  const linkedDeliverables=new Set([...artifacts.map(a=>a.deliverableId),...evidence.map(e=>e.deliverableId)].filter(Boolean));const linkedRubric=new Set([...artifacts.flatMap(a=>a.rubricIds||[]),...evidence.flatMap(e=>e.rubricIds||[])]);
  return{projectId:project.id,generatedAt:isoNow(),nodes,edges,canonicalSources,coverage:{deliverablesLinked:linkedDeliverables.size,deliverablesTotal:project.deliverables.length,rubricLinked:linkedRubric.size,rubricTotal:project.rubric.length,verifiedEvidence:evidence.filter(e=>e.verification!=='unverified').length,totalEvidence:evidence.length},note:'العلاقات Explicit عندما أدخلها المستخدم أو أنشأها النظام من حقول ربط محفوظة. علاقات Skill Evidence الموسومة system_derived مبنية على سجل نشاط المشروع ولا تُعامل كتحقق مؤسسي ما لم يكن مستوى التحقق institution.'};
}

export function buildEvidenceCapsule(project:ProjectDNA,artifacts:WorkspaceArtifact[],evidence:ProjectEvidence[],learning:LearningEvidenceRecord[],skills:SkillEvidence[],aiRuns:Array<Record<string,unknown>>,signingPrivateKeyB64?:string):EvidenceCapsule{
  const projectSkills=skills.filter(s=>s.projectId===project.id);const contributors=new Set<string>([project.userId,...artifacts.flatMap(a=>[a.createdBy,a.updatedBy]).filter(Boolean),...evidence.map(e=>e.userId).filter(Boolean),...learning.map(l=>l.userId).filter(Boolean)]);
  const base= {schemaVersion:'1.0' as const,generatedAt:isoNow(),project:{id:project.id,title:project.title,course:project.course,status:project.status,updatedAt:project.updatedAt},skills:projectSkills.map(s=>({skill:s.skill,verificationLevel:s.verificationLevel,evidence:s.evidence,date:s.date})),deliverables:project.deliverables.map(d=>({title:d.title,format:d.format,status:d.status})),rubric:project.rubric.map(r=>({title:r.title,weighting:r.weighting,readiness:r.readiness||'not_evidenced'})),proofOfLearning:learning.map(l=>({id:l.id,source:l.source,summary:l.summary,createdAt:l.createdAt})),provenance:{artifacts:artifacts.length,canonicalArtifacts:artifacts.filter(a=>a.isCanonical).length,evidenceItems:evidence.length,verifiedEvidenceItems:evidence.filter(e=>e.verification!=='unverified').length,aiAssistedRuns:aiRuns.length,humanContributors:contributors.size},disclosure:'هذه الكبسولة تلخص أدلة محفوظة داخل AcademicOS. لا تمثل Transcript أو درجة نهائية، ولا ترفع مستوى التحقق عن المستوى المسجل لكل دليل.'};
  const canonical=JSON.stringify(stable(base));const hash=createHash('sha256').update(canonical).digest('hex');
  if(!signingPrivateKeyB64)return{...base,integrity:{algorithm:'SHA-256',hash,signatureStatus:'hash_only'}};
  const privatePem=Buffer.from(signingPrivateKeyB64,'base64').toString('utf8');const privateKey=createPrivateKey(privatePem),publicKey=createPublicKey(privateKey);const publicDer=publicKey.export({type:'spki',format:'der'}) as Buffer;const signature=cryptoSign(null,Buffer.from(hash,'hex'),privateKey).toString('base64url');const publicKeySpki=publicDer.toString('base64url');const keyId=createHash('sha256').update(publicDer).digest('hex').slice(0,20);
  return{...base,integrity:{algorithm:'SHA-256',hash,signatureStatus:'signed',signature,signatureAlgorithm:'Ed25519',publicKeySpki,keyId}};
}

export function verifyEvidenceCapsule(capsule:EvidenceCapsule,trustedSigningPrivateKeyB64?:string,trustedPublicKeySpkiB64url:string[]=[]){
  const{integrity,...base}=capsule;const hash=createHash('sha256').update(JSON.stringify(stable(base))).digest('hex');const hashValid=hash===integrity.hash;if(!hashValid)return{hashValid:false,signatureValid:false,signerTrusted:false,status:'invalid' as const};if(integrity.signatureStatus!=='signed')return{hashValid:true,signatureValid:null,signerTrusted:null,status:'hash_valid' as const};if(!integrity.signature||integrity.signatureAlgorithm!=='Ed25519'||!integrity.publicKeySpki)return{hashValid:true,signatureValid:false,signerTrusted:false,status:'invalid' as const};try{const publicDer=Buffer.from(integrity.publicKeySpki,'base64url');const publicKey=createPublicKey({key:publicDer,format:'der',type:'spki'});const signatureValid=cryptoVerify(null,Buffer.from(hash,'hex'),publicKey,Buffer.from(integrity.signature,'base64url'));if(!signatureValid)return{hashValid:true,signatureValid:false,signerTrusted:false,status:'invalid' as const,keyId:integrity.keyId};let signerTrusted=trustedPublicKeySpkiB64url.some(key=>{try{return Buffer.from(key,'base64url').equals(publicDer)}catch{return false}});if(!signerTrusted&&trustedSigningPrivateKeyB64){const trustedPrivate=createPrivateKey(Buffer.from(trustedSigningPrivateKeyB64,'base64').toString('utf8'));const trustedDer=createPublicKey(trustedPrivate).export({type:'spki',format:'der'}) as Buffer;signerTrusted=trustedDer.equals(publicDer);}return{hashValid:true,signatureValid:true,signerTrusted,status:signerTrusted?'signed_trusted' as const:'signed_untrusted' as const,keyId:integrity.keyId};}catch{return{hashValid:true,signatureValid:false,signerTrusted:false,status:'invalid' as const};}
}

function buildCurriculum(courses:CourseRecord[],assignments:CourseAssignmentRecord[],program?:PlatformRecord,curriculumMap?:PlatformRecord,forcedExpected:string[]=[]):CurriculumTwinSnapshot{
  const mappedCourseIds=asStringArray(curriculumMap?.data?.courseIds);const selected=mappedCourseIds.length?courses.filter(c=>mappedCourseIds.includes(c.id)):courses;const selectedIds=new Set(selected.map(c=>c.id));const selectedAssignments=assignments.filter(a=>selectedIds.has(a.courseId));const expected=unique([...forcedExpected,...asStringArray(program?.data?.outcomes),...asStringArray(program?.data?.programOutcomes),...asStringArray(curriculumMap?.data?.outcomes),...asStringArray(curriculumMap?.data?.programOutcomes),...selected.flatMap(c=>c.outcomes),...selectedAssignments.flatMap(a=>a.outcomes)]);
  const outcomeRows=expected.map(outcome=>{const key=normalize(outcome);const courseIds=selected.filter(c=>c.outcomes.some(x=>normalize(x)===key)).map(c=>c.id);const assignmentIds=selectedAssignments.filter(a=>a.outcomes.some(x=>normalize(x)===key)).map(a=>a.id);const status=courseIds.length===0&&assignmentIds.length===0?'uncovered':courseIds.length===1||assignmentIds.length===0?'thin':'covered';return{outcome,courseIds,assignmentIds,status} as CurriculumTwinSnapshot['outcomes'][number];});
  const courseRows=selected.map(c=>{const related=selectedAssignments.filter(a=>a.courseId===c.id);return{id:c.id,code:c.code,title:c.title,term:c.term,outcomes:c.outcomes,assignmentCount:related.length,assignmentOutcomeLinks:related.reduce((n,a)=>n+a.outcomes.length,0)}});
  const terms=unique(selected.map(c=>c.term||'غير محدد'));const workloadByTerm=terms.map(term=>{const cs=selected.filter(c=>(c.term||'غير محدد')===term);const ids=new Set(cs.map(c=>c.id));return{term,assignments:selectedAssignments.filter(a=>ids.has(a.courseId)).length,courses:cs.length}}).sort((a,b)=>a.term.localeCompare(b.term));
  return{generatedAt:isoNow(),programId:program?.id,programTitle:program?.title,courses:courseRows,outcomes:outcomeRows,uncoveredOutcomes:outcomeRows.filter(x=>x.status==='uncovered').map(x=>x.outcome),thinOutcomes:outcomeRows.filter(x=>x.status==='thin').map(x=>x.outcome),duplicateSignals:outcomeRows.filter(x=>x.courseIds.length>=3).map(x=>({outcome:x.outcome,courseCount:x.courseIds.length})),workloadByTerm,sourceNote:curriculumMap?`تم تطبيق Curriculum Map: ${curriculumMap.title}.`:'لا يوجد Curriculum Map محدد لهذا العرض؛ التحليل الحالي يستخدم المقررات والتكليفات الموجودة في الـtenant فقط.'};
}

export function buildCurriculumTwin(courses:CourseRecord[],assignments:CourseAssignmentRecord[],programs:PlatformRecord[],maps:PlatformRecord[],programId?:string):CurriculumTwinSnapshot{
  const program=programId?programs.find(x=>x.id===programId):programs[0];const map=maps.find(x=>String(x.data?.programId||'')===String(program?.id||''))||(!programId?maps[0]:undefined);return buildCurriculum(courses,assignments,program,map);
}

export function simulateCurriculumTwin(courses:CourseRecord[],assignments:CourseAssignmentRecord[],programs:PlatformRecord[],maps:PlatformRecord[],input:{programId?:string;removeCourseIds?:string[];courseOutcomeOverrides?:Record<string,string[]>;termOverrides?:Record<string,string>}):CurriculumTwinSimulation{
  const program=input.programId?programs.find(x=>x.id===input.programId):programs[0];const map=maps.find(x=>String(x.data?.programId||'')===String(program?.id||''))||(!input.programId?maps[0]:undefined);const baseline=buildCurriculum(courses,assignments,program,map);const remove=new Set(input.removeCourseIds||[]);const scenarioCourses=courses.filter(c=>!remove.has(c.id)).map(c=>({...c,outcomes:input.courseOutcomeOverrides?.[c.id]||c.outcomes,term:input.termOverrides?.[c.id]||c.term}));const scenarioAssignments=assignments.filter(a=>!remove.has(a.courseId));const scenario=buildCurriculum(scenarioCourses,scenarioAssignments,program,map,baseline.outcomes.map(x=>x.outcome));const scenBy=new Map(scenario.outcomes.map(x=>[normalize(x.outcome),x]));const newlyUncovered=baseline.outcomes.filter(x=>x.status!=='uncovered'&&scenBy.get(normalize(x.outcome))?.status==='uncovered').map(x=>x.outcome);const reduced=baseline.outcomes.filter(x=>{const s=scenBy.get(normalize(x.outcome));return s&&x.courseIds.length>s.courseIds.length&&!newlyUncovered.includes(x.outcome)}).map(x=>x.outcome);const lost=baseline.outcomes.reduce((n,x)=>n+x.assignmentIds.length,0)-scenario.outcomes.reduce((n,x)=>n+x.assignmentIds.length,0);const removedCourses=baseline.courses.filter(c=>remove.has(c.id)).map(c=>({id:c.id,code:c.code,title:c.title}));const riskLevel=newlyUncovered.length?'high':reduced.length||lost>0?'moderate':'low';const summary=riskLevel==='high'?`السيناريو يترك ${newlyUncovered.length} Outcome بلا تغطية ظاهرة.`:riskLevel==='moderate'?`لا توجد فجوة كاملة جديدة، لكن انخفضت تغطية ${reduced.length} Outcome وفُقد ${Math.max(0,lost)} رابط Evidence من التكليفات.`:'لم يظهر فقد تغطية في البيانات الحالية لهذا السيناريو.';return{baseline,scenario,impact:{removedCourses,newlyUncoveredOutcomes:newlyUncovered,reducedCoverageOutcomes:reduced,assignmentEvidenceLinksLost:Math.max(0,lost),riskLevel,summary}};
}
