import { createHash, createPrivateKey, createPublicKey, sign as cryptoSign, verify as cryptoVerify } from 'node:crypto';
import type {
  AcademicTimeMachine, AcademicTimeMachineEvent, AcademicTrustGraph, CourseAssignmentRecord, CourseRecord, CurriculumTwinSimulation,
  CurriculumTwinSnapshot, EvidenceCapsule, LearningBrain, LearningBrainSkill, LearningEvidenceRecord, MissionControlAction, MissionControlPlan,
  PlatformRecord, ProjectActivityRecord, ProjectDNA, ProjectEvidence, ProjectVersionRecord, SkillEvidence, UserProfile, WorkspaceArtifact,
} from '../types';
import { L, resolveServerLocale, tx, txf, type ServerLocale } from './server-locale';

// Learning Brain, Mission Control, the Time Machine and the curriculum twin all
// render generated sentences straight to the user, so they are localized rather
// than emitted in one fixed language.
const INT = {
  momentumCompleted: L("مشاريع مكتملة", "Completed projects", "Tamamlanan projeler", "已完成项目", "पूर्ण प्रोजेक्ट", "Proyectos completados", "Projets terminés", "مکمل پروجیکٹس"),
  momentumEvidence: L("أدلة تعلم خلال 30 يومًا", "Learning evidence in 30 days", "30 gündeki öğrenme kanıtı", "30 天内的学习证据", "30 दिनों में अधिगम प्रमाण", "Evidencias de aprendizaje en 30 días", "Preuves d'apprentissage sur 30 jours", "30 دنوں میں سیکھنے کے شواہد"),
  momentumTasks: L("مهام مكتملة موثقة", "Documented completed tasks", "Belgelenmiş tamamlanan görevler", "已记录的完成任务", "प्रलेखित पूर्ण कार्य", "Tareas completadas documentadas", "Tâches terminées documentées", "دستاویزی مکمل کام"),
  focusSomeEvidence: L("هذه المهارة مطلوبة في {count} مشروع/مشاريع ولها دليل واحد فقط حتى الآن.", "This skill is required in {count} project(s) and has only one piece of evidence so far.", "Bu beceri {count} projede gerekli ve şimdiye dek tek bir kanıtı var.", "该技能在 {count} 个项目中被要求，目前只有一项证据。", "यह कौशल {count} प्रोजेक्ट में आवश्यक है और अब तक केवल एक प्रमाण है।", "Esta habilidad se requiere en {count} proyecto(s) y solo tiene una evidencia hasta ahora.", "Cette compétence est requise dans {count} projet(s) et ne compte qu'une seule preuve à ce jour.", "یہ مہارت {count} پروجیکٹس میں درکار ہے اور اب تک صرف ایک شہادت ہے۔"),
  focusNoEvidence: L("هذه المهارة مطلوبة في {count} مشروع/مشاريع ولا يوجد لها دليل تعلم محفوظ حتى الآن.", "This skill is required in {count} project(s) and has no saved learning evidence yet.", "Bu beceri {count} projede gerekli ve henüz kayıtlı bir öğrenme kanıtı yok.", "该技能在 {count} 个项目中被要求，但尚无已保存的学习证据。", "यह कौशल {count} प्रोजेक्ट में आवश्यक है और अभी तक कोई सहेजा गया अधिगम प्रमाण नहीं है।", "Esta habilidad se requiere en {count} proyecto(s) y aún no tiene evidencia de aprendizaje guardada.", "Cette compétence est requise dans {count} projet(s) et n'a encore aucune preuve d'apprentissage enregistrée.", "یہ مہارت {count} پروجیکٹس میں درکار ہے اور ابھی تک کوئی محفوظ شہادت نہیں۔"),
  brainBasis: L("يبنى هذا النموذج من مشاريع المستخدم، المهارات المرتبطة بنشاط فعلي، ودليل التعلم المحفوظ فقط. لا يستنتج سمات نفسية أو قدرات شخصية حساسة.", "This model is built only from your projects, skills tied to real activity, and saved learning evidence. It does not infer psychological traits or sensitive personal abilities.", "Bu model yalnızca projelerinizden, gerçek etkinliğe bağlı becerilerden ve kayıtlı öğrenme kanıtından oluşur. Psikolojik özellik veya hassas kişisel yetenek çıkarımı yapmaz.", "该模型仅基于你的项目、与真实活动相关的技能以及已保存的学习证据构建，不推断心理特质或敏感的个人能力。", "यह मॉडल केवल आपके प्रोजेक्ट, वास्तविक गतिविधि से जुड़े कौशल और सहेजे गए अधिगम प्रमाण से बनता है। यह मनोवैज्ञानिक गुण या संवेदनशील व्यक्तिगत क्षमताएँ नहीं आँकता।", "Este modelo se construye solo con tus proyectos, las habilidades ligadas a actividad real y la evidencia de aprendizaje guardada. No infiere rasgos psicológicos ni capacidades personales sensibles.", "Ce modèle est construit uniquement à partir de vos projets, des compétences liées à une activité réelle et des preuves d'apprentissage enregistrées. Il n'infère aucun trait psychologique ni aptitude personnelle sensible.", "یہ ماڈل صرف آپ کے پروجیکٹس، حقیقی سرگرمی سے جڑی مہارتوں اور محفوظ شواہد سے بنتا ہے۔ یہ نفسیاتی خصوصیات یا حساس ذاتی صلاحیتیں اخذ نہیں کرتا۔"),
  reasonOverdue: L("الموعد مستحق أو متجاوز؛ هذه أعلى أولوية الآن.", "The deadline is due or passed; this is the top priority right now.", "Teslim tarihi geldi ya da geçti; şu an en yüksek öncelik bu.", "截止时间已到或已过期；这是当前最高优先级。", "समय-सीमा आ चुकी है या बीत गई; अभी यही सर्वोच्च प्राथमिकता है।", "El plazo vence o ya pasó; ahora es la máxima prioridad.", "L'échéance est arrivée ou dépassée ; c'est la priorité absolue maintenant.", "آخری تاریخ آ چکی یا گزر گئی؛ ابھی یہی اولین ترجیح ہے۔"),
  reasonDaysLeft: L("بقي {days} أيام على التسليم.", "{days} days left until submission.", "Teslime {days} gün kaldı.", "距离提交还有 {days} 天。", "सबमिशन में {days} दिन बचे हैं।", "Quedan {days} días para la entrega.", "Il reste {days} jours avant le rendu.", "جمع میں {days} دن باقی ہیں۔"),
  reasonNextStep: L("هذه هي الخطوة الجاهزة التالية في خطة المشروع.", "This is the next ready step in the project plan.", "Proje planındaki bir sonraki hazır adım bu.", "这是项目计划中下一个可执行的步骤。", "यह प्रोजेक्ट योजना का अगला तैयार चरण है।", "Este es el siguiente paso listo del plan del proyecto.", "C'est la prochaine étape prête du plan de projet.", "یہ پروجیکٹ منصوبے کا اگلا تیار مرحلہ ہے۔"),
  reasonOpenRisks: L(" يوجد {count} تنبيه/تنبيهات مفتوحة.", " {count} open risk flag(s) remain.", " {count} açık risk uyarısı var.", " 还有 {count} 条未处理的风险提示。", " {count} खुले जोखिम-संकेत बाकी हैं।", " Quedan {count} avisos de riesgo abiertos.", " Il reste {count} alertes de risque ouvertes.", " {count} کھلے خطرے کے اشارے باقی ہیں۔"),
  reasonNearDeadline: L("المشروع قريب من موعده النهائي ({days} أيام).", "The project is close to its deadline ({days} days).", "Proje teslim tarihine yaklaştı ({days} gün).", "该项目接近截止日期（{days} 天）。", "प्रोजेक्ट अपनी समय-सीमा के निकट है ({days} दिन)।", "El proyecto está cerca de su fecha límite ({days} días).", "Le projet approche de son échéance ({days} jours).", "پروجیکٹ اپنی آخری تاریخ کے قریب ہے ({days} دن)۔"),
  reasonDnaNext: L("الخطوة التالية محفوظة في Project DNA.", "The next step is saved in the project DNA.", "Sonraki adım Project DNA'da kayıtlı.", "下一步已保存在项目 DNA 中。", "अगला चरण प्रोजेक्ट DNA में सहेजा गया है।", "El siguiente paso está guardado en el ADN del proyecto.", "L'étape suivante est enregistrée dans l'ADN du projet.", "اگلا مرحلہ پروجیکٹ DNA میں محفوظ ہے۔"),
  reasonFocusSession: L("{reason} ابدأ اليوم بجلسة تركيز {minutes} دقيقة من هذه المهمة.", "{reason} Start today with a {minutes}-minute focus session on this task.", "{reason} Bugüne bu görev için {minutes} dakikalık bir odak seansıyla başlayın.", "{reason} 今天先用 {minutes} 分钟专注处理这项任务。", "{reason} आज इस कार्य पर {minutes} मिनट का फ़ोकस सत्र से शुरू करें।", "{reason} Empieza hoy con una sesión de enfoque de {minutes} minutos en esta tarea.", "{reason} Commencez aujourd'hui par une session de concentration de {minutes} minutes sur cette tâche.", "{reason} آج اس کام پر {minutes} منٹ کے فوکس سیشن سے آغاز کریں۔"),
  deferredFar: L("موعده أبعد من أولويات اليوم الحالية.", "Its deadline is further out than today's priorities.", "Teslim tarihi bugünkü önceliklerden daha uzakta.", "它的截止时间比今天的优先事项更远。", "इसकी समय-सीमा आज की प्राथमिकताओं से दूर है।", "Su plazo está más lejos que las prioridades de hoy.", "Son échéance est plus lointaine que les priorités du jour.", "اس کی آخری تاریخ آج کی ترجیحات سے دور ہے۔"),
  deferredBudget: L("لم يدخل ضمن ميزانية الوقت اليومية بعد ترتيب المخاطر والخطوات الجاهزة.", "It did not fit today's time budget after ranking risks and ready steps.", "Riskler ve hazır adımlar sıralandıktan sonra günlük zaman bütçesine sığmadı.", "在排序风险与可执行步骤后，它未能进入今天的时间预算。", "जोखिम व तैयार चरणों की रैंकिंग के बाद यह आज के समय-बजट में नहीं आया।", "No entró en el presupuesto de tiempo de hoy tras ordenar riesgos y pasos listos.", "Il n'est pas entré dans le budget de temps du jour après le classement des risques et des étapes prêtes.", "خطرات اور تیار مراحل کی ترتیب کے بعد یہ آج کے وقت بجٹ میں نہ آ سکا۔"),
  pressureCritical: L("لديك {count} تسليمات خلال 7 أيام. رتبت اليوم لتقليل مخاطر التزاحم.", "You have {count} submissions within 7 days. Today is ordered to reduce the pile-up risk.", "7 gün içinde {count} teslimatınız var. Bugün, yığılma riskini azaltacak şekilde sıralandı.", "你在 7 天内有 {count} 项提交。今天的顺序已按降低堆积风险安排。", "आपके पास 7 दिनों में {count} सबमिशन हैं। भीड़ का जोखिम घटाने के लिए आज का क्रम बनाया गया है।", "Tienes {count} entregas en 7 días. El día se ordenó para reducir el riesgo de acumulación.", "Vous avez {count} rendus sous 7 jours. La journée est ordonnée pour limiter l'effet d'accumulation.", "آپ کے پاس 7 دن میں {count} جمع ہیں۔ آج کی ترتیب ازدحام کا خطرہ کم کرنے کے لیے ہے۔"),
  pressureBusy: L("لديك {count} تسليم/تسليمات خلال 7 أيام.", "You have {count} submission(s) within 7 days.", "7 gün içinde {count} teslimatınız var.", "你在 7 天内有 {count} 项提交。", "आपके पास 7 दिनों में {count} सबमिशन हैं।", "Tienes {count} entrega(s) en 7 días.", "Vous avez {count} rendu(s) sous 7 jours.", "آپ کے پاس 7 دن میں {count} جمع ہیں۔"),
  pressureCalm: L("لا توجد تسليمات نهائية خلال 7 أيام؛ يمكن الاستثمار في التقدم العميق بدل الإطفاء السريع.", "No final submissions in the next 7 days; invest in deep progress rather than firefighting.", "Önümüzdeki 7 günde nihai teslim yok; yangın söndürmek yerine derin ilerlemeye yatırım yapın.", "未来 7 天没有最终提交；可以投入深度推进，而不是救火。", "अगले 7 दिनों में कोई अंतिम सबमिशन नहीं; आग बुझाने के बजाय गहन प्रगति में निवेश करें।", "No hay entregas finales en 7 días; invierte en avance profundo en lugar de apagar incendios.", "Aucun rendu final sous 7 jours ; investissez dans un travail de fond plutôt que dans l'urgence.", "اگلے 7 دن میں کوئی حتمی جمع نہیں؛ آگ بجھانے کے بجائے گہری پیش رفت میں سرمایہ کاری کریں۔"),
  evProjectCreate: L("إنشاء المشروع", "Project created", "Proje oluşturuldu", "创建项目", "प्रोजेक्ट बनाया गया", "Proyecto creado", "Projet créé", "پروجیکٹ بنایا گیا"),
  evProjectUpdate: L("تحديث خطة المشروع", "Project plan updated", "Proje planı güncellendi", "更新项目计划", "प्रोजेक्ट योजना अपडेट", "Plan del proyecto actualizado", "Plan du projet mis à jour", "پروجیکٹ منصوبہ اپ ڈیٹ"),
  evArtifactSave: L("حفظ عنصر عمل", "Work item saved", "İş öğesi kaydedildi", "保存工作项", "वर्क आइटम सहेजा गया", "Elemento de trabajo guardado", "Élément de travail enregistré", "ورک آئٹم محفوظ"),
  evArtifactRestore: L("استعادة إصدار عنصر", "Work item version restored", "İş öğesi sürümü geri yüklendi", "恢复工作项版本", "वर्क आइटम संस्करण बहाल", "Versión del elemento restaurada", "Version de l'élément restaurée", "ورک آئٹم ورژن بحال"),
  evArtifactRecycle: L("نقل عنصر إلى السلة", "Work item moved to trash", "İş öğesi çöp kutusuna taşındı", "工作项移入回收站", "वर्क आइटम ट्रैश में", "Elemento movido a la papelera", "Élément déplacé vers la corbeille", "ورک آئٹم ردی میں"),
  evEvidence: L("إضافة Evidence", "Evidence added", "Kanıt eklendi", "添加证据", "प्रमाण जोड़ा गया", "Evidencia añadida", "Preuve ajoutée", "شہادت شامل"),
  evProofOfLearning: L("إنشاء Proof of Learning", "Proof of Learning created", "Öğrenme Kanıtı oluşturuldu", "生成学习证明", "प्रूफ़ ऑफ़ लर्निंग बना", "Prueba de aprendizaje creada", "Preuve d'apprentissage créée", "پروف آف لرننگ بنا"),
  evVivaStart: L("بدء Viva", "Viva started", "Viva başladı", "开始答辩", "वाइवा शुरू", "Viva iniciada", "Soutenance démarrée", "وائیوا شروع"),
  evSubmissionAudit: L("فحص التسليم", "Submission audit", "Teslim denetimi", "提交审查", "सबमिशन ऑडिट", "Auditoría de entrega", "Audit de rendu", "جمع کا آڈٹ"),
  evAiFaculty: L("مراجعة AI Faculty", "AI Faculty review", "AI Faculty incelemesi", "AI 教师评审", "AI फ़ैकल्टी समीक्षा", "Revisión de AI Faculty", "Revue AI Faculty", "AI فیکلٹی جائزہ"),
  evComment: L("تعليق / مراجعة", "Comment / review", "Yorum / inceleme", "评论 / 复核", "टिप्पणी / समीक्षा", "Comentario / revisión", "Commentaire / revue", "تبصرہ / جائزہ"),
  evTeam: L("تحديث فريق المشروع", "Project team updated", "Proje ekibi güncellendi", "更新项目团队", "प्रोजेक्ट टीम अपडेट", "Equipo del proyecto actualizado", "Équipe du projet mise à jour", "پروجیکٹ ٹیم اپ ڈیٹ"),
  evProjectStarted: L("بدأ المشروع", "Project started", "Proje başladı", "项目启动", "प्रोजेक्ट शुरू", "Proyecto iniciado", "Projet démarré", "پروجیکٹ شروع"),
  evProjectVersion: L("نسخة المشروع v{version}", "Project snapshot v{version}", "Proje sürümü v{version}", "项目快照 v{version}", "प्रोजेक्ट स्नैपशॉट v{version}", "Instantánea del proyecto v{version}", "Version du projet v{version}", "پروجیکٹ اسنیپ شاٹ v{version}"),
  evCanonical: L(" · مرجع معتمد", " · canonical reference", " · onaylı referans", " · 权威参考", " · प्रामाणिक संदर्भ", " · referencia canónica", " · référence canonique", " · مستند حوالہ"),
  evLearning: L("دليل تعلم", "Learning evidence", "Öğrenme kanıtı", "学习证据", "अधिगम प्रमाण", "Evidencia de aprendizaje", "Preuve d'apprentissage", "سیکھنے کی شہادت"),
  trustNote: L("العلاقات Explicit عندما أدخلها المستخدم أو أنشأها النظام من حقول ربط محفوظة. علاقات Skill Evidence الموسومة system_derived مبنية على سجل نشاط المشروع ولا تُعامل كتحقق مؤسسي ما لم يكن مستوى التحقق institution.", "Relationships are explicit when the user entered them or the system built them from saved link fields. Skill-evidence relationships marked system_derived come from the project activity log and are not treated as institutional verification unless the verification level is institution.", "İlişkiler, kullanıcı girdiğinde ya da sistem kayıtlı bağlantı alanlarından oluşturduğunda açıktır. system_derived işaretli beceri kanıtı ilişkileri proje etkinlik kaydından gelir ve doğrulama düzeyi institution olmadıkça kurumsal doğrulama sayılmaz.", "当关系由用户录入或系统依据已保存的关联字段生成时，即为显式关系。标记为 system_derived 的技能证据关系来自项目活动日志，除非验证级别为 institution，否则不视为机构验证。", "संबंध तब स्पष्ट होते हैं जब उपयोगकर्ता ने उन्हें दर्ज किया या सिस्टम ने सहेजे गए लिंक फ़ील्ड से बनाया। system_derived चिह्नित कौशल-प्रमाण संबंध प्रोजेक्ट गतिविधि लॉग से आते हैं और संस्थागत सत्यापन नहीं माने जाते जब तक स्तर institution न हो।", "Las relaciones son explícitas cuando las introdujo el usuario o el sistema las construyó a partir de campos de enlace guardados. Las relaciones de evidencia de habilidad marcadas system_derived provienen del registro de actividad y no se consideran verificación institucional salvo que el nivel sea institution.", "Les relations sont explicites lorsqu'elles ont été saisies par l'utilisateur ou construites par le système à partir de champs de liaison enregistrés. Les relations de preuve de compétence marquées system_derived proviennent du journal d'activité et ne valent pas vérification institutionnelle sauf si le niveau est institution.", "تعلقات اُس وقت واضح ہوتے ہیں جب صارف نے درج کیے یا نظام نے محفوظ لنک فیلڈز سے بنائے۔ system_derived نشان زد مہارت شواہد پروجیکٹ سرگرمی لاگ سے آتے ہیں اور جب تک سطح institution نہ ہو، ادارہ جاتی تصدیق نہیں مانے جاتے۔"),
  capsuleDisclosure: L("هذه الكبسولة تلخص أدلة محفوظة داخل AcademicOS. لا تمثل Transcript أو درجة نهائية، ولا ترفع مستوى التحقق عن المستوى المسجل لكل دليل.", "This capsule summarises evidence stored inside AcademicOS. It is not a transcript or a final grade, and it does not raise any item's verification above its recorded level.", "Bu kapsül, AcademicOS içinde saklanan kanıtları özetler. Bir transkript veya nihai not değildir ve hiçbir öğenin doğrulamasını kayıtlı düzeyinin üstüne çıkarmaz.", "本凭证汇总了 AcademicOS 内保存的证据。它不是成绩单或最终成绩，也不会把任何条目的验证级别提高到其记录级别之上。", "यह कैप्सूल AcademicOS में संग्रहीत प्रमाणों का सार है। यह ट्रांसक्रिप्ट या अंतिम ग्रेड नहीं है, और किसी आइटम का सत्यापन उसके दर्ज स्तर से ऊपर नहीं करता।", "Esta cápsula resume la evidencia almacenada en AcademicOS. No es un expediente ni una nota final, y no eleva la verificación de ningún elemento por encima de su nivel registrado.", "Cette capsule résume les preuves stockées dans AcademicOS. Ce n'est ni un relevé de notes ni une note finale, et elle n'élève la vérification d'aucun élément au-dessus de son niveau enregistré.", "یہ کیپسول AcademicOS میں محفوظ شواہد کا خلاصہ ہے۔ یہ ٹرانسکرپٹ یا حتمی گریڈ نہیں، اور کسی شے کی تصدیق اُس کے درج درجے سے اوپر نہیں لے جاتا۔"),
  termUnspecified: L("غير محدد", "Unspecified", "Belirtilmemiş", "未指定", "अनिर्दिष्ट", "Sin especificar", "Non précisé", "غیر متعین"),
  curriculumMapApplied: L("تم تطبيق Curriculum Map: {title}.", "Curriculum map applied: {title}.", "Müfredat haritası uygulandı: {title}.", "已应用课程图谱：{title}。", "पाठ्यचर्या मानचित्र लागू: {title}।", "Mapa curricular aplicado: {title}.", "Cartographie du curriculum appliquée : {title}.", "نصابی نقشہ لاگو: {title}۔"),
  curriculumNoMap: L("لا يوجد Curriculum Map محدد لهذا العرض؛ التحليل الحالي يستخدم المقررات والتكليفات الموجودة في الـtenant فقط.", "No curriculum map is selected for this view; the current analysis uses only the courses and assignments in this tenant.", "Bu görünüm için seçili bir müfredat haritası yok; mevcut analiz yalnızca bu kiracıdaki ders ve ödevleri kullanıyor.", "此视图未选择课程图谱；当前分析仅使用该租户内的课程与作业。", "इस दृश्य के लिए कोई पाठ्यचर्या मानचित्र चयनित नहीं; वर्तमान विश्लेषण केवल इस टेनेंट के कोर्स व असाइनमेंट उपयोग करता है।", "No hay mapa curricular seleccionado para esta vista; el análisis actual usa solo los cursos y tareas de este tenant.", "Aucune cartographie du curriculum n'est sélectionnée pour cette vue ; l'analyse actuelle n'utilise que les cours et devoirs de ce tenant.", "اس منظر کے لیے کوئی نصابی نقشہ منتخب نہیں؛ موجودہ تجزیہ صرف اسی ٹیننٹ کے کورسز اور اسائنمنٹس استعمال کرتا ہے۔"),
  simHigh: L("السيناريو يترك {count} Outcome بلا تغطية ظاهرة.", "The scenario leaves {count} outcome(s) with no visible coverage.", "Senaryo {count} kazanımı görünür kapsam olmadan bırakıyor.", "该情景使 {count} 项学习成果失去可见覆盖。", "यह परिदृश्य {count} आउटकम को दृश्य कवरेज के बिना छोड़ता है।", "El escenario deja {count} resultado(s) sin cobertura visible.", "Le scénario laisse {count} acquis sans couverture visible.", "یہ منظرنامہ {count} نتائج کو نمایاں کوریج کے بغیر چھوڑتا ہے۔"),
  simModerate: L("لا توجد فجوة كاملة جديدة، لكن انخفضت تغطية {reduced} Outcome وفُقد {lost} رابط Evidence من التكليفات.", "No new complete gap appeared, but coverage dropped for {reduced} outcome(s) and {lost} assignment evidence link(s) were lost.", "Yeni tam bir boşluk oluşmadı, ancak {reduced} kazanımın kapsamı düştü ve {lost} ödev kanıt bağlantısı kayboldu.", "没有出现新的完全缺口，但 {reduced} 项成果的覆盖下降，并失去 {lost} 条作业证据关联。", "कोई नया पूर्ण अंतर नहीं आया, पर {reduced} आउटकम की कवरेज घटी और {lost} असाइनमेंट प्रमाण-लिंक खोए।", "No apareció un vacío completo nuevo, pero la cobertura bajó en {reduced} resultado(s) y se perdieron {lost} enlaces de evidencia.", "Aucun manque complet nouveau, mais la couverture a baissé pour {reduced} acquis et {lost} liens de preuve ont été perdus.", "کوئی نیا مکمل خلا نہیں آیا، مگر {reduced} نتائج کی کوریج کم ہوئی اور {lost} شہادتی روابط ضائع ہوئے۔"),
  simLow: L("لم يظهر فقد تغطية في البيانات الحالية لهذا السيناريو.", "No coverage loss appeared in the current data for this scenario.", "Bu senaryo için mevcut veride kapsam kaybı görülmedi.", "在当前数据下，该情景未出现覆盖损失。", "इस परिदृश्य हेतु वर्तमान डेटा में कोई कवरेज हानि नहीं दिखी।", "No se detectó pérdida de cobertura en los datos actuales para este escenario.", "Aucune perte de couverture n'apparaît dans les données actuelles pour ce scénario.", "اس منظرنامے کے لیے موجودہ ڈیٹا میں کوریج کا نقصان نہیں ملا۔"),
} as const;

function isoNow(){ return new Date().toISOString(); }
function normalize(value:string){ return value.trim().replace(/\s+/g,' ').toLocaleLowerCase('en'); }
function dayDiff(date?:string, now=Date.now()){ if(!date)return Number.POSITIVE_INFINITY; return Math.ceil((new Date(date).getTime()-now)/86400000); }
function dateInTimezone(now:number,timezone?:string){
  try{return new Intl.DateTimeFormat('en-CA',{timeZone:timezone||'UTC',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(now));}catch{return new Date(now).toISOString().slice(0,10);}
}
function unique<T>(items:T[]){ return [...new Set(items)]; }
function asStringArray(value:unknown){ return Array.isArray(value)?value.map(String).map(x=>x.trim()).filter(Boolean):[]; }
function stable(value:unknown):unknown{
  if(Array.isArray(value))return value.map(stable);
  if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>[k,stable(v)]));
  return value;
}

export function buildLearningBrain(projects:ProjectDNA[],skills:SkillEvidence[],learning:LearningEvidenceRecord[],requestedLocale?:string):LearningBrain{
  const locale:ServerLocale=resolveServerLocale(requestedLocale);
  const required=new Map<string,{label:string;count:number;projectIds:Set<string>}>();
  for(const project of projects)for(const label of project.requiredSkills){const key=normalize(label);if(!key)continue;const x=required.get(key)||{label,count:0,projectIds:new Set<string>()};x.count+=1;x.projectIds.add(project.id);required.set(key,x);}
  const evidence=new Map<string,{count:number;institution:number;latest?:string;projectIds:Set<string>}>();
  for(const item of skills){const key=normalize(item.skill);const x=evidence.get(key)||{count:0,institution:0,projectIds:new Set<string>()};x.count+=1;if(item.verificationLevel==='institution')x.institution+=1;if(!x.latest||item.date>x.latest)x.latest=item.date;x.projectIds.add(item.projectId);evidence.set(key,x);}
  const allKeys=unique([...required.keys(),...evidence.keys()]);
  const rows:LearningBrainSkill[]=allKeys.map(key=>{const r=required.get(key),e=evidence.get(key);const evidenceCount=e?.count||0;const institutionVerifiedCount=e?.institution||0;return{skill:r?.label||skills.find(x=>normalize(x.skill)===key)?.skill||key,requiredInProjects:r?.count||0,evidenceCount,institutionVerifiedCount,latestEvidenceAt:e?.latest,state:institutionVerifiedCount>0||evidenceCount>=2?'established':evidenceCount===1?'developing':'needed',projectIds:unique([...(r?.projectIds||[]),...(e?.projectIds||[])])};});
  const strengths=rows.filter(x=>x.evidenceCount>0).sort((a,b)=>b.institutionVerifiedCount-a.institutionVerifiedCount||b.evidenceCount-a.evidenceCount||b.requiredInProjects-a.requiredInProjects).slice(0,6);
  const growthAreas=rows.filter(x=>x.requiredInProjects>0&&x.state!=='established').sort((a,b)=>b.requiredInProjects-a.requiredInProjects||a.evidenceCount-b.evidenceCount).slice(0,6);
  const patterns=new Map<string,{label:string;occurrences:number;projectIds:Set<string>}>();
  for(const p of projects)for(const risk of p.riskFlags){const key=normalize(risk);if(!key)continue;const x=patterns.get(key)||{label:risk,occurrences:0,projectIds:new Set<string>()};x.occurrences+=1;x.projectIds.add(p.id);patterns.set(key,x);}
  const recurringPatterns=[...patterns.values()].filter(x=>x.occurrences>=2).sort((a,b)=>b.occurrences-a.occurrences).slice(0,5).map(x=>({label:x.label,occurrences:x.occurrences,projectIds:[...x.projectIds]}));
  const recentCutoff=Date.now()-30*86400000;const recentLearning=learning.filter(x=>new Date(x.createdAt).getTime()>=recentCutoff).length;const completed=projects.filter(x=>x.status==='completed').length;const completedTasks=projects.reduce((n,p)=>n+p.tasks.filter(t=>t.status==='completed').length,0);
  const momentum:LearningBrain['momentum']=[{label:tx(INT.momentumCompleted,locale),value:String(completed),tone:completed?'positive':'neutral'},{label:tx(INT.momentumEvidence,locale),value:String(recentLearning),tone:recentLearning?'positive':'neutral'},{label:tx(INT.momentumTasks,locale),value:String(completedTasks),tone:completedTasks?'positive':'neutral'}];
  const active=projects.filter(p=>p.status!=='completed');
  const recommendedFocus=growthAreas.slice(0,3).map(skill=>{const project=active.find(p=>p.requiredSkills.some(x=>normalize(x)===normalize(skill.skill)));return{skill:skill.skill,reason:txf(skill.evidenceCount?INT.focusSomeEvidence:INT.focusNoEvidence,locale,{count:skill.requiredInProjects}),projectId:project?.id,projectTitle:project?.title};});
  return{generatedAt:isoNow(),projectsAnalyzed:projects.length,completedProjects:completed,evidenceItems:learning.length+skills.length,strengths,growthAreas,recurringPatterns,momentum,recommendedFocus,basis:tx(INT.brainBasis,locale)};
}

export function buildMissionControl(projects:ProjectDNA[],profile:UserProfile,brain:LearningBrain,now=Date.now(),requestedLocale?:string):MissionControlPlan{
  const locale:ServerLocale=resolveServerLocale(requestedLocale,profile.language);
  const configured=Number(profile.dailyStudyMinutes||0);const availableMinutes=configured>=30&&configured<=720?Math.round(configured):150;const source=configured>=30&&configured<=720?'profile':'default';
  const candidates:Array<MissionControlAction&{score:number}>=[];
  for(const project of projects.filter(p=>p.status!=='completed')){
    const days=dayDiff(project.deadlines.final,now);const deadlineScore=days<=1?120:days<=3?95:days<=7?70:days<=14?45:25;const riskScore=Math.min(30,project.riskFlags.length*8);
    const tasks=project.tasks.filter(t=>t.status!=='completed').sort((a,b)=>({in_progress:0,ready:1,needs_review:2,blocked:3,not_started:4} as Record<string,number>)[a.status]-({in_progress:0,ready:1,needs_review:2,blocked:3,not_started:4} as Record<string,number>)[b.status]).slice(0,2);
    for(const task of tasks){const statusScore=task.status==='in_progress'?25:task.status==='ready'?20:task.status==='needs_review'?15:task.status==='blocked'?-15:5;const estimate=Math.max(20,Math.min(120,Number(task.estimatedMinutes||45)));const focus=brain.recommendedFocus.find(x=>x.projectId===project.id)?.skill;let reason=days<=0?tx(INT.reasonOverdue,locale):days<=7?txf(INT.reasonDaysLeft,locale,{days:Math.max(0,days)}):tx(INT.reasonNextStep,locale);if(project.riskFlags.length)reason+=txf(INT.reasonOpenRisks,locale,{count:project.riskFlags.length});candidates.push({id:`${project.id}_${task.id}`,projectId:project.id,projectTitle:project.title,title:task.title,reason,estimatedMinutes:estimate,priority:days<=2?'critical':days<=7||project.riskFlags.length>1?'important':'normal',taskId:task.id,module:task.module,dueAt:task.dueDate||project.deadlines.final,skillFocus:focus,path:`/app/project/${encodeURIComponent(project.id)}?focus=tasks&task=${encodeURIComponent(task.id)}`,score:deadlineScore+riskScore+statusScore});}
    if(!tasks.length&&project.nextAction)candidates.push({id:`${project.id}_next`,projectId:project.id,projectTitle:project.title,title:project.nextAction,reason:days<=7?txf(INT.reasonNearDeadline,locale,{days:Math.max(0,days)}):tx(INT.reasonDnaNext,locale),estimatedMinutes:45,priority:days<=2?'critical':days<=7?'important':'normal',dueAt:project.deadlines.final,path:`/app/project/${encodeURIComponent(project.id)}`,score:deadlineScore+riskScore});
  }
  candidates.sort((a,b)=>b.score-a.score||String(a.dueAt||'').localeCompare(String(b.dueAt||'')));
  const actions:MissionControlAction[]=[];let spent=0;
  for(const item of candidates){if(actions.filter(a=>a.projectId===item.projectId).length>=2)continue;const remaining=availableMinutes-spent;if(remaining<20)break;const allocation=Math.min(item.estimatedMinutes,remaining);const{score:_,...base}=item;const action:MissionControlAction={...base,estimatedMinutes:allocation,reason:allocation<item.estimatedMinutes?txf(INT.reasonFocusSession,locale,{reason:item.reason,minutes:allocation}):item.reason};actions.push(action);spent+=allocation;if(spent>=availableMinutes)break;}
  const selectedProjects=new Set(actions.map(x=>x.projectId));const deferred=projects.filter(p=>p.status!=='completed'&&!selectedProjects.has(p.id)).slice(0,6).map(p=>({projectId:p.id,projectTitle:p.title,reason:dayDiff(p.deadlines.final,now)>7?tx(INT.deferredFar,locale):tx(INT.deferredBudget,locale)}));
  const dueWithinSevenDays=projects.filter(p=>p.status!=='completed'&&dayDiff(p.deadlines.final,now)>=0&&dayDiff(p.deadlines.final,now)<=7).length;const pressure=dueWithinSevenDays>=3?{level:'critical' as const,message:txf(INT.pressureCritical,locale,{count:dueWithinSevenDays}),dueWithinSevenDays}:dueWithinSevenDays>=1?{level:'busy' as const,message:txf(INT.pressureBusy,locale,{count:dueWithinSevenDays}),dueWithinSevenDays}:{level:'calm' as const,message:tx(INT.pressureCalm,locale),dueWithinSevenDays};
  const topFocus=brain.recommendedFocus[0];return{generatedAt:isoNow(),date:dateInTimezone(now,profile.timezone),availableMinutes,availableMinutesSource:source,suggestedMinutes:spent,pressure,actions,deferred,brainFocus:topFocus?{skill:topFocus.skill,reason:topFocus.reason}:undefined};
}

function activityLabel(action:string,locale:ServerLocale){
  const map:Record<string,{kind:AcademicTimeMachineEvent['kind'];title:string;actorType:AcademicTimeMachineEvent['actorType']}>= {
    'project.create':{kind:'created',title:tx(INT.evProjectCreate,locale),actorType:'human'},'project.update':{kind:'plan',title:tx(INT.evProjectUpdate,locale),actorType:'human'},'workspace.artifact.upsert':{kind:'work',title:tx(INT.evArtifactSave,locale),actorType:'human'},'workspace.artifact.restore':{kind:'version',title:tx(INT.evArtifactRestore,locale),actorType:'human'},'workspace.artifact.recycle':{kind:'version',title:tx(INT.evArtifactRecycle,locale),actorType:'human'},'evidence.create':{kind:'evidence',title:tx(INT.evEvidence,locale),actorType:'human'},'learning_evidence.create':{kind:'viva',title:tx(INT.evProofOfLearning,locale),actorType:'system'},'viva.start':{kind:'viva',title:tx(INT.evVivaStart,locale),actorType:'human'},'submission.audit':{kind:'submission',title:tx(INT.evSubmissionAudit,locale),actorType:'system'},'ai.faculty.run':{kind:'ai',title:tx(INT.evAiFaculty,locale),actorType:'ai'},'comment.create':{kind:'review',title:tx(INT.evComment,locale),actorType:'human'},'project.member.upsert':{kind:'work',title:tx(INT.evTeam,locale),actorType:'human'},
  };return map[action]||{kind:'system' as const,title:action.replace(/[._]/g,' '),actorType:'system' as const};
}

export function buildTimeMachine(project:ProjectDNA,activity:ProjectActivityRecord[],versions:ProjectVersionRecord[],artifacts:WorkspaceArtifact[],evidence:ProjectEvidence[],learning:LearningEvidenceRecord[],aiRuns:Array<Record<string,unknown>>,requestedLocale?:string):AcademicTimeMachine{
  const locale:ServerLocale=resolveServerLocale(requestedLocale,project.language);
  const events:AcademicTimeMachineEvent[]=[{id:`created_${project.id}`,at:project.createdAt,kind:'created',title:tx(INT.evProjectStarted,locale),detail:`${project.title} · ${project.course}`,actorType:'human',actor:project.userId,source:'project'}];
  for(const a of activity){const mapped=activityLabel(a.action,locale);events.push({id:`audit_${a.id}`,at:a.timestamp,kind:mapped.kind,title:mapped.title,detail:a.reason||a.action,actorType:mapped.actorType,actor:a.actor,source:'audit'});}
  for(const v of versions)events.push({id:`version_${v.id}`,at:v.createdAt,kind:'version',title:txf(INT.evProjectVersion,locale,{version:v.versionNumber}),detail:v.summary||'Project state version',actorType:'human',actor:v.actorId,source:'project_version',version:v.versionNumber});
  for(const item of artifacts)events.push({id:`artifact_${item.id}`,at:item.updatedAt,kind:'work',title:item.title,detail:`${item.module} · ${item.status}${item.isCanonical?tx(INT.evCanonical,locale):''}`,actorType:'human',actor:item.updatedBy,source:'artifact',version:item.revision});
  for(const item of evidence)events.push({id:`evidence_${item.id}`,at:item.updatedAt,kind:'evidence',title:item.title,detail:`${item.type} · ${item.verification}`,actorType:'human',actor:item.userId,source:'evidence'});
  for(const item of learning)events.push({id:`learning_${item.id}`,at:item.createdAt,kind:item.source==='viva'?'viva':'evidence',title:tx(INT.evLearning,locale),detail:item.summary,actorType:'human',actor:item.userId,source:'learning_evidence'});
  for(const run of aiRuns){const at=String(run.createdAt||'');if(!at)continue;events.push({id:`ai_${String(run.id||createHash('sha1').update(JSON.stringify(run)).digest('hex').slice(0,12))}`,at,kind:'ai',title:'AI assistance',detail:`${String(run.provider||'provider')} · ${String(run.model||'model')} · ${String(run.taskType||run.type||'academic task')}`,actorType:'ai',actor:String(run.userId||''),source:'ai_run'});}
  const dedup=new Map<string,AcademicTimeMachineEvent>();for(const e of events){const key=`${e.at}|${e.title}|${e.source}|${e.actor||''}`;if(!dedup.has(key))dedup.set(key,e);}const sorted=[...dedup.values()].sort((a,b)=>a.at.localeCompare(b.at));
  return{projectId:project.id,generatedAt:isoNow(),events:sorted,summary:{humanEvents:sorted.filter(x=>x.actorType==='human').length,aiEvents:sorted.filter(x=>x.actorType==='ai').length,evidenceEvents:sorted.filter(x=>x.kind==='evidence'||x.kind==='viva').length,versions:versions.length,firstAt:sorted[0]?.at,latestAt:sorted[sorted.length-1]?.at}};
}

export function buildTrustGraph(project:ProjectDNA,artifacts:WorkspaceArtifact[],evidence:ProjectEvidence[],learning:LearningEvidenceRecord[],skills:SkillEvidence[],requestedLocale?:string):AcademicTrustGraph{
  const locale:ServerLocale=resolveServerLocale(requestedLocale,project.language);
  const nodes:AcademicTrustGraph['nodes']=[];const edges:AcademicTrustGraph['edges']=[];const addNode=(node:AcademicTrustGraph['nodes'][number])=>{if(!nodes.some(x=>x.id===node.id))nodes.push(node)};const addEdge=(edge:AcademicTrustGraph['edges'][number])=>{if(!edges.some(x=>x.id===edge.id))edges.push(edge)};
  addNode({id:`project_${project.id}`,type:'project',label:project.title,trust:'recorded',meta:{course:project.course,status:project.status}});
  for(const d of project.deliverables){const id=`deliverable_${d.id}`;addNode({id,type:'deliverable',label:d.title,trust:'recorded',meta:{format:d.format,status:d.status}});addEdge({id:`project_${project.id}__${id}`,from:`project_${project.id}`,to:id,relation:'requires',basis:'explicit'});}
  for(const r of project.rubric){const id=`rubric_${r.id}`;addNode({id,type:'rubric',label:r.title,trust:'recorded',meta:{weighting:r.weighting,readiness:r.readiness||'not_evidenced'}});addEdge({id:`project_${project.id}__${id}`,from:`project_${project.id}`,to:id,relation:'measures',basis:'explicit'});}
  for(const a of artifacts){const id=`artifact_${a.id}`;addNode({id,type:'artifact',label:a.title,trust:'recorded',meta:{module:a.module,status:a.status,canonical:Boolean(a.isCanonical),revision:a.revision||0}});addEdge({id:`${id}__project`,from:id,to:`project_${project.id}`,relation:'belongs_to',basis:'explicit'});if(a.deliverableId)addEdge({id:`${id}__deliverable_${a.deliverableId}`,from:id,to:`deliverable_${a.deliverableId}`,relation:'supports',basis:'explicit'});for(const rid of a.rubricIds||[])addEdge({id:`${id}__rubric_${rid}`,from:id,to:`rubric_${rid}`,relation:'satisfies',basis:'explicit'});}
  for(const e of evidence){const id=`evidence_${e.id}`;addNode({id,type:'evidence',label:e.title,trust:e.verification==='institution_verified'?'institution_verified':e.verification==='user_verified'?'user_verified':'recorded',meta:{type:e.type,verification:e.verification,hasSourceUrl:Boolean(e.sourceUrl)}});addEdge({id:`${id}__project`,from:id,to:`project_${project.id}`,relation:'supports',basis:'explicit'});}
  for(const e of evidence){const id=`evidence_${e.id}`;for(const related of e.relatedEvidenceIds||[])if(evidence.some(x=>x.id===related))addEdge({id:`${id}__evidence_${related}`,from:id,to:`evidence_${related}`,relation:'derived_from',basis:'explicit'});if(e.artifactId&&artifacts.some(x=>x.id===e.artifactId))addEdge({id:`${id}__artifact_${e.artifactId}`,from:id,to:`artifact_${e.artifactId}`,relation:'supports',basis:'explicit'});if(e.deliverableId&&project.deliverables.some(x=>x.id===e.deliverableId))addEdge({id:`${id}__deliverable_${e.deliverableId}`,from:id,to:`deliverable_${e.deliverableId}`,relation:'supports',basis:'explicit'});for(const rid of e.rubricIds||[])if(project.rubric.some(x=>x.id===rid))addEdge({id:`${id}__rubric_${rid}`,from:id,to:`rubric_${rid}`,relation:'satisfies',basis:'explicit'});}
  const projectSkills=skills.filter(s=>s.projectId===project.id);for(const label of project.requiredSkills){const id=`skill_${createHash('sha1').update(normalize(label)).digest('hex').slice(0,12)}`;addNode({id,type:'skill',label,trust:'recorded'});addEdge({id:`project_${project.id}__${id}`,from:`project_${project.id}`,to:id,relation:'requires',basis:'explicit'});}for(const s of projectSkills){const sid=`skill_${createHash('sha1').update(normalize(s.skill)).digest('hex').slice(0,12)}`,eid=`skill_evidence_${s.id}`;addNode({id:sid,type:'skill',label:s.skill,trust:'recorded'});addNode({id:eid,type:'evidence',label:`Skill evidence · ${s.skill}`,trust:s.verificationLevel==='institution'?'institution_verified':'derived',meta:{verificationLevel:s.verificationLevel,date:s.date}});addEdge({id:`${eid}__${sid}`,from:eid,to:sid,relation:'proves',basis:'system_derived'});}
  for(const l of learning){const id=`learning_${l.id}`;addNode({id,type:'learning_evidence',label:l.summary.slice(0,100)||'Proof of Learning',trust:'recorded',meta:{source:l.source}});addEdge({id:`${id}__project`,from:id,to:`project_${project.id}`,relation:'proves',basis:'explicit'});}
  const canonicalSources=artifacts.filter(a=>a.isCanonical).map(a=>({artifactId:a.id,title:a.title,module:a.module,updatedAt:a.updatedAt,linkedDeliverable:project.deliverables.find(d=>d.id===a.deliverableId)?.title,linkedRubric:(a.rubricIds||[]).map(id=>project.rubric.find(r=>r.id===id)?.title||id)}));
  const linkedDeliverables=new Set([...artifacts.map(a=>a.deliverableId),...evidence.map(e=>e.deliverableId)].filter(Boolean));const linkedRubric=new Set([...artifacts.flatMap(a=>a.rubricIds||[]),...evidence.flatMap(e=>e.rubricIds||[])]);
  return{projectId:project.id,generatedAt:isoNow(),nodes,edges,canonicalSources,coverage:{deliverablesLinked:linkedDeliverables.size,deliverablesTotal:project.deliverables.length,rubricLinked:linkedRubric.size,rubricTotal:project.rubric.length,verifiedEvidence:evidence.filter(e=>e.verification!=='unverified').length,totalEvidence:evidence.length},note:tx(INT.trustNote,locale)};
}

export function buildEvidenceCapsule(project:ProjectDNA,artifacts:WorkspaceArtifact[],evidence:ProjectEvidence[],learning:LearningEvidenceRecord[],skills:SkillEvidence[],aiRuns:Array<Record<string,unknown>>,signingPrivateKeyB64?:string,requestedLocale?:string):EvidenceCapsule{
  const locale:ServerLocale=resolveServerLocale(requestedLocale,project.language);
  const projectSkills=skills.filter(s=>s.projectId===project.id);const contributors=new Set<string>([project.userId,...artifacts.flatMap(a=>[a.createdBy,a.updatedBy]).filter(Boolean),...evidence.map(e=>e.userId).filter(Boolean),...learning.map(l=>l.userId).filter(Boolean)]);
  const base= {schemaVersion:'1.0' as const,generatedAt:isoNow(),project:{id:project.id,title:project.title,course:project.course,status:project.status,updatedAt:project.updatedAt},skills:projectSkills.map(s=>({skill:s.skill,verificationLevel:s.verificationLevel,evidence:s.evidence,date:s.date})),deliverables:project.deliverables.map(d=>({title:d.title,format:d.format,status:d.status})),rubric:project.rubric.map(r=>({title:r.title,weighting:r.weighting,readiness:r.readiness||'not_evidenced'})),proofOfLearning:learning.map(l=>({id:l.id,source:l.source,summary:l.summary,createdAt:l.createdAt})),provenance:{artifacts:artifacts.length,canonicalArtifacts:artifacts.filter(a=>a.isCanonical).length,evidenceItems:evidence.length,verifiedEvidenceItems:evidence.filter(e=>e.verification!=='unverified').length,aiAssistedRuns:aiRuns.length,humanContributors:contributors.size},disclosure:tx(INT.capsuleDisclosure,locale)};
  const canonical=JSON.stringify(stable(base));const hash=createHash('sha256').update(canonical).digest('hex');
  if(!signingPrivateKeyB64)return{...base,integrity:{algorithm:'SHA-256',hash,signatureStatus:'hash_only'}};
  const privatePem=Buffer.from(signingPrivateKeyB64,'base64').toString('utf8');const privateKey=createPrivateKey(privatePem),publicKey=createPublicKey(privateKey);const publicDer=publicKey.export({type:'spki',format:'der'}) as Buffer;const signature=cryptoSign(null,Buffer.from(hash,'hex'),privateKey).toString('base64url');const publicKeySpki=publicDer.toString('base64url');const keyId=createHash('sha256').update(publicDer).digest('hex').slice(0,20);
  return{...base,integrity:{algorithm:'SHA-256',hash,signatureStatus:'signed',signature,signatureAlgorithm:'Ed25519',publicKeySpki,keyId}};
}

export function verifyEvidenceCapsule(capsule:EvidenceCapsule,trustedSigningPrivateKeyB64?:string,trustedPublicKeySpkiB64url:string[]=[]){
  const{integrity,...base}=capsule;const hash=createHash('sha256').update(JSON.stringify(stable(base))).digest('hex');const hashValid=hash===integrity.hash;if(!hashValid)return{hashValid:false,signatureValid:false,signerTrusted:false,status:'invalid' as const};if(integrity.signatureStatus!=='signed')return{hashValid:true,signatureValid:null,signerTrusted:null,status:'hash_valid' as const};if(!integrity.signature||integrity.signatureAlgorithm!=='Ed25519'||!integrity.publicKeySpki)return{hashValid:true,signatureValid:false,signerTrusted:false,status:'invalid' as const};try{const publicDer=Buffer.from(integrity.publicKeySpki,'base64url');const publicKey=createPublicKey({key:publicDer,format:'der',type:'spki'});const signatureValid=cryptoVerify(null,Buffer.from(hash,'hex'),publicKey,Buffer.from(integrity.signature,'base64url'));if(!signatureValid)return{hashValid:true,signatureValid:false,signerTrusted:false,status:'invalid' as const,keyId:integrity.keyId};let signerTrusted=trustedPublicKeySpkiB64url.some(key=>{try{return Buffer.from(key,'base64url').equals(publicDer)}catch{return false}});if(!signerTrusted&&trustedSigningPrivateKeyB64){const trustedPrivate=createPrivateKey(Buffer.from(trustedSigningPrivateKeyB64,'base64').toString('utf8'));const trustedDer=createPublicKey(trustedPrivate).export({type:'spki',format:'der'}) as Buffer;signerTrusted=trustedDer.equals(publicDer);}return{hashValid:true,signatureValid:true,signerTrusted,status:signerTrusted?'signed_trusted' as const:'signed_untrusted' as const,keyId:integrity.keyId};}catch{return{hashValid:true,signatureValid:false,signerTrusted:false,status:'invalid' as const};}
}

function buildCurriculum(courses:CourseRecord[],assignments:CourseAssignmentRecord[],program?:PlatformRecord,curriculumMap?:PlatformRecord,forcedExpected:string[]=[],locale:ServerLocale='en'):CurriculumTwinSnapshot{
  const unspecifiedTerm=tx(INT.termUnspecified,locale);
  const mappedCourseIds=asStringArray(curriculumMap?.data?.courseIds);const selected=mappedCourseIds.length?courses.filter(c=>mappedCourseIds.includes(c.id)):courses;const selectedIds=new Set(selected.map(c=>c.id));const selectedAssignments=assignments.filter(a=>selectedIds.has(a.courseId));const expected=unique([...forcedExpected,...asStringArray(program?.data?.outcomes),...asStringArray(program?.data?.programOutcomes),...asStringArray(curriculumMap?.data?.outcomes),...asStringArray(curriculumMap?.data?.programOutcomes),...selected.flatMap(c=>c.outcomes),...selectedAssignments.flatMap(a=>a.outcomes)]);
  const outcomeRows=expected.map(outcome=>{const key=normalize(outcome);const courseIds=selected.filter(c=>c.outcomes.some(x=>normalize(x)===key)).map(c=>c.id);const assignmentIds=selectedAssignments.filter(a=>a.outcomes.some(x=>normalize(x)===key)).map(a=>a.id);const status=courseIds.length===0&&assignmentIds.length===0?'uncovered':courseIds.length===1||assignmentIds.length===0?'thin':'covered';return{outcome,courseIds,assignmentIds,status} as CurriculumTwinSnapshot['outcomes'][number];});
  const courseRows=selected.map(c=>{const related=selectedAssignments.filter(a=>a.courseId===c.id);return{id:c.id,code:c.code,title:c.title,term:c.term,outcomes:c.outcomes,assignmentCount:related.length,assignmentOutcomeLinks:related.reduce((n,a)=>n+a.outcomes.length,0)}});
  const terms=unique(selected.map(c=>c.term||unspecifiedTerm));const workloadByTerm=terms.map(term=>{const cs=selected.filter(c=>(c.term||unspecifiedTerm)===term);const ids=new Set(cs.map(c=>c.id));return{term,assignments:selectedAssignments.filter(a=>ids.has(a.courseId)).length,courses:cs.length}}).sort((a,b)=>a.term.localeCompare(b.term));
  return{generatedAt:isoNow(),programId:program?.id,programTitle:program?.title,courses:courseRows,outcomes:outcomeRows,uncoveredOutcomes:outcomeRows.filter(x=>x.status==='uncovered').map(x=>x.outcome),thinOutcomes:outcomeRows.filter(x=>x.status==='thin').map(x=>x.outcome),duplicateSignals:outcomeRows.filter(x=>x.courseIds.length>=3).map(x=>({outcome:x.outcome,courseCount:x.courseIds.length})),workloadByTerm,sourceNote:curriculumMap?txf(INT.curriculumMapApplied,locale,{title:curriculumMap.title}):tx(INT.curriculumNoMap,locale)};
}

export function buildCurriculumTwin(courses:CourseRecord[],assignments:CourseAssignmentRecord[],programs:PlatformRecord[],maps:PlatformRecord[],programId?:string,requestedLocale?:string):CurriculumTwinSnapshot{
  const locale:ServerLocale=resolveServerLocale(requestedLocale);
  const program=programId?programs.find(x=>x.id===programId):programs[0];const map=maps.find(x=>String(x.data?.programId||'')===String(program?.id||''))||(!programId?maps[0]:undefined);return buildCurriculum(courses,assignments,program,map,[],locale);
}

export function simulateCurriculumTwin(courses:CourseRecord[],assignments:CourseAssignmentRecord[],programs:PlatformRecord[],maps:PlatformRecord[],input:{programId?:string;removeCourseIds?:string[];courseOutcomeOverrides?:Record<string,string[]>;termOverrides?:Record<string,string>;locale?:string}):CurriculumTwinSimulation{
  const locale:ServerLocale=resolveServerLocale(input.locale);
  const program=input.programId?programs.find(x=>x.id===input.programId):programs[0];const map=maps.find(x=>String(x.data?.programId||'')===String(program?.id||''))||(!input.programId?maps[0]:undefined);const baseline=buildCurriculum(courses,assignments,program,map,[],locale);const remove=new Set(input.removeCourseIds||[]);const scenarioCourses=courses.filter(c=>!remove.has(c.id)).map(c=>({...c,outcomes:input.courseOutcomeOverrides?.[c.id]||c.outcomes,term:input.termOverrides?.[c.id]||c.term}));const scenarioAssignments=assignments.filter(a=>!remove.has(a.courseId));const scenario=buildCurriculum(scenarioCourses,scenarioAssignments,program,map,baseline.outcomes.map(x=>x.outcome),locale);const scenBy=new Map(scenario.outcomes.map(x=>[normalize(x.outcome),x]));const newlyUncovered=baseline.outcomes.filter(x=>x.status!=='uncovered'&&scenBy.get(normalize(x.outcome))?.status==='uncovered').map(x=>x.outcome);const reduced=baseline.outcomes.filter(x=>{const s=scenBy.get(normalize(x.outcome));return s&&x.courseIds.length>s.courseIds.length&&!newlyUncovered.includes(x.outcome)}).map(x=>x.outcome);const lost=baseline.outcomes.reduce((n,x)=>n+x.assignmentIds.length,0)-scenario.outcomes.reduce((n,x)=>n+x.assignmentIds.length,0);const removedCourses=baseline.courses.filter(c=>remove.has(c.id)).map(c=>({id:c.id,code:c.code,title:c.title}));const riskLevel=newlyUncovered.length?'high':reduced.length||lost>0?'moderate':'low';const summary=riskLevel==='high'?txf(INT.simHigh,locale,{count:newlyUncovered.length}):riskLevel==='moderate'?txf(INT.simModerate,locale,{reduced:reduced.length,lost:Math.max(0,lost)}):tx(INT.simLow,locale);return{baseline,scenario,impact:{removedCourses,newlyUncoveredOutcomes:newlyUncovered,reducedCoverageOutcomes:reduced,assignmentEvidenceLinksLost:Math.max(0,lost),riskLevel,summary}};
}
