// AcademicOS Native Compiler — شبكة أمان حتمية عندما لا يوجد مزوّد AI مُهيّأ.
//
// الغرض: ألا ينكسر تدفّق الطالب (لصق نص → مشروع) عند غياب/انقطاع مزوّد الذكاء الاصطناعي.
// هذا المُجمِّع استدلالي (heuristic) وحتمي: لا يزعم فهمًا عميقًا كالـAI؛ ينتج ParsedAssignment
// قابلًا للعمل مع وسم كل شيء منخفض الثقة/يحتاج تأكيدًا، متسقًا مع مبدأ الصدق في المنتج.
//
// عند توفر مزوّد AI، لا يُستخدم هذا المسار إطلاقًا — الـAI هو الأساس.

import type { ParsedAssignment } from './project-engine';

function lines(text: string): string[] {
  return String(text || '').replace(/\r/g, '').split('\n').map(l => l.trim()).filter(Boolean);
}
function clip(s: string, n: number) { return s.replace(/\s+/g, ' ').trim().slice(0, n); }
function has(text: string, terms: string[]) { const l = text.toLowerCase(); return terms.some(t => l.includes(t.toLowerCase())); }


type NativeLocale = 'ar'|'en'|'tr'|'zh'|'hi'|'es'|'fr'|'ur';
function detectLanguage(text:string):NativeLocale {
  const sample=String(text||'').toLowerCase();
  if(/[\u4e00-\u9fff]/u.test(sample)) return 'zh';
  if(/[\u0900-\u097f]/u.test(sample)) return 'hi';
  if(/[\u0600-\u06ff]/u.test(sample)) {
    const urdu=(sample.match(/[ٹڈڑںھہےگکچپژ]/gu)||[]).length;
    return urdu>=2 ? 'ur' : 'ar';
  }
  const score=(words:string[])=>words.reduce((n,w)=>n+(sample.includes(w)?1:0),0);
  const scores:{code:NativeLocale;n:number}[]=[
    {code:'tr',n:score(['ödev','teslim','öğrenci','araştırma','sunum','rapor','kaynak','değerlendirme'])},
    {code:'es',n:score(['tarea','entrega','estudiante','investigación','presentación','informe','fuentes','evaluación'])},
    {code:'fr',n:score(['devoir','remise','étudiant','recherche','présentation','rapport','sources','évaluation'])},
  ];
  scores.sort((a,b)=>b.n-a.n);
  return scores[0].n>=2?scores[0].code:'en';
}
const COPY:Record<NativeLocale,Record<string,string>>={
  en:{untitled:'Untitled assignment — confirm title',course:'Course not specified',final:'Final submission',document:'Written document',presentation:'Presentation',pdf:'PDF file',code:'Code / repository',spreadsheet:'Spreadsheet',poster:'Academic poster',media:'Video / media',localSource:'Detected locally from assignment text — confirm',criterion:'Criterion',analysisSource:'Analysis source',nativeValue:'Deterministic local compiler (no AI)',deadline:'Deadline',citation:'Citation style',policy:'Unverified policy — local extraction without AI.',riskBase:'Generated by the local fallback compiler without an AI provider — review every field before relying on it.',riskDeadline:'No deadline was detected — add it manually.',riskRubric:'No weighted rubric was detected — confirm the assessment criteria.',riskDeliverables:'No explicit deliverables were detected — confirm what must be submitted.'},
  ar:{untitled:'تكليف بلا عنوان — يحتاج تأكيد',course:'المقرر غير محدد',final:'التسليم النهائي',document:'تقرير مكتوب',presentation:'عرض تقديمي',pdf:'ملف PDF',code:'كود / مستودع',spreadsheet:'جدول بيانات',poster:'ملصق علمي',media:'فيديو / وسائط',localSource:'استُخرج محليًا من نص التكليف — يحتاج تأكيد',criterion:'معيار',analysisSource:'مصدر التحليل',nativeValue:'مُجمِّع محلي حتمي (بدون AI)',deadline:'الموعد النهائي',citation:'نمط الاستشهاد',policy:'سياسة غير موثقة — استخراج محلي بلا AI.',riskBase:'تم التوليد بالمُجمِّع المحلي بلا مزوّد ذكاء اصطناعي — راجع كل الحقول قبل الاعتماد.',riskDeadline:'لم يُكتشف موعد نهائي — أضفه يدويًا.',riskRubric:'لم يُكتشف Rubric موزون — أكّد معايير التقييم.',riskDeliverables:'لم تُكتشف مخرجات صريحة — أكّد التسليمات المطلوبة.'},
  tr:{untitled:'Başlıksız ödev — başlığı doğrulayın',course:'Ders belirtilmedi',final:'Nihai teslim',document:'Yazılı belge',presentation:'Sunum',pdf:'PDF dosyası',code:'Kod / depo',spreadsheet:'Elektronik tablo',poster:'Akademik poster',media:'Video / medya',localSource:'Ödev metninden yerel olarak algılandı — doğrulayın',criterion:'Ölçüt',analysisSource:'Analiz kaynağı',nativeValue:'Deterministik yerel derleyici (AI yok)',deadline:'Teslim tarihi',citation:'Atıf stili',policy:'Doğrulanmamış politika — AI olmadan yerel çıkarım.',riskBase:'AI sağlayıcısı olmadan yerel yedek derleyici kullanıldı — güvenmeden önce tüm alanları inceleyin.',riskDeadline:'Teslim tarihi algılanmadı — elle ekleyin.',riskRubric:'Ağırlıklı rubrik algılanmadı — değerlendirme ölçütlerini doğrulayın.',riskDeliverables:'Açık teslim çıktıları algılanmadı — teslim edilecekleri doğrulayın.'},
  zh:{untitled:'未命名作业——请确认标题',course:'未指定课程',final:'最终提交',document:'书面文档',presentation:'演示文稿',pdf:'PDF 文件',code:'代码 / 仓库',spreadsheet:'电子表格',poster:'学术海报',media:'视频 / 媒体',localSource:'从作业文本本地识别——请确认',criterion:'评分标准',analysisSource:'分析来源',nativeValue:'确定性本地编译器（无 AI）',deadline:'截止日期',citation:'引用格式',policy:'政策尚未核验——本地无 AI 提取。',riskBase:'当前使用无 AI 提供方的本地备用编译器生成——依赖前请检查所有字段。',riskDeadline:'未检测到截止日期——请手动添加。',riskRubric:'未检测到带权重的评分标准——请确认评价标准。',riskDeliverables:'未检测到明确交付物——请确认需要提交的内容。'},
  hi:{untitled:'शीर्षक रहित असाइनमेंट — शीर्षक की पुष्टि करें',course:'कोर्स निर्दिष्ट नहीं',final:'अंतिम सबमिशन',document:'लिखित दस्तावेज़',presentation:'प्रस्तुति',pdf:'PDF फ़ाइल',code:'कोड / रिपॉज़िटरी',spreadsheet:'स्प्रेडशीट',poster:'अकादमिक पोस्टर',media:'वीडियो / मीडिया',localSource:'असाइनमेंट पाठ से स्थानीय रूप से पहचाना गया — पुष्टि करें',criterion:'मानदंड',analysisSource:'विश्लेषण स्रोत',nativeValue:'निर्धारित स्थानीय कंपाइलर (AI के बिना)',deadline:'डेडलाइन',citation:'साइटेशन शैली',policy:'असत्यापित नीति — AI के बिना स्थानीय निष्कर्षण।',riskBase:'AI प्रदाता के बिना स्थानीय फ़ॉलबैक कंपाइलर से बनाया गया — भरोसा करने से पहले हर फ़ील्ड जाँचें।',riskDeadline:'डेडलाइन नहीं मिली — मैन्युअली जोड़ें।',riskRubric:'वेटेड रूब्रिक नहीं मिली — मूल्यांकन मानदंड की पुष्टि करें।',riskDeliverables:'स्पष्ट डिलिवरेबल नहीं मिले — आवश्यक सबमिशन की पुष्टि करें।'},
  es:{untitled:'Tarea sin título — confirma el título',course:'Curso no especificado',final:'Entrega final',document:'Documento escrito',presentation:'Presentación',pdf:'Archivo PDF',code:'Código / repositorio',spreadsheet:'Hoja de cálculo',poster:'Póster académico',media:'Vídeo / medios',localSource:'Detectado localmente del texto de la tarea — confirmar',criterion:'Criterio',analysisSource:'Fuente del análisis',nativeValue:'Compilador local determinista (sin IA)',deadline:'Fecha límite',citation:'Estilo de citación',policy:'Política no verificada — extracción local sin IA.',riskBase:'Generado con el compilador local de respaldo sin proveedor de IA — revisa todos los campos antes de confiar en ellos.',riskDeadline:'No se detectó fecha límite — añádela manualmente.',riskRubric:'No se detectó rúbrica ponderada — confirma los criterios de evaluación.',riskDeliverables:'No se detectaron entregables explícitos — confirma qué debes entregar.'},
  fr:{untitled:'Devoir sans titre — confirmez le titre',course:'Cours non précisé',final:'Remise finale',document:'Document écrit',presentation:'Présentation',pdf:'Fichier PDF',code:'Code / dépôt',spreadsheet:'Feuille de calcul',poster:'Poster académique',media:'Vidéo / média',localSource:'Détecté localement dans le texte du devoir — à confirmer',criterion:'Critère',analysisSource:'Source de l’analyse',nativeValue:'Compilateur local déterministe (sans IA)',deadline:'Échéance',citation:'Style de citation',policy:'Politique non vérifiée — extraction locale sans IA.',riskBase:'Généré par le compilateur local de secours sans fournisseur IA — vérifiez tous les champs avant de vous y fier.',riskDeadline:'Aucune échéance détectée — ajoutez-la manuellement.',riskRubric:'Aucune grille pondérée détectée — confirmez les critères d’évaluation.',riskDeliverables:'Aucun livrable explicite détecté — confirmez ce qui doit être remis.'},
  ur:{untitled:'بغیر عنوان اسائنمنٹ — عنوان کی تصدیق کریں',course:'کورس متعین نہیں',final:'حتمی جمع',document:'تحریری دستاویز',presentation:'پریزنٹیشن',pdf:'PDF فائل',code:'کوڈ / ریپوزٹری',spreadsheet:'اسپریڈشیٹ',poster:'تعلیمی پوسٹر',media:'ویڈیو / میڈیا',localSource:'اسائنمنٹ متن سے مقامی طور پر شناخت — تصدیق کریں',criterion:'معیار',analysisSource:'تجزیہ ماخذ',nativeValue:'متعین مقامی کمپائلر (AI کے بغیر)',deadline:'ڈیڈ لائن',citation:'حوالہ انداز',policy:'غیر تصدیق شدہ پالیسی — AI کے بغیر مقامی اخذ۔',riskBase:'AI فراہم کنندہ کے بغیر مقامی فال بیک کمپائلر سے تیار — اعتماد سے پہلے ہر فیلڈ کا جائزہ لیں۔',riskDeadline:'ڈیڈ لائن نہیں ملی — دستی طور پر شامل کریں۔',riskRubric:'وزنی روبرک نہیں ملی — جانچ معیار کی تصدیق کریں۔',riskDeliverables:'واضح مخرجات نہیں ملے — مطلوبہ جمع کی تصدیق کریں۔'},
};
function c(locale:NativeLocale,key:string){return COPY[locale]?.[key]||COPY.en[key]||key;}

// أفعال المهام: عربي + إنجليزي → رمز إجراء
const ACTION_KEYWORDS: Array<{ action: string; terms: string[] }> = [
  { action: 'RESEARCH', terms: ['بحث','مصادر','مراجع','research','sources','literature','references','investigación','fuentes','recherche','sources','araştırma','kaynak','研究','来源','शोध','स्रोत','تحقیق','ذرائع'] },
  { action: 'WRITE', terms: ['اكتب','تقرير','مقال','مقالة','كتابة','write','report','essay','paper','document','escribir','informe','rédiger','rapport','yaz','rapor','撰写','报告','लिखें','रिपोर्ट','لکھیں','رپورٹ'] },
  { action: 'ANALYZE', terms: ['حلل', 'تحليل', 'ناقش', 'analyze', 'analyse', 'analysis', 'discuss', 'evaluate', 'قيّم'] },
  { action: 'CALCULATE', terms: ['احسب', 'حساب', 'معادلة', 'calculate', 'compute', 'equation', 'statistics', 'إحصاء'] },
  { action: 'CODE', terms: ['برمج', 'كود', 'برنامج', 'code', 'program', 'implement', 'algorithm', 'خوارزمية'] },
  { action: 'DESIGN', terms: ['صمم', 'تصميم', 'design', 'prototype', 'wireframe', 'mockup'] },
  { action: 'BUILD', terms: ['ابن', 'نموذج', 'منتج', 'build', 'construct', 'model', 'prototype'] },
  { action: 'TEST', terms: ['اختبر', 'اختبار', 'test', 'validate', 'verify', 'تحقق'] },
  { action: 'PRESENT', terms: ['عرض','قدّم','شرائح','present','presentation','slides','deck','presentación','diapositivas','présentation','diapositives','sunum','slayt','演示','幻灯片','प्रस्तुति','स्लाइड','پریزنٹیشن','سلائیڈ'] },
  { action: 'SURVEY', terms: ['استبيان', 'استبانة', 'survey', 'questionnaire'] },
  { action: 'LAB', terms: ['مختبر', 'معمل', 'تجربة', 'lab', 'experiment'] },
  { action: 'REFLECT', terms: ['تأمل', 'انعكاس', 'reflection', 'reflect'] },
];

const DELIVERABLE_KEYWORDS: Array<{ title: string; format: string; terms: string[] }> = [
  { title: 'تقرير مكتوب', format: 'document', terms: ['تقرير','report','مقال','essay','paper','word','docx','informe','documento','rapport','document','rapor','belge','报告','文档','रिपोर्ट','दस्तावेज़','رپورٹ','دستاویز'] },
  { title: 'عرض تقديمي', format: 'presentation', terms: ['عرض','presentation','slides','pptx','powerpoint','شرائح','presentación','diapositivas','présentation','diapositives','sunum','slayt','演示','幻灯片','प्रस्तुति','स्लाइड','پریزنٹیشن','سلائیڈ'] },
  { title: 'ملف PDF', format: 'pdf', terms: ['pdf'] },
  { title: 'كود / مستودع', format: 'code', terms: ['كود','code','repository','github','مستودع','notebook','código','repositorio','code source','dépôt','kod','depo','代码','仓库','कोड','रिपॉज़िटरी','کوڈ','ریپوزٹری'] },
  { title: 'جدول بيانات', format: 'spreadsheet', terms: ['جدول','spreadsheet','excel','xlsx','مصنف','hoja de cálculo','feuille de calcul','elektronik tablo','电子表格','स्प्रेडशीट','اسپریڈشیٹ'] },
  { title: 'ملصق علمي', format: 'poster', terms: ['ملصق','poster','póster','affiche','poster akademik','海报','पोस्टर','پوسٹر'] },
  { title: 'فيديو', format: 'media', terms: ['فيديو','video','تسجيل','vídeo','enregistrement','kayıt','视频','वीडियो','ویڈیو'] },
];

const CITATION_STYLES: Array<{ style: string; terms: string[] }> = [
  { style: 'APA', terms: ['apa'] }, { style: 'MLA', terms: ['mla'] }, { style: 'Chicago', terms: ['chicago'] },
  { style: 'Harvard', terms: ['harvard', 'هارفارد'] }, { style: 'IEEE', terms: ['ieee'] }, { style: 'Vancouver', terms: ['vancouver'] },
];

const DOMAIN_KEYWORDS: Array<{ domain: string; terms: string[] }> = [
  { domain: 'Engineering', terms: ['هندسة', 'engineering', 'mechanic', 'circuit', 'structural', 'ميكانيك', 'دائرة'] },
  { domain: 'Computer Science', terms: ['برمجة', 'حاسوب', 'computer', 'software', 'algorithm', 'data structure', 'خوارزمية'] },
  { domain: 'Medicine', terms: ['طب', 'سريري', 'medicine', 'clinical', 'patient', 'مريض', 'تشخيص', 'diagnosis'] },
  { domain: 'Law', terms: ['قانون', 'حكم', 'law', 'legal', 'statute', 'قضية', 'case law', 'دعوى'] },
  { domain: 'Business', terms: ['أعمال', 'تسويق', 'business', 'marketing', 'management', 'إدارة', 'strategy'] },
  { domain: 'Statistics', terms: ['إحصاء', 'statistics', 'regression', 'hypothesis', 'انحدار', 'عينة', 'probability'] },
  { domain: 'Literature', terms: ['أدب', 'نص أدبي', 'literature', 'poem', 'novel', 'رواية', 'قصيدة', 'نقد'] },
  { domain: 'Science', terms: ['كيمياء', 'فيزياء', 'أحياء', 'chemistry', 'physics', 'biology', 'مختبر'] },
];

// بناء تاريخ UTC مع التحقق من صحة round-trip (يرفض 45/13/2025 بدل تدويره صامتًا).
function makeUtcDate(y: number, m: number, d: number): string | undefined {
  if (!(m >= 1 && m <= 12 && d >= 1 && d <= 31)) return undefined;
  const dt = new Date(Date.UTC(y, m - 1, d));
  if (dt.getUTCFullYear() === y && dt.getUTCMonth() === m - 1 && dt.getUTCDate() === d) return dt.toISOString();
  return undefined;
}
// كشف موعد بسيط: ISO أو dd/mm/yyyy أو "خلال N يوم/أسبوع".
function detectDeadline(text: string, now = Date.now()): string | undefined {
  const iso = text.match(/\b(20\d{2})-(\d{2})-(\d{2})(?:[T ]\d{2}:\d{2})?\b/);
  if (iso) { const dt = makeUtcDate(Number(iso[1]), Number(iso[2]), Number(iso[3])); if (dt) return dt; }
  const dmy = text.match(/\b(\d{1,2})[\/\-.](\d{1,2})[\/\-.](20\d{2})\b/);
  if (dmy) { const dt = makeUtcDate(Number(dmy[3]), Number(dmy[2]), Number(dmy[1])); if (dt) return dt; }
  const rel = text.match(/(?:خلال|بعد|within|in)\s+(\d{1,3})\s*(يوم|أيام|day|days|أسبوع|weeks?|اسبوع)/i);
  if (rel) { const n = Number(rel[1]); const weeks = /أسبوع|week|اسبوع/i.test(rel[2]); return new Date(now + n * (weeks ? 7 : 1) * 86400000).toISOString(); }
  return undefined;
}

export function compileAssignmentNative(input: { text: string; timezone?: string }, now = Date.now()): ParsedAssignment {
  const text = String(input.text || '');
  const language = detectLanguage(text);
  const ls = lines(text);
  const title = clip(ls[0] || '', 160) || c(language,'untitled');

  const actions = ACTION_KEYWORDS.filter(a => has(text, a.terms)).map(a => a.action);
  const requiredActions = actions.length ? [...new Set(actions)] : ['RESEARCH', 'WRITE', 'PRESENT'];

  const deliverables = DELIVERABLE_KEYWORDS.filter(d => has(text, d.terms)).map(d => ({
    title: c(language, d.format === 'document' ? 'document' : d.format === 'presentation' ? 'presentation' : d.format === 'pdf' ? 'pdf' : d.format === 'code' ? 'code' : d.format === 'spreadsheet' ? 'spreadsheet' : d.format === 'poster' ? 'poster' : 'media'), format: d.format, requirementSource: c(language,'localSource'),
  }));

  // Rubric: كل نسبة مئوية في النص (قد توجد عدة نسب في سطر واحد)
  const rubric: Array<{ title: string; description: string; weighting: number }> = [];
  const seenWeights: string[] = [];
  for (const m of text.matchAll(/([؀-ۿA-Za-z][؀-ۿA-Za-z \-_]{1,60}?)\s*[:：،-]?\s*(\d{1,3})\s*%/g)) {
    const w = Number(m[2]);
    if (!(w > 0 && w <= 100)) continue;
    const title = clip(m[1], 120) || c(language,'criterion');
    const key = `${title}|${w}`;
    if (seenWeights.includes(key)) continue;
    seenWeights.push(key);
    rubric.push({ title, description: '', weighting: w });
    if (rubric.length >= 20) break;
  }

  const citation = CITATION_STYLES.find(c => has(text, c.terms))?.style;
  const domain = DOMAIN_KEYWORDS.find(d => has(text, d.terms))?.domain || 'General';
  const deadline = detectDeadline(text, now);
  const group = has(text, ['مجموعة', 'جماعي', 'فريق', 'group', 'team']);
  const len = text.length;
  const complexity: 'low' | 'medium' | 'high' = len > 2500 || requiredActions.length >= 5 ? 'high' : len < 400 ? 'low' : 'medium';

  const projectType = has(text, ['عرض', 'presentation', 'slides']) ? 'Presentation'
    : has(text, ['كود', 'code', 'program', 'برمج']) ? 'Software project'
    : has(text, ['بحث', 'research', 'paper']) ? 'Research paper'
    : 'Report';

  const riskFlags: string[] = [c(language,'riskBase')];
  if (!deadline) riskFlags.push(c(language,'riskDeadline'));
  if (!rubric.length) riskFlags.push(c(language,'riskRubric'));
  if (!deliverables.length) riskFlags.push(c(language,'riskDeliverables'));

  return {
    language,
    title,
    course: c(language,'course'),
    projectType,
    academicDomain: domain,
    complexity,
    collaborationMode: group ? 'group' : 'individual',
    requiredSkills: [],
    learningOutcomes: [],
    requiredActions,
    deliverables: deliverables.length ? deliverables : [{ title: c(language,'final'), format: 'Needs confirmation' }],
    requirements: [
      { label: c(language,'analysisSource'), value: c(language,'nativeValue'), category: 'other', confidence: 'needs_confirmation', source: 'native-compiler' },
      ...(deadline ? [{ label: c(language,'deadline'), value: deadline, category: 'deadline' as const, confidence: 'needs_confirmation' as const }] : []),
      ...(citation ? [{ label: c(language,'citation'), value: citation, category: 'format' as const, confidence: 'medium' as const }] : []),
    ],
    rubric,
    deadline,
    deadlineTimezone: input.timezone,
    citationStyle: citation,
    softwareRequirements: [],
    aiPolicy: { level: 0, summary: c(language,'policy'), needsConfirmation: true },
    riskFlags,
    estimatedWorkloadHours: undefined,
  };
}
