import { localizedUiError } from "../../lib/ui-error";
import React,{useEffect,useState}from'react';
import{BookOpen,ExternalLink,FileCheck2,GitBranch,LoaderCircle,Plus,Trash2}from'lucide-react';
import{api}from'../../lib/api';
import type{ProjectDNA,ProjectEvidence,WorkspaceArtifact}from'../../types';
import{Button}from'../ui/button';
import{Card,CardContent}from'../ui/card';
import{useI18n}from'../../lib/i18n';
import{runtimeEnumLabel}from'../../lib/platform-locale';

export function EvidenceStudio({project}:{project:ProjectDNA}){
 const{t,locale}=useI18n();
 const[items,setItems]=useState<ProjectEvidence[]>([]);const[artifacts,setArtifacts]=useState<WorkspaceArtifact[]>([]);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[error,setError]=useState('');
 const[type,setType]=useState<ProjectEvidence['type']>('source');const[title,setTitle]=useState('');const[detail,setDetail]=useState('');const[sourceUrl,setSourceUrl]=useState('');const[relatedId,setRelatedId]=useState('');const[artifactId,setArtifactId]=useState('');const[deliverableId,setDeliverableId]=useState('');const[rubricId,setRubricId]=useState('');
 useEffect(()=>{Promise.all([api.evidence(project.id),api.artifacts(project.id)]).then(([e,a])=>{setItems(e.evidence);setArtifacts(a.artifacts)}).catch(e=>setError(localizedUiError(e, t, "ui.actionError"))).finally(()=>setLoading(false))},[project.id]);
 async function add(){if(!title.trim()||!detail.trim())return;setSaving(true);setError('');try{const r=await api.addEvidence(project.id,{type,title:title.trim(),detail:detail.trim(),sourceUrl:sourceUrl.trim()||undefined,relatedEvidenceIds:relatedId?[relatedId]:undefined,artifactId:artifactId||undefined,deliverableId:deliverableId||undefined,rubricIds:rubricId?[rubricId]:undefined});setItems(v=>[r.evidence,...v]);setTitle('');setDetail('');setSourceUrl('');setRelatedId('');setArtifactId('');setDeliverableId('');setRubricId('')}catch(e:any){setError(localizedUiError(e, t, "ui.actionError"))}finally{setSaving(false)}}
 async function remove(id:string){const old=items;setItems(v=>v.filter(x=>x.id!==id));try{await api.deleteEvidence(project.id,id)}catch{setItems(old)}}
 return <div className="grid xl:grid-cols-[.8fr_1.2fr] gap-5 items-start">
  <Card><CardContent><div className="eyebrow">{t("ui.evidenceInbox")}</div><h2 className="section-title mt-1">{t('evid.addTitle')}</h2><p className="body-copy mt-2">{t('evid.addDesc')}</p>
   <div className="mt-5 space-y-3"><select value={type} onChange={e=>setType(e.target.value as ProjectEvidence['type'])} className="focus-ring w-full rounded-xl border hairline bg-[var(--panel)] px-3 py-3 text-sm"><option value="source">{t('evid.typeSource')}</option><option value="claim">{t('evid.typeClaim')}</option><option value="note">{t('evid.typeNote')}</option><option value="calculation">{t('evid.typeCalculation')}</option><option value="chart">{t('evid.typeChart')}</option><option value="code">{t('evid.typeCode')}</option><option value="decision">{t('evid.typeDecision')}</option><option value="other">{t('evid.typeOther')}</option></select><input value={title} onChange={e=>setTitle(e.target.value)} placeholder={t('evid.titlePlaceholder')} className="focus-ring w-full rounded-xl border hairline bg-[var(--panel)] px-3 py-3 text-sm"/><textarea value={detail} onChange={e=>setDetail(e.target.value)} placeholder={t('evid.detailPlaceholder')} className="focus-ring w-full min-h-32 rounded-xl border hairline bg-[var(--panel)] p-3 text-sm leading-7"/>{type==='source'&&<input value={sourceUrl} onChange={e=>setSourceUrl(e.target.value)} placeholder={t('evid.urlPlaceholder')} className="focus-ring w-full rounded-xl border hairline bg-[var(--panel)] px-3 py-3 text-sm ltr"/>}
    <details className="rounded-xl border hairline bg-[var(--bg)]"><summary className="focus-ring cursor-pointer list-none px-3 py-3 text-xs font-semibold flex items-center gap-2"><GitBranch size={14} className="brand-text"/>{t('evid.advancedLink')} <span className="text-[10px] muted font-normal">{t('evid.advancedLinkHint')}</span></summary><div className="px-3 pb-3 grid gap-2"><select className="field" value={relatedId} onChange={e=>setRelatedId(e.target.value)}><option value="">{t('evid.relatedNone')}</option>{items.map(x=><option key={x.id} value={x.id}>{runtimeEnumLabel(x.type,locale)} · {x.title}</option>)}</select><select className="field" value={artifactId} onChange={e=>setArtifactId(e.target.value)}><option value="">{t('evid.artifactNone')}</option>{artifacts.map(x=><option key={x.id} value={x.id}>{x.module} · {x.title}</option>)}</select><select className="field" value={deliverableId} onChange={e=>setDeliverableId(e.target.value)}><option value="">{t('evid.deliverableNone')}</option>{project.deliverables.map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select><select className="field" value={rubricId} onChange={e=>setRubricId(e.target.value)}><option value="">{t('evid.rubricNone')}</option>{project.rubric.map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select><div className="text-[10px] muted leading-5">{t('evid.explicitNote')}</div></div></details>
    <Button className="w-full" onClick={add} disabled={saving||!title.trim()||!detail.trim()}>{saving?<LoaderCircle size={16} className="animate-spin"/>:<Plus size={16}/>}{t('evid.saveBtn')}</Button>{error&&<p className="text-xs text-[var(--danger)]">{error}</p>}</div>
  </CardContent></Card>
  <Card><CardContent><div className="flex items-end justify-between gap-3"><div><div className="eyebrow">{t("ui.traceableProjectKnowledge")}</div><h2 className="section-title mt-1">{t('evid.currentTitle')}</h2></div><span className="text-xs muted">{items.length} {t('evid.itemsUnit')}</span></div>
   {loading?<div className="h-40 grid place-items-center"><LoaderCircle className="animate-spin brand-text"/></div>:items.length?<div className="mt-5 space-y-3">{items.map(item=><div key={item.id} className="rounded-2xl border hairline bg-[var(--bg)] p-4"><div className="flex items-start gap-3"><div className="h-9 w-9 rounded-xl brand-soft-bg grid place-items-center shrink-0">{item.type==='source'?<BookOpen size={16}/>:<FileCheck2 size={16}/>}</div><div className="min-w-0 flex-1"><div className="flex gap-2 items-center flex-wrap"><h3 className="text-sm font-semibold">{item.title}</h3><span className="rounded-full border hairline px-2 py-0.5 text-[9px] uppercase muted">{runtimeEnumLabel(item.type,locale)}</span><span className={`rounded-full px-2 py-0.5 text-[9px] ${item.verification==='institution_verified'?'brand-soft-bg':item.verification==='user_verified'?'soft-bg':'bg-[#f7eddd] dark:bg-[#332a1d] text-[var(--warning)]'}`}>{runtimeEnumLabel(item.verification,locale)}</span></div><p className="text-xs leading-6 muted mt-2 whitespace-pre-wrap">{item.detail}</p>{item.sourceUrl&&<a href={item.sourceUrl} target="_blank" rel="noreferrer" className="focus-ring inline-flex items-center gap-1 text-[11px] brand-text mt-2 max-w-full"><ExternalLink size={12}/><span className="truncate">{item.sourceUrl}</span></a>}<EvidenceLinks item={item} items={items} project={project} artifacts={artifacts}/></div><Button size="icon" variant="ghost" aria-label={t('evid.deleteAria')} onClick={()=>remove(item.id)}><Trash2 size={15}/></Button></div></div>)}</div>:<div className="mt-6 rounded-2xl soft-bg p-6 text-center"><BookOpen className="mx-auto brand-text"/><div className="text-sm font-semibold mt-3">{t('evid.emptyTitle')}</div><p className="body-copy mt-1">{t('evid.emptyDesc')}</p></div>}
  </CardContent></Card>
 </div>
}
function EvidenceLinks({item,items,project,artifacts}:{item:ProjectEvidence;items:ProjectEvidence[];project:ProjectDNA;artifacts:WorkspaceArtifact[]}){const{t,locale}=useI18n();const labels=[...(item.relatedEvidenceIds||[]).map(id=>`${t('evid.derivedFrom')}: ${items.find(x=>x.id===id)?.title||id}`),...(item.artifactId?[`${t('ui.workspace')}: ${artifacts.find(x=>x.id===item.artifactId)?.title||item.artifactId}`]:[]),...(item.deliverableId?[`${t('ui.deliverable')}: ${project.deliverables.find(x=>x.id===item.deliverableId)?.title||item.deliverableId}`]:[]),...(item.rubricIds||[]).map(id=>`${t('ui.rubric')}: ${project.rubric.find(x=>x.id===id)?.title||id}`)];return labels.length?<div className="mt-3 flex flex-wrap gap-1.5">{labels.map(x=><span key={x} className="rounded-full soft-bg px-2 py-1 text-[9px] muted">{x}</span>)}</div>:null}
