import React,{useEffect,useMemo,useState}from'react';
import{CheckCircle2,Clock3,Download,FileCheck2,GitBranch,Link2,LoaderCircle,Network,ShieldCheck,Sparkles,Target}from'lucide-react';
import{api}from'../../lib/api';
import type{AcademicTimeMachine,AcademicTrustGraph,EvidenceCapsule,ProjectDNA,WorkspaceArtifact}from'../../types';
import{Button}from'../ui/button';
import{Card,CardContent}from'../ui/card';
import{useI18n}from'../../lib/i18n';

type View='twin'|'journey'|'trust';
export function ProjectIntelligence({project}:{project:ProjectDNA}){
 const{t}=useI18n();
 const[view,setView]=useState<View>('twin');const[artifacts,setArtifacts]=useState<WorkspaceArtifact[]>([]);const[storedGraph,setStoredGraph]=useState<{nodes:Array<Record<string,any>>;edges:Array<Record<string,any>>}>({nodes:[],edges:[]});const[time,setTime]=useState<AcademicTimeMachine|null>(null);const[trust,setTrust]=useState<AcademicTrustGraph|null>(null);const[capsule,setCapsule]=useState<EvidenceCapsule|null>(null);const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');const[loadError,setLoadError]=useState('');
 useEffect(()=>{let active=true;setLoadError('');Promise.all([api.artifacts(project.id).catch(()=>({artifacts:[]})),api.projectGraph(project.id).catch(()=>({success:true as const,graph:{nodes:[],edges:[]}})),api.projectTimeMachine(project.id),api.projectTrustGraph(project.id),api.evidenceCapsule(project.id)]).then(([a,g,t,tr,c])=>{if(!active)return;setArtifacts(a.artifacts);setStoredGraph(g.graph);setTime(t.timeMachine);setTrust(tr.trustGraph);setCapsule(c.capsule)}).catch((e:any)=>{if(active)setLoadError(e?.message||t('pintel.loadError'))});return()=>{active=false}},[project.id]);
 const artifactNodeCount=useMemo(()=>storedGraph.nodes.filter(n=>String(n.type).toLowerCase()==='artifact').length,[storedGraph.nodes]);
 async function share(){setBusy(true);setMessage('');try{const expires=new Date(Date.now()+30*86400000).toISOString();const r=await api.createShare({kind:'project',targetId:project.id,label:`Evidence Capsule · ${project.title}`,expiresAt:expires,watermark:'AcademicOS · Evidence Capsule'});const url=new URL(String(r.url),window.location.origin).toString();await navigator.clipboard.writeText(url);setMessage(t('pintel.shareCreated'))}catch(e:any){setMessage(e.message||t('pintel.cannotCreateLink'))}finally{setBusy(false)}}
 return <div className="space-y-5">{loadError&&<div className="rounded-xl border border-red-500/20 bg-red-500/5 p-3 text-sm text-red-700 dark:text-red-300">{loadError}</div>}<Card><CardContent className="p-3"><div className="grid grid-cols-3 gap-1 rounded-2xl bg-[var(--bg)] p-1">{([['twin','Project Twin'],['journey','Time Machine'],['trust','Trust & Evidence']] as const).map(([key,label])=><button key={key} onClick={()=>setView(key)} className={`focus-ring rounded-xl px-3 py-2.5 text-xs font-semibold ${view===key?'bg-[var(--panel)] shadow-sm':'muted hover:text-[var(--ink)]'}`}>{label}</button>)}</div></CardContent></Card>
  {view==='twin'&&<TwinView project={project} artifacts={artifacts} graph={storedGraph} trust={trust} artifactNodeCount={artifactNodeCount}/>} 
  {view==='journey'&&<JourneyView time={time}/>} 
  {view==='trust'&&<TrustView project={project} trust={trust} capsule={capsule} busy={busy} message={message} onShare={share}/>} 
 </div>
}
function TwinView({project,artifacts,graph,trust,artifactNodeCount}:{project:ProjectDNA;artifacts:WorkspaceArtifact[];graph:{nodes:Array<Record<string,any>>;edges:Array<Record<string,any>>};trust:AcademicTrustGraph|null;artifactNodeCount:number}){const{t:tr}=useI18n();return <div className="space-y-5"><Card><CardContent><div className="flex items-start justify-between gap-4"><div><div className="eyebrow">Project Twin</div><h2 className="section-title mt-1">{tr('pintel.oneProject')}</h2><p className="body-copy mt-2 max-w-3xl">{tr('pintel.twinNote')}</p></div><Network size={20} className="brand-text shrink-0"/></div><div className="mt-6 grid grid-cols-3 gap-3"><Metric label="Graph nodes" value={graph.nodes.length}/><Metric label="Graph edges" value={graph.edges.length}/><Metric label="Artifact nodes" value={artifactNodeCount}/></div>
   <div className="mt-7 overflow-x-auto pb-2"><div className="min-w-[720px] grid grid-cols-[1fr_90px_1fr] gap-4 items-center"><div className="space-y-2">{project.deliverables.slice(0,6).map(d=><Node key={d.id} icon={FileCheck2} title={d.title} meta={d.format}/>)}</div><div className="flex flex-col items-center"><div className="w-full border-t hairline"/><div className="my-3 rounded-2xl brand-bg px-3 py-3 text-center text-[11px] font-semibold shadow-sm">{project.title}</div><div className="w-full border-t hairline"/></div><div className="space-y-2">{project.rubric.length?project.rubric.slice(0,6).map(r=><Node key={r.id} icon={Target} title={r.title} meta={`${r.weighting}%`}/>):project.tasks.slice(0,6).map(t=><Node key={t.id} icon={CheckCircle2} title={t.title} meta={t.status}/>)}</div></div></div>
  </CardContent></Card>
  <Card><CardContent><div className="flex items-center justify-between gap-3"><div><div className="eyebrow">Source of truth</div><h2 className="section-title mt-1">{tr('pintel.canonicalItems')}</h2></div><span className="text-[11px] muted">{trust?.canonicalSources.length||0} canonical</span></div>{artifacts.length?<div className="mt-5 space-y-2">{artifacts.map(a=><div key={a.id} className="rounded-xl border hairline p-3 grid md:grid-cols-[1fr_auto_1fr] items-center gap-3"><div className="min-w-0"><div className="text-xs font-semibold truncate">{a.title}</div><div className="text-[9px] muted mt-1">{a.module}{a.isCanonical?` · ${tr('pintel.canonicalRef')}`:''}</div></div><GitBranch size={14} className="brand-text hidden md:block"/><div className="text-[10px] muted flex flex-wrap gap-2">{a.deliverableId?<span>{tr('pintel.linkedToDeliverable')}</span>:<span>{tr('pintel.noDeliverableLink')}</span>}{(a.rubricIds||[]).length?<span>{a.rubricIds.length} Rubric link</span>:<span>{tr('pintel.noRubricLink')}</span>}</div></div>)}</div>:<p className="body-copy mt-4">{tr('pintel.twinEmpty')}</p>}</CardContent></Card></div>}
function JourneyView({time}:{time:AcademicTimeMachine|null}){const{t}=useI18n();if(!time)return <Card><CardContent className="py-14 text-center"><LoaderCircle className="animate-spin mx-auto brand-text"/><p className="body-copy mt-3">{t('pintel.buildingJourney')}</p></CardContent></Card>;return <Card><CardContent><div className="flex items-start justify-between gap-4"><div><div className="eyebrow">Academic Time Machine</div><h2 className="section-title mt-1">{t('pintel.howEvolved')}</h2><p className="body-copy mt-2">{t('pintel.journeyNote')}</p></div><Clock3 size={19} className="brand-text"/></div><div className="mt-6 grid grid-cols-4 gap-2"><Metric label="Human" value={time.summary.humanEvents}/><Metric label="AI" value={time.summary.aiEvents}/><Metric label="Evidence" value={time.summary.evidenceEvents}/><Metric label="Versions" value={time.summary.versions}/></div><div className="mt-7 relative"><div className="absolute top-2 bottom-2 start-[15px] border-s hairline"/>{time.events.length?<div className="space-y-1">{time.events.map(e=><div key={e.id} className="relative grid grid-cols-[32px_1fr] gap-3 py-3"><div className={`relative z-10 h-8 w-8 rounded-xl grid place-items-center ${e.actorType==='ai'?'brand-soft-bg':e.actorType==='human'?'bg-[var(--panel)] border hairline':'soft-bg'}`}>{e.actorType==='ai'?<Sparkles size={13}/>:e.actorType==='human'?<CheckCircle2 size={13}/>:<Network size={13}/>}</div><div className="min-w-0"><div className="flex items-center gap-2 flex-wrap"><span className="text-xs font-semibold">{e.title}</span><span className="text-[9px] muted">{new Date(e.at).toLocaleString(document.documentElement.lang || undefined)}</span>{e.version&&<span className="text-[9px] muted">v{e.version}</span>}</div><p className="text-[11px] leading-5 muted mt-1">{e.detail}</p><div className="text-[9px] muted mt-1">{e.source}</div></div></div>)}</div>:<p className="body-copy py-8">{t('pintel.notEnoughEvents')}</p>}</div></CardContent></Card>}
function TrustView({project,trust,capsule,busy,message,onShare}:{project:ProjectDNA;trust:AcademicTrustGraph|null;capsule:EvidenceCapsule|null;busy:boolean;message:string;onShare:()=>void}){const{t}=useI18n();if(!trust||!capsule)return <Card><CardContent className="py-14 text-center"><LoaderCircle className="animate-spin mx-auto brand-text"/></CardContent></Card>;const dPct=trust.coverage.deliverablesTotal?Math.round(trust.coverage.deliverablesLinked/trust.coverage.deliverablesTotal*100):0;const rPct=trust.coverage.rubricTotal?Math.round(trust.coverage.rubricLinked/trust.coverage.rubricTotal*100):0;return <div className="space-y-5"><Card><CardContent><div className="flex items-start justify-between gap-4"><div><div className="eyebrow">AcademicOS Trust Graph</div><h2 className="section-title mt-1">{t('pintel.claimToEvidence')}</h2><p className="body-copy mt-2 max-w-3xl">{t('pintel.trustNote')}</p></div><ShieldCheck size={20} className="brand-text"/></div><div className="mt-6 grid sm:grid-cols-3 gap-3"><Coverage label={t('pintel.linkedDeliverables')} value={dPct} detail={`${trust.coverage.deliverablesLinked}/${trust.coverage.deliverablesTotal}`}/><Coverage label={t('pintel.linkedRubric')} value={rPct} detail={`${trust.coverage.rubricLinked}/${trust.coverage.rubricTotal}`}/><Coverage label={t('pintel.verifiedEvidence')} value={trust.coverage.totalEvidence?Math.round(trust.coverage.verifiedEvidence/trust.coverage.totalEvidence*100):0} detail={`${trust.coverage.verifiedEvidence}/${trust.coverage.totalEvidence}`}/></div>{trust.canonicalSources.length>0&&<div className="mt-6 border-t hairline pt-5"><div className="eyebrow">Canonical sources</div><div className="mt-3 space-y-2">{trust.canonicalSources.map(s=><div key={s.artifactId} className="rounded-xl bg-[var(--bg)] border hairline p-3 flex items-start justify-between gap-4"><div><div className="text-xs font-semibold">{s.title}</div><div className="text-[10px] muted mt-1">{s.module}{s.linkedDeliverable?` · ${s.linkedDeliverable}`:''}</div></div><div className="text-[9px] muted text-end">{s.linkedRubric.length} Rubric links<br/>{new Date(s.updatedAt).toLocaleDateString(document.documentElement.lang || undefined)}</div></div>)}</div></div>}<div className="mt-5 text-[10px] leading-5 muted">{trust.note}</div></CardContent></Card>
 <Card><CardContent><div className="flex flex-col md:flex-row md:items-start justify-between gap-5"><div><div className="eyebrow">Evidence Capsule</div><h2 className="section-title mt-1">{t('pintel.verifiableEvidencePackage')}</h2><p className="body-copy mt-2 max-w-2xl">{t('pintel.capsuleNote')}</p></div><div className={`rounded-full px-3 py-1.5 text-[10px] font-semibold self-start ${capsule.integrity.signatureStatus==='signed'?'brand-soft-bg':'soft-bg muted'}`}>{capsule.integrity.signatureStatus==='signed'?'Signed integrity':'SHA-256 integrity'}</div></div><div className="mt-5 rounded-2xl bg-[var(--bg)] border hairline p-4"><div className="grid sm:grid-cols-4 gap-4"><Small label="Skills" value={capsule.skills.length}/><Small label="Evidence" value={capsule.provenance.evidenceItems}/><Small label="AI assists" value={capsule.provenance.aiAssistedRuns}/><Small label="Contributors" value={capsule.provenance.humanContributors}/></div><div className="mt-4 pt-4 border-t hairline"><div className="text-[9px] muted">SHA-256</div><code dir="ltr" className="block text-[10px] mt-1 break-all">{capsule.integrity.hash}</code></div></div><div className="mt-4 flex flex-wrap gap-2"><Button variant="outline" onClick={()=>api.exportEvidenceCapsule(project.id)}><Download size={14}/>{t('pintel.downloadCapsule')}</Button><Button onClick={onShare} disabled={busy}>{busy?<LoaderCircle size={14} className="animate-spin"/>:<Link2 size={14}/>}{t('pintel.shareLink')}</Button></div>{message&&<div className="text-[11px] muted mt-3">{message}</div>}<div className="text-[10px] leading-5 muted mt-5">{capsule.disclosure}</div></CardContent></Card></div>}
function Metric({label,value}:{label:string;value:number}){return <div className="rounded-xl bg-[var(--bg)] border hairline p-3"><div className="text-[9px] muted">{label}</div><div className="text-xl font-semibold mt-1 mono-number">{value}</div></div>}
function Small({label,value}:{label:string;value:number}){return <div><div className="text-[9px] muted">{label}</div><div className="text-lg font-semibold mt-1 mono-number">{value}</div></div>}
function Coverage({label,value,detail}:{label:string;value:number;detail:string}){return <div className="rounded-2xl bg-[var(--bg)] border hairline p-4"><div className="flex items-center justify-between text-[10px] muted"><span>{label}</span><span>{detail}</span></div><div className="text-2xl font-semibold mt-3 mono-number">{value}%</div><div className="mt-3 h-1.5 rounded-full soft-bg overflow-hidden"><div className="h-full brand-bg rounded-full" style={{width:`${Math.min(100,value)}%`}}/></div></div>}
function Node({icon:Icon,title,meta}:any){return <div className="rounded-xl border hairline bg-[var(--bg)] p-3 flex items-center gap-3"><div className="h-8 w-8 rounded-lg brand-soft-bg flex items-center justify-center shrink-0"><Icon size={14}/></div><div className="min-w-0"><div className="text-xs font-semibold truncate">{title}</div><div className="text-[10px] muted mt-0.5 truncate">{meta}</div></div></div>}
