import React,{useEffect,useState}from'react';
import{CheckCircle2,GraduationCap,LoaderCircle,Play,ShieldCheck}from'lucide-react';
import{api}from'../../lib/api';
import type{LearningEvidenceRecord,ProjectDNA,VivaMode,VivaSession}from'../../types';
import{Button}from'../ui/button';
import{Card,CardContent}from'../ui/card';
import{useI18n}from'../../lib/i18n';

export function VivaStudio({project}:{project:ProjectDNA}){
 const{t}=useI18n();
 const[mode,setMode]=useState<VivaMode>('normal');const[session,setSession]=useState<VivaSession|null>(null);const[answers,setAnswers]=useState<Record<string,string>>({});const[evidence,setEvidence]=useState<LearningEvidenceRecord[]>([]);const[busy,setBusy]=useState(false);const[error,setError]=useState('');
 useEffect(()=>{api.learningEvidence(project.id).then(r=>setEvidence(r.evidence)).catch(()=>undefined)},[project.id]);
 async function start(){setBusy(true);setError('');try{const r=await api.startViva(project.id,mode);setSession(r.session);setAnswers({})}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function save(questionId:string){if(!session)return;const answer=(answers[questionId]||'').trim();try{const r=await api.saveVivaResponse(project.id,session.id,questionId,answer);setSession(r.session)}catch(e:any){setError(e.message)}}
 async function finish(){if(!session)return;setBusy(true);try{for(const q of session.questions)if((answers[q.id]||'').trim())await save(q.id);const r=await api.completeViva(project.id,session.id);setSession(r.session);setEvidence(v=>[r.evidence,...v])}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 if(!session||session.status==='completed')return <div className="grid xl:grid-cols-[1fr_.8fr] gap-5"><Card><CardContent><div className="h-12 w-12 rounded-2xl brand-soft-bg grid place-items-center"><GraduationCap size={20}/></div><div className="eyebrow mt-5">Viva Simulator</div><h2 className="text-2xl font-semibold mt-1">{t('viva.introTitle')}</h2><p className="body-copy mt-3 max-w-2xl">{t('viva.introDesc')}</p><div className="grid sm:grid-cols-4 gap-2 mt-6">{([['easy',t('viva.modeEasy')],['normal',t('viva.modeNormal')],['strict',t('viva.modeStrict')],['external',t('viva.modeExternal')]]as [VivaMode,string][]).map(([v,l])=><button key={v} onClick={()=>setMode(v)} className={`focus-ring rounded-xl border hairline p-3 text-xs font-semibold ${mode===v?'brand-soft-bg':''}`}>{l}</button>)}</div><Button onClick={start} disabled={busy} className="mt-5">{busy?<LoaderCircle size={16} className="animate-spin"/>:<Play size={16}/>}{t('viva.startBtn')}</Button>{error&&<p className="text-xs text-[var(--danger)] mt-3">{error}</p>}</CardContent></Card><Learning evidence={evidence}/></div>;
 return <div className="grid xl:grid-cols-[1.15fr_.65fr] gap-5"><Card><CardContent><div className="flex items-center justify-between gap-4"><div><div className="eyebrow">Live Viva · {session.mode}</div><h2 className="section-title mt-1">{t('viva.liveTitle')}</h2></div><span className="text-xs muted">{session.questions.length} {t('viva.questionsUnit')}</span></div><div className="mt-6 space-y-6">{session.questions.map((q,i)=><div key={q.id} className="border-b hairline pb-6 last:border-0"><div className="flex gap-3"><span className="h-7 w-7 rounded-lg brand-soft-bg grid place-items-center text-xs font-semibold shrink-0">{i+1}</span><div className="flex-1"><label htmlFor={`q_${q.id}`} className="text-sm font-semibold leading-7">{q.prompt}</label><div className="text-[10px] muted mt-1">Focus: {q.focus}</div><textarea id={`q_${q.id}`} value={answers[q.id]??session.responses.find(r=>r.questionId===q.id)?.answer??''} onChange={e=>setAnswers(a=>({...a,[q.id]:e.target.value}))} onBlur={()=>save(q.id)} placeholder={t('viva.answerPlaceholder')} className="focus-ring mt-3 w-full min-h-28 rounded-xl border hairline bg-[var(--bg)] p-3 text-sm leading-7"/></div></div></div>)}</div><div className="flex justify-end mt-6"><Button onClick={finish} disabled={busy}>{busy?<LoaderCircle size={16} className="animate-spin"/>:<ShieldCheck size={16}/>}{t('viva.finishBtn')}</Button></div>{error&&<p className="text-xs text-[var(--danger)] mt-3">{error}</p>}</CardContent></Card><Learning evidence={evidence}/></div>
}
function Learning({evidence}:{evidence:LearningEvidenceRecord[]}){const{t}=useI18n();return <Card><CardContent><div className="flex items-center gap-2"><CheckCircle2 size={17} className="brand-text"/><h2 className="section-title">Proof of Learning</h2></div><p className="body-copy mt-2">{t('viva.learningDesc')}</p><div className="mt-5 space-y-3">{evidence.map(e=><div key={e.id} className="rounded-xl bg-[var(--bg)] border hairline p-3"><div className="text-[10px] uppercase muted">{e.source}</div><p className="text-xs leading-6 mt-1">{e.summary}</p><div className="text-[10px] muted mt-2">{new Date(e.createdAt).toLocaleString('ar-KW')}</div></div>)}{!evidence.length&&<div className="rounded-xl soft-bg p-4 text-xs muted">{t('viva.learningEmpty')}</div>}</div></CardContent></Card>}
