import test from'node:test';import assert from'node:assert/strict';
import{runSubmissionAudit}from'../src/server/audit';
import{buildFacultyAutomation,buildInstitutionCommandCenter,buildRescuePlan,normalizeRubricGrades}from'../src/server/experience-engine';
import{ocrAgreement,selectOcrCandidate}from'../src/server/ocr';

const assignment:any={id:'a1',tenantId:'t1',courseId:'c1',createdBy:'teacher',title:'المشروع النهائي',instructions:'تعليمات مفصلة '.repeat(20),deadline:'2026-12-01T20:00:00Z',deliverables:[{id:'d1',title:'التقرير',format:'PDF'}],rubric:[{id:'r1',title:'التحليل',description:'دقة التحليل',weighting:60},{id:'r2',title:'التوثيق',description:'جودة الأدلة',weighting:40}],outcomes:['O1'],aiPolicy:{level:2,summary:'Planning only',needsConfirmation:false},groupMode:'individual',status:'published',createdAt:'',updatedAt:''};
const project:any={id:'p1',tenantId:'t1',userId:'s1',title:'مشروع',course:'C1',status:'active',projectType:'report',academicDomain:'general',complexity:'medium',collaborationMode:'individual',requiredSkills:[],learningOutcomes:['O1'],requiredActions:['WRITE'],deliverables:[{id:'d1',title:'التقرير',format:'PDF',status:'ready',fileId:'file1'}],rubric:[{id:'r1',title:'التحليل',description:'',weighting:60,readiness:'covered'},{id:'r2',title:'التوثيق',description:'',weighting:40,readiness:'covered'}],deadlines:{final:'2026-12-01T20:00:00Z'},sourceRequirements:[],softwareRequirements:[],aiPolicy:{level:2,summary:'مؤكدة',needsConfirmation:false,provenance:'published_assignment',courseId:'c1',assignmentId:'a1'},riskFlags:[],tasks:[{id:'t1',title:'إنهاء التقرير',status:'in_progress',estimatedMinutes:90},{id:'t2',title:'مراجعة نهائية',status:'ready',estimatedMinutes:60}],workspaceModules:['writing'],requirements:[],originalAssignment:{attachments:[{fileName:'brief.pdf',sha256:'a'.repeat(64)}]},revision:3,progress:80,createdAt:'',updatedAt:''};
const artifacts:any[]=[{id:'w1',tenantId:'t1',projectId:'p1',module:'writing',kind:'document',title:'التقرير',content:'إفصاح استخدام الذكاء الاصطناعي',status:'ready',deliverableId:'d1',rubricIds:['r1','r2'],createdBy:'s1',updatedBy:'s1',createdAt:'',updatedAt:''}];
const evidence:any[]=[{id:'e1',tenantId:'t1',projectId:'p1',userId:'s1',type:'claim',title:'دليل',detail:'',verification:'user_verified',deliverableId:'d1',rubricIds:['r1','r2'],createdAt:'',updatedAt:''}];

test('submission shield separates blocking issues from honest manual checks',()=>{const ready=runSubmissionAudit(project,{artifacts,evidence});assert.equal(ready.blockingIssues,0);assert.ok(ready.warnings!>=1);assert.equal(ready.evidenceCoverage,100);const broken=structuredClone(project);broken.deliverables[0].status='pending';assert.ok(runSubmissionAudit(broken,{artifacts:[],evidence:[]}).blockingIssues!>=1)});
test('rescue plan never spends more than the confirmed time budget',()=>{const plan=buildRescuePlan(project,100,new Date('2026-08-20T08:00:00Z').getTime());assert.equal(plan.requiresConfirmation,true);assert.ok(plan.phases.reduce((sum,x)=>sum+x.minutes,0)<=100);assert.ok(plan.phases[0].taskIds.includes('t1'))});
test('faculty automation catches unsafe published assignments',()=>{const bad={...assignment,deadline:undefined,rubric:[],outcomes:[],aiPolicy:{...assignment.aiPolicy,needsConfirmation:true}};const brief=buildFacultyAutomation([{id:'c1',tenantId:'t1',ownerId:'teacher',code:'C1',title:'مقرر',outcomes:['O1'],aiPolicy:assignment.aiPolicy,status:'active',createdAt:'',updatedAt:''} as any],[bad]);assert.ok(brief.actions.some(x=>x.priority==='critical'));assert.equal(brief.health.rubricReady,0)});
test('rubric grading rejects missing, unknown and over-limit criteria',()=>{const good=normalizeRubricGrades(assignment,[{rubricId:'r1',awardedPoints:55},{rubricId:'r2',awardedPoints:36}]);assert.equal(good.totalScore,91);assert.equal(good.maxScore,100);assert.throws(()=>normalizeRubricGrades(assignment,[{rubricId:'r1',awardedPoints:61},{rubricId:'r2',awardedPoints:30}]),/between 0 and 60/);assert.throws(()=>normalizeRubricGrades(assignment,[{rubricId:'r1',awardedPoints:50}]),/Missing grade/)});
test('Arabic-English OCR ensemble exposes disagreement instead of hiding it',()=>{const close=ocrAgreement('تحليل المتطلبات system design','تحليل المتطلبات system design with rubric');assert.ok(close>.5);const result=selectOcrCandidate([{provider:'primary',text:'تحليل المتطلبات وتسليم التقرير النهائي مع rubric واضح',confidence:.94,languages:['ar','en'],pageCount:2,layoutPreserved:true,warnings:[]},{provider:'secondary',text:'صفحة مختلفة تماماً عن المطلوب',confidence:.88,languages:['ar'],pageCount:2,layoutPreserved:true,warnings:[]}]);assert.equal(result.extraction.mode,'ocr');assert.equal(result.extraction.needsReview,true);assert.ok(result.extraction.warnings.some(x=>x.includes('اختلف')))});
test('institution command center exposes grading backlog and external readiness gaps',()=>{const control:any={metrics:{users:10,projects:1,activeProjects:1,dueSoon:1,aiCostUsd:0,openIncidents:0,supportBacklog:0},projects:[{id:'p1',title:'P',course:'C',userId:'s',status:'active',progress:20,riskCount:1,aiPolicyLevel:2,updatedAt:''}],audit:[{id:'1',actor:'s',action:'submission.audit',target:'p1',timestamp:''},{id:'2',actor:'s',action:'submission.audit',target:'p1',timestamp:''}],system:{}};const submission:any={status:'submitted'};const command=buildInstitutionCommandCenter({control,courses:[{...assignment,id:'c1',code:'C1',outcomes:['O1']}],assignments:[assignment],submissions:[submission],serviceState:{authentication:true,database:true,storage:true,ai:true,ocr:false,malware:false,notifications:false,backup:false,billing:false}});assert.ok(command.decisions.some(x=>x.id==='decision_grading'));assert.equal(command.operations.find(x=>x.key==='ocr')?.state,'blocked');assert.ok(command.memory.length>=1)});
