import React,{useEffect,useMemo,useState}from'react';
import{AlertTriangle,ArrowLeft,BookOpenCheck,CheckCircle2,LoaderCircle,Network,RefreshCw}from'lucide-react';
import{Link}from'react-router';
import{api}from'../lib/api';
import type{CurriculumTwinSimulation,CurriculumTwinSnapshot}from'../types';
import{PageHeader}from'../components/PageHeader';
import{Button}from'../components/ui/button';
import{Card,CardContent}from'../components/ui/card';
import{useI18n}from'../lib/i18n';

export function CurriculumTwin(){
 const{t}=useI18n();
 const[twin,setTwin]=useState<CurriculumTwinSnapshot|null>(null);const[programs,setPrograms]=useState<Array<{id:string;title:string;status:string}>>([]);const[programId,setProgramId]=useState('');const[removed,setRemoved]=useState<string[]>([]);const[simulation,setSimulation]=useState<CurriculumTwinSimulation|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState('');
 const load=async(id?:string)=>{setBusy(true);setError('');try{const r=await api.curriculumTwin(id);setTwin(r.twin);setPrograms(r.programs);setProgramId(r.twin.programId||id||'');setRemoved([]);setSimulation(null)}catch(e:any){setError(e.message||t('curric.errBuild'))}finally{setBusy(false)}};
 useEffect(()=>{load()},[]);
 async function simulate(){if(!twin)return;setBusy(true);setError('');try{setSimulation((await api.simulateCurriculumTwin({programId:twin.programId,removeCourseIds:removed})).simulation)}catch(e:any){setError(e.message||t('curric.errSimulate'))}finally{setBusy(false)}}
 const maxAssignments=useMemo(()=>Math.max(1,...(twin?.workloadByTerm||[]).map(x=>x.assignments)),[twin]);
 return <div className="space-y-6"><PageHeader eyebrow="Curriculum Digital Twin" title={t('curric.pageTitle')} description={t('curric.pageDesc')} action={<Button asChild variant="outline"><Link to="/app/platform">{t('curric.opsCenter')} <ArrowLeft size={14}/></Link></Button>}/>
  {error&&<div className="rounded-xl border border-red-500/20 bg-red-500/5 p-3 text-sm text-red-700">{error}</div>}
  {!twin?<div className="h-80 panel rounded-3xl animate-pulse"/>:<>
   <Card><CardContent><div className="flex flex-col md:flex-row md:items-end justify-between gap-4"><div><div className="eyebrow">Program model</div><h2 className="section-title mt-1">{twin.programTitle||t('curric.currentLandscape')}</h2><p className="body-copy mt-2 max-w-3xl">{twin.sourceNote}</p></div>{programs.length>1&&<label className="text-[11px] muted">{t('curric.program')}<select className="field mt-1 min-w-56" value={programId} onChange={e=>load(e.target.value)}>{programs.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label>}</div>
    <div className="mt-6 grid grid-cols-2 md:grid-cols-4 gap-3"><Metric label={t('curric.courses')} value={twin.courses.length}/><Metric label="Outcomes" value={twin.outcomes.length}/><Metric label={t('curric.fullGaps')} value={twin.uncoveredOutcomes.length} alert={twin.uncoveredOutcomes.length>0}/><Metric label={t('curric.thinCoverage')} value={twin.thinOutcomes.length} alert={twin.thinOutcomes.length>0}/></div>{twin.duplicateSignals.length>0&&<details className="mt-4 rounded-2xl bg-[var(--bg)] border hairline p-4"><summary className="cursor-pointer text-xs font-semibold">{t('curric.possibleDup')} · {twin.duplicateSignals.length}</summary><div className="mt-3 space-y-2">{twin.duplicateSignals.slice(0,8).map(x=><div key={x.outcome} className="flex items-center justify-between gap-4 text-[11px]"><span>{x.outcome}</span><span className="muted">{x.courseCount} {t('curric.coursesWord')}</span></div>)}</div><p className="text-[10px] leading-5 muted mt-3">{t('curric.dupNote')}</p></details>}
   </CardContent></Card>
   <div className="grid xl:grid-cols-[1fr_360px] gap-5 items-start">
    <div className="space-y-5">
     <Card><CardContent><div className="flex items-center justify-between gap-3"><div><div className="eyebrow">Evidence coverage</div><h2 className="section-title mt-1">{t('curric.outcomesMap')}</h2></div><BookOpenCheck size={18} className="brand-text"/></div><div className="mt-5 divide-y hairline">{twin.outcomes.length?twin.outcomes.map(o=><div key={o.outcome} className="py-3 grid sm:grid-cols-[1fr_auto] gap-3"><div><div className="text-xs font-semibold">{o.outcome}</div><div className="text-[10px] muted mt-1">{o.courseIds.length} {t('curric.courseWord')} · {o.assignmentIds.length} {t('curric.assignmentLink')}</div></div><span className={`self-start rounded-full px-2.5 py-1 text-[9px] font-semibold ${o.status==='covered'?'brand-soft-bg':o.status==='thin'?'bg-[#f7eddd] text-[var(--warning)] dark:bg-[#332a1d]':'bg-[#f5e6e3] text-[var(--danger)] dark:bg-[#382522]'}`}>{o.status==='covered'?t('curric.covered'):o.status==='thin'?t('curric.thin'):t('curric.uncovered')}</span></div>):<p className="body-copy py-5">{t('curric.noOutcomes')}</p>}</div></CardContent></Card>
     <Card><CardContent><div className="eyebrow">Workload distribution</div><h2 className="section-title mt-1">{t('curric.workloadTitle')}</h2><div className="mt-5 space-y-4">{twin.workloadByTerm.map(x=><div key={x.term}><div className="flex justify-between gap-3 text-xs"><span className="font-semibold">{x.term}</span><span className="muted">{x.courses} {t('curric.courseWord')} · {x.assignments} {t('curric.assignmentWord')}</span></div><div className="mt-2 h-2 rounded-full soft-bg overflow-hidden"><div className="h-full brand-bg rounded-full" style={{width:`${Math.max(6,(x.assignments/maxAssignments)*100)}%`}}/></div></div>)}</div></CardContent></Card>
    </div>
    <Card className="xl:sticky xl:top-24"><CardContent><div className="flex items-center gap-2"><Network size={18} className="brand-text"/><div><div className="eyebrow">Scenario lab</div><h2 className="section-title mt-1">{t('curric.whatIfTitle')}</h2></div></div><p className="body-copy mt-3">{t('curric.whatIfDesc')}</p>
     <div className="mt-5 max-h-72 overflow-auto space-y-2">{twin.courses.map(c=><label key={c.id} className={`focus-ring flex items-start gap-3 rounded-xl border hairline p-3 cursor-pointer ${removed.includes(c.id)?'brand-soft-bg':''}`}><input type="checkbox" className="mt-0.5" checked={removed.includes(c.id)} onChange={()=>setRemoved(v=>v.includes(c.id)?v.filter(x=>x!==c.id):[...v,c.id])}/><span className="min-w-0"><span className="text-xs font-semibold block">{c.code} · {c.title}</span><span className="text-[10px] muted mt-1 block">{c.outcomes.length} Outcome · {c.assignmentCount} {t('curric.assignmentWord')}</span></span></label>)}</div><div className="mt-4 flex gap-2"><Button onClick={simulate} disabled={busy||!removed.length}>{busy?<LoaderCircle size={15} className="animate-spin"/>:<RefreshCw size={15}/>}{t('curric.simulateChange')}</Button>{removed.length>0&&<Button variant="ghost" onClick={()=>{setRemoved([]);setSimulation(null)}}>{t('curric.clear')}</Button>}</div>
     {simulation&&<Impact simulation={simulation}/>} 
    </CardContent></Card>
   </div>
  </>}
 </div>
}
function Metric({label,value,alert=false}:{label:string;value:number;alert?:boolean}){return <div className="rounded-2xl bg-[var(--bg)] border hairline p-4"><div className="text-[10px] muted">{label}</div><div className={`text-2xl font-semibold mt-2 mono-number ${alert&&value?'text-[var(--warning)]':''}`}>{value}</div></div>}
function Impact({simulation}:{simulation:CurriculumTwinSimulation}){const{t}=useI18n();const i=simulation.impact;const severe=i.riskLevel==='high';return <div className={`mt-5 rounded-2xl p-4 border ${severe?'border-red-500/20 bg-red-500/5':'hairline bg-[var(--bg)]'}`}><div className="flex items-start gap-3">{i.riskLevel==='low'?<CheckCircle2 size={18} className="brand-text shrink-0"/>:<AlertTriangle size={18} className={severe?'text-[var(--danger)]':'text-[var(--warning)]'}/>}<div><div className="text-xs font-semibold">{t('curric.scenarioImpact')} · {i.riskLevel==='high'?t('curric.riskHigh'):i.riskLevel==='moderate'?t('curric.riskModerate'):t('curric.riskLow')}</div><p className="text-[11px] leading-5 muted mt-1">{i.summary}</p></div></div><div className="mt-4 grid grid-cols-2 gap-2"><Small label={t('curric.uncoveredOutcomes')} value={i.newlyUncoveredOutcomes.length}/><Small label={t('curric.lostEvidenceLinks')} value={i.assignmentEvidenceLinksLost}/></div>{i.newlyUncoveredOutcomes.length>0&&<div className="mt-4 pt-3 border-t hairline"><div className="text-[10px] muted mb-2">{t('curric.newGaps')}</div>{i.newlyUncoveredOutcomes.slice(0,5).map(x=><div key={x} className="text-xs py-1">{x}</div>)}</div>}</div>}
function Small({label,value}:{label:string;value:number}){return <div className="rounded-xl soft-bg p-3"><div className="text-[9px] muted">{label}</div><div className="text-lg font-semibold mt-1 mono-number">{value}</div></div>}
