import React,{useEffect,useState}from'react';
import{BookOpenCheck,CalendarDays,Cloud,Code2,CreditCard,KeyRound,LoaderCircle,Mail,Plug,Server,ShieldCheck}from'lucide-react';
import{api}from'../lib/api';
import type{IntegrationStatusRecord}from'../types';
import{PageHeader}from'../components/PageHeader';
import{Card,CardContent}from'../components/ui/card';
import{useI18n}from'../lib/i18n';

export function Integrations(){const{t}=useI18n();const[data,setData]=useState<IntegrationStatusRecord[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');useEffect(()=>{api.integrations().then(r=>setData(r.integrations)).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);return <div className="space-y-6"><PageHeader eyebrow="Connector Framework" title={t('integ.title')} description={t('integ.description')}/>{error&&<div className="rounded-xl border border-[var(--danger)]/20 p-3 text-sm text-[var(--danger)]">{error}</div>}{loading?<div className="min-h-64 grid place-items-center"><LoaderCircle className="animate-spin brand-text"/></div>:<div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{data.map(i=><Card key={i.key}><CardContent className="h-full flex flex-col"><div className="flex items-start justify-between gap-3"><div className="h-10 w-10 rounded-xl brand-soft-bg grid place-items-center">{icon(i.category)}</div><span className={`rounded-full px-2.5 py-1 text-[9px] font-semibold ${i.configured?'brand-soft-bg':'soft-bg muted'}`}>{i.configured?'Configured':'Not configured'}</span></div><div className="eyebrow mt-5">{i.mode.replace('_',' ')}</div><h2 className="section-title mt-1">{i.name}</h2><p className="body-copy mt-2">{i.description}</p><div className="mt-auto pt-5"><div className="text-[9px] muted mb-2">Server configuration</div><div className="flex flex-wrap gap-1">{i.setupKeys.map(k=><code key={k} className="rounded-md soft-bg px-2 py-1 text-[8px]">{k}</code>)}</div></div></CardContent></Card>)}</div>}<div className="rounded-2xl border hairline p-4 flex gap-3"><ShieldCheck size={18} className="brand-text shrink-0"/><p className="text-xs leading-6 muted">{t('integ.note')}</p></div></div>}
function icon(category:IntegrationStatusRecord['category']){const M:any={productivity:Cloud,lms:BookOpenCheck,code:Code2,calendar:CalendarDays,communications:Mail,identity:KeyRound,billing:CreditCard,ai:Server,storage:Cloud};const I=M[category]||Plug;return <I size={17}/>}
