import React,{useEffect,useState}from'react';
import{Check,LoaderCircle,MailOpen,UsersRound,X}from'lucide-react';
import{api}from'../lib/api';
import type{ProjectMemberRecord}from'../types';
import{PageHeader}from'../components/PageHeader';
import{Button}from'../components/ui/button';
import{Card,CardContent}from'../components/ui/card';
import { formatDate, useI18n } from '../lib/i18n';

export function Invitations(){const{t,locale}=useI18n();const[items,setItems]=useState<ProjectMemberRecord[]>([]);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState('');const[error,setError]=useState('');function load(){setLoading(true);api.invitations().then(r=>setItems(r.invitations)).catch(e=>setError(e.message)).finally(()=>setLoading(false))}useEffect(load,[]);async function respond(i:ProjectMemberRecord,decision:'accept'|'decline'){setBusy(i.id);setError('');try{await api.respondInvitation(i.id,decision);setItems(v=>v.filter(x=>x.id!==i.id))}catch(e:any){setError(e.message)}finally{setBusy('')}}return <div className="space-y-6"><PageHeader eyebrow={t("ui.collaboration")} title={t('invite.title')} description={t('invite.description')}/>{error&&<div className="rounded-xl border border-[var(--danger)]/20 p-3 text-sm text-[var(--danger)]">{error}</div>}<Card><CardContent><div className="flex items-center justify-between"><div className="flex items-center gap-2"><MailOpen size={18} className="brand-text"/><h2 className="section-title">{t("ui.pendingInvitations")}</h2></div>{loading?<LoaderCircle size={16} className="animate-spin brand-text"/>:<span className="text-xs muted">{items.length}</span>}</div><div className="mt-5 space-y-3">{items.map(i=><div key={i.id} className="rounded-2xl border hairline p-4 flex flex-col sm:flex-row sm:items-center gap-4 justify-between"><div className="flex gap-3"><div className="h-10 w-10 rounded-xl brand-soft-bg grid place-items-center"><UsersRound size={17}/></div><div><div className="text-sm font-semibold">{t('invite.projectInvite')}</div><div className="text-[10px] muted mt-1">{t("ui.projectId")}: {i.projectId.slice(0,8)} · {formatDate(i.createdAt,locale)}</div><div className="text-[10px] muted mt-1">{t('invite.role')}: {t(roleTranslationKey(i.role))}</div></div></div><div className="flex gap-2"><Button size="sm" variant="outline" disabled={busy===i.id} onClick={()=>respond(i,'decline')}><X size={14}/>{t('invite.decline')}</Button><Button size="sm" disabled={busy===i.id} onClick={()=>respond(i,'accept')}>{busy===i.id?<LoaderCircle size={14} className="animate-spin"/>:<Check size={14}/>}{t('invite.accept')}</Button></div></div>)}{!loading&&!items.length&&<div className="py-16 text-center"><MailOpen className="mx-auto muted"/><h3 className="font-semibold mt-4">{t('invite.emptyTitle')}</h3><p className="body-copy mt-2">{t('invite.emptyBody')}</p></div>}</div></CardContent></Card></div>}
