import React,{useEffect,useState}from'react';
import{CircleStop,Clock3,RefreshCw,ServerCog}from'lucide-react';
import{api}from'../lib/api';
import type{JobRecord}from'../types';
import{PageHeader}from'../components/PageHeader';
import{Card,CardContent}from'../components/ui/card';
import{Button}from'../components/ui/button';
import{EmptyState}from'../components/EmptyState';
import{useI18n}from'../lib/i18n';
export function Jobs(){const{t}=useI18n();const[jobs,setJobs]=useState<JobRecord[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const load=()=>{setLoading(true);api.jobs().then(r=>setJobs(r.jobs)).catch(e=>setError(e.message)).finally(()=>setLoading(false))};useEffect(()=>{load();const id=setInterval(load,10000);return()=>clearInterval(id)},[]);const cancel=async(id:string)=>{await api.cancelJob(id);load()};return <div className="space-y-6"><PageHeader eyebrow="Background processing" title={t('jobs.title')} description={t('jobs.description')} action={<Button variant="outline" onClick={load}><RefreshCw size={14} className={loading?'animate-spin':''}/> {t('jobs.refresh')}</Button>}/>{error&&<div className="text-sm text-[var(--danger)]">{error}</div>}{jobs.length?<div className="grid gap-3">{jobs.map(j=><Card key={j.id}><CardContent><div className="flex flex-col md:flex-row md:items-center justify-between gap-4"><div className="min-w-0"><div className="eyebrow">{j.type} · {j.state}</div><div className="font-semibold mt-1 mono-number truncate">{j.id}</div><div className="text-[10px] muted mt-1">{t('jobs.lastUpdate').replace('{date}',new Date(j.updatedAt).toLocaleString(document.documentElement.lang || undefined))}</div></div><div className="flex items-center gap-3"><div className="w-40"><div className="flex justify-between text-[10px] muted"><span>Progress</span><span>{j.progress}%</span></div><div className="mt-1 h-2 rounded-full bg-[var(--line)] overflow-hidden"><div className="h-full brand-bg" style={{width:`${j.progress}%`}}/></div></div>{!['completed','failed','cancelled'].includes(j.state)&&<Button size="sm" variant="outline" onClick={()=>cancel(j.id)}><CircleStop size={13}/> {t('jobs.cancel')}</Button>}</div></div><div className="mt-4 grid md:grid-cols-4 gap-2">{j.stages.map(s=><div key={s.key} className="rounded-xl bg-[var(--bg)] border hairline p-3"><div className="flex items-center gap-2"><Clock3 size={13} className={s.state==='running'?'animate-pulse brand-text':'muted'}/><span className="text-[11px] font-semibold">{s.label}</span></div><div className="text-[9px] muted mt-1">{s.state}</div></div>)}</div>{j.error&&<div className="mt-3 text-xs text-[var(--danger)]">{j.error}</div>}</CardContent></Card>)}</div>:!loading&&<EmptyState icon={ServerCog} title={t('jobs.emptyTitle')} description={t('jobs.emptyDescription')}/>}</div>}
