import React,{useEffect,useMemo,useState}from'react';
import{Archive,ArrowLeft,Bell,CalendarClock,CheckCheck,CheckCircle2,Clock3,Filter,Settings2,ShieldAlert,Sparkles}from'lucide-react';
import{Link}from'react-router';
import{api}from'../lib/api';
import type{DashboardSummary,NotificationPreferences,NotificationRecord}from'../types';
import{PageHeader}from'../components/PageHeader';
import{Card,CardContent}from'../components/ui/card';
import{Button}from'../components/ui/button';
import{EmptyState}from'../components/EmptyState';
import{useI18n}from'../lib/i18n';

type Notice={id:string;priority:'critical'|'important'|'normal';title:string;detail:string;date?:string;read?:boolean;persisted?:boolean;targetPath?:string;requiresAction?:boolean};
type View='attention'|'unread'|'all';
const defaults:NotificationPreferences={inApp:true,email:true,push:false,smsCriticalOnly:false,digest:'realtime',quietHours:{enabled:true,start:'22:00',end:'07:00'},timezone:'Asia/Kuwait'};

export function Notifications(){
 const{t}=useI18n();
 const[data,setData]=useState<DashboardSummary|null>(null),[persisted,setPersisted]=useState<NotificationRecord[]>([]),[prefs,setPrefs]=useState<NotificationPreferences>(defaults),[loading,setLoading]=useState(true),[view,setView]=useState<View>('attention'),[busy,setBusy]=useState('');
 const load=async()=>{setLoading(true);try{const[d,n,p]=await Promise.all([api.dashboard(),api.notifications(),api.notificationPreferences()]);setData(d.summary);setPersisted(n.notifications);setPrefs(p.preferences)}finally{setLoading(false)}};useEffect(()=>{load()},[]);
 const notices=useMemo<Notice[]>(()=>{
  const now=Date.now();const out:Notice[]=persisted.map(n=>({id:n.id,priority:n.priority,title:n.title,detail:n.body,date:n.createdAt,read:Boolean(n.readAt),persisted:true,targetPath:n.targetPath,requiresAction:n.requiresAction}));
  if(data){for(const risk of data.risks)out.push({id:`risk-${risk.projectId}-${risk.message}`,priority:'important',title:risk.projectTitle,detail:risk.message,targetPath:`/app/project/${risk.projectId}`,requiresAction:true});for(const item of data.upcoming){const delta=new Date(item.date).getTime()-now,days=Math.ceil(delta/86400000);out.push({id:`deadline-${item.id}`,priority:days<=2?'critical':days<=7?'important':'normal',title:item.title,detail:days<=0?t('notif.dueTodayOrLate'):`${days} ${t('notif.daysRemaining')}`,date:item.date,targetPath:item.projectId?`/app/project/${item.projectId}`:undefined,requiresAction:days<=7});}}
  const rank={critical:0,important:1,normal:2};return out.sort((a,b)=>rank[a.priority]-rank[b.priority]||(b.date||'').localeCompare(a.date||''));
 },[data,persisted]);
 const visible=notices.filter(n=>view==='all'?true:view==='unread'?!n.read:n.priority!=='normal'||n.requiresAction),unread=notices.filter(n=>!n.read).length,attention=notices.filter(n=>n.priority!=='normal'||n.requiresAction).length;
 async function state(n:Notice,action:'read'|'snooze'|'archive'){if(!n.persisted)return;setBusy(`${n.id}:${action}`);try{if(action==='read')await api.readNotification(n.id);else await api.updateNotificationState(n.id,action==='archive'?{archive:true}:{snoozedUntil:new Date(Date.now()+24*3600000).toISOString()});setPersisted(v=>action==='archive'||action==='snooze'?v.filter(x=>x.id!==n.id):v.map(x=>x.id===n.id?{...x,readAt:new Date().toISOString()}:x))}finally{setBusy('')}}
 async function readAll(){setBusy('all');try{await api.readAllNotifications();setPersisted(v=>v.map(x=>({...x,readAt:x.readAt||new Date().toISOString()})))}finally{setBusy('')}}
 async function savePrefs(patch:Partial<NotificationPreferences>){const optimistic={...prefs,...patch,quietHours:{...prefs.quietHours,...(patch.quietHours||{})}};setPrefs(optimistic);try{const r=await api.updateNotificationPreferences(patch);setPrefs(r.preferences)}catch{setPrefs(prefs)}}
 return <div className="space-y-7"><PageHeader eyebrow={t('notif.eyebrow')} title={t('notif.title')} description={t('notif.description')} action={<Button variant="outline" onClick={readAll} disabled={!unread||busy==='all'}><CheckCheck size={16}/>{t('notif.readAll')}</Button>}/>
  <div className="grid sm:grid-cols-3 gap-3">{[[ShieldAlert,t('notif.needsDecision'),attention,'critical'],[Bell,t('notif.unread'),unread,'brand'],[CheckCircle2,t('notif.calmNow'),Math.max(0,notices.length-attention),'ok']].map(([I,label,value,tone]:any)=><Card key={label}><CardContent className="flex items-center gap-3"><span className={`h-11 w-11 rounded-xl grid place-items-center ${tone==='critical'?'bg-red-500/10 text-red-600':tone==='ok'?'bg-emerald-500/10 text-emerald-600':'brand-soft-bg brand-text'}`}><I size={18}/></span><div><div className="text-2xl font-semibold">{value}</div><div className="text-xs muted">{label}</div></div></CardContent></Card>)}</div>
  <div className="grid xl:grid-cols-[1fr_310px] gap-5"><section><div className="flex flex-wrap items-center gap-2 mb-3" aria-label={t('notif.filterAria')}>{([{id:'attention',label:t('notif.tabDecisions'),count:attention},{id:'unread',label:t('notif.tabUnread'),count:unread},{id:'all',label:t('notif.tabAll'),count:notices.length}] as const).map(x=><button key={x.id} onClick={()=>setView(x.id)} aria-pressed={view===x.id} className={`focus-ring min-h-11 rounded-xl px-3.5 text-xs font-semibold border hairline inline-flex items-center gap-2 ${view===x.id?'brand-soft-bg brand-text':''}`}>{x.id==='attention'?<Sparkles size={14}/>:<Filter size={14}/>} {x.label}<span className="rounded-full soft-bg px-2 py-0.5">{x.count}</span></button>)}</div>
  {loading?<div className="grid gap-3">{[1,2,3].map(x=><div key={x} className="h-28 panel rounded-2xl animate-pulse"/>)}</div>:visible.length?<div className="grid gap-3">{visible.map(n=><Card key={n.id} className={n.read?'opacity-70':''}><CardContent className="flex flex-col sm:flex-row gap-4"><span className={`h-11 w-11 rounded-xl grid place-items-center shrink-0 ${n.priority==='critical'?'bg-red-500/10 text-red-600':n.priority==='important'?'bg-amber-500/10 text-amber-700':'brand-soft-bg brand-text'}`}>{n.priority==='critical'?<ShieldAlert size={18}/>:n.date?<CalendarClock size={18}/>:<Bell size={18}/>}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="text-sm font-semibold">{n.title}</h2><span className="eyebrow">{n.priority==='critical'?t('notif.critical'):n.priority==='important'?t('notif.important'):t('notif.normal')}</span>{n.read&&<span className="text-[10px] muted">{t('notif.read')}</span>}</div><p className="body-copy mt-1">{n.detail}</p>{n.date&&<time className="text-[11px] muted mt-2 block" dateTime={n.date}>{new Date(n.date).toLocaleString('ar-KW',{dateStyle:'medium',timeStyle:'short'})}</time>}<div className="flex flex-wrap gap-2 mt-3">{n.targetPath&&<Link to={n.targetPath} className="focus-ring min-h-11 rounded-xl brand-soft-bg brand-text px-3 inline-flex items-center gap-2 text-xs font-semibold">{t('notif.openAction')}<ArrowLeft size={14}/></Link>}{n.persisted&&!n.read&&<button disabled={busy.startsWith(n.id)} onClick={()=>state(n,'read')} className="focus-ring min-h-11 rounded-xl border hairline px-3 text-xs font-semibold"><CheckCheck size={14} className="inline me-1"/>{t('notif.markRead')}</button>}{n.persisted&&<button disabled={busy.startsWith(n.id)} onClick={()=>state(n,'snooze')} className="focus-ring min-h-11 rounded-xl border hairline px-3 text-xs font-semibold"><Clock3 size={14} className="inline me-1"/>{t('notif.tomorrow')}</button>}{n.persisted&&<button disabled={busy.startsWith(n.id)} onClick={()=>state(n,'archive')} aria-label={`${t('notif.archive')} ${n.title}`} className="focus-ring min-h-11 min-w-11 rounded-xl border hairline px-3 text-xs"><Archive size={14}/></button>}</div></div></CardContent></Card>)}</div>:<EmptyState icon={CheckCircle2} title={t('notif.emptyTitle')} description={t('notif.emptyDesc')}/>}</section>
  <aside><Card><CardContent><div className="flex items-center gap-2"><Settings2 size={17} className="brand-text"/><h2 className="section-title">{t('notif.rhythmTitle')}</h2></div><p className="body-copy mt-2">{t('notif.rhythmDesc')}</p><div className="mt-5 space-y-3">{([['email',t('notif.channelEmail')],['push',t('notif.channelPush')],['smsCriticalOnly',t('notif.channelSmsCritical')]] as const).map(([key,label])=><label key={key} className="min-h-11 flex items-center justify-between gap-3 rounded-xl border hairline px-3 text-xs font-semibold"><span>{label}</span><input type="checkbox" checked={Boolean(prefs[key])} onChange={e=>savePrefs({[key]:e.target.checked})} className="h-5 w-5 accent-[var(--brand)]"/></label>)}<label className="block"><span className="text-xs font-semibold">{t('notif.digest')}</span><select className="field mt-1.5" value={prefs.digest} onChange={e=>savePrefs({digest:e.target.value as NotificationPreferences['digest']})}><option value="realtime">{t('notif.digestRealtime')}</option><option value="daily">{t('notif.digestDaily')}</option><option value="weekly">{t('notif.digestWeekly')}</option></select></label><label className="min-h-11 flex items-center justify-between gap-3 rounded-xl border hairline px-3 text-xs font-semibold"><span>{t('notif.quietHours')} {prefs.quietHours.start}–{prefs.quietHours.end}</span><input type="checkbox" checked={prefs.quietHours.enabled} onChange={e=>savePrefs({quietHours:{...prefs.quietHours,enabled:e.target.checked}})} className="h-5 w-5 accent-[var(--brand)]"/></label></div></CardContent></Card></aside></div>
 </div>;
}
