import React, { useEffect, useMemo, useState } from "react";
import { Link } from "react-router";
import { Activity, BookOpen, BrainCircuit, Check, ChevronLeft, ClipboardPlus, Copy, GraduationCap, Link2, LoaderCircle, Plus, Send, ShieldCheck, Sparkles, Target } from "lucide-react";
import { api } from "../lib/api";
import type { AIUsagePolicy, CourseRecord, FacultyAutomationBrief } from "../types";
import { Button } from "../components/ui/button";
import { Card, CardContent } from "../components/ui/card";
import { useI18n } from "../lib/i18n";

type PolicyPreset={level:1|2|4;title:string;summary:string;allowed:string[];prohibited:string[];disclosureRequired:boolean};
export function ProfessorOS(){
  const{t}=useI18n();
  const presets=useMemo<PolicyPreset[]>(()=>[
    {level:1,title:t('prof2.policy1'),summary:t('prof2.policy1Desc'),allowed:[t('prof2.allowExplain'),t('prof2.allowBrainstorm'),t('prof2.allowPlan')],prohibited:[t('prof2.blockSubmit'),t('prof2.blockFakeSources')],disclosureRequired:false},
    {level:2,title:t('prof2.policy2'),summary:t('prof2.policy2Desc'),allowed:[t('prof2.allowReview'),t('prof2.allowGaps'),t('prof2.allowLanguage')],prohibited:[t('prof2.blockFullSubmission'),t('prof2.blockFakeData')],disclosureRequired:true},
    {level:4,title:t('prof2.policy4'),summary:t('prof2.policy4Desc'),allowed:[t('prof2.allowPlan'),t('prof2.allowDraft'),t('prof2.allowReview'),t('prof2.allowViva')],prohibited:[t('prof2.blockFakeSources'),t('prof2.blockFakeClaims'),t('prof2.blockHideAI')],disclosureRequired:true},
  ],[t]);
  const copilotPrompts=useMemo(()=>[t('prof2.promptGap'),t('prof2.promptQuestions'),t('prof2.promptPublish')],[t]);
  const[courses,setCourses]=useState<CourseRecord[]>([]);const[brief,setBrief]=useState<FacultyAutomationBrief|null>(null);const[loading,setLoading]=useState(true);const[creating,setCreating]=useState(false);const[linkBusy,setLinkBusy]=useState('');const[latestLink,setLatestLink]=useState('');const[showCreate,setShowCreate]=useState(false);const[notice,setNotice]=useState('');const[copilotQuery,setCopilotQuery]=useState('');const[copilotBusy,setCopilotBusy]=useState(false);const[copilot,setCopilot]=useState<Awaited<ReturnType<typeof api.facultyCopilot>>|null>(null);const[form,setForm]=useState({code:'',title:'',term:'',policyLevel:2 as 1|2|4});
  function refresh(){setLoading(true);Promise.allSettled([api.courses(),api.facultyAutomation()]).then(([c,b])=>{setCourses(c.status==='fulfilled'?c.value.courses:[]);if(b.status==='fulfilled')setBrief(b.value.brief)}).finally(()=>setLoading(false))}useEffect(refresh,[]);
  const preset=useMemo(()=>presets.find(x=>x.level===form.policyLevel)||presets[1],[form.policyLevel,presets]);
  async function createStudentLink(courseId:string){setLinkBusy(courseId);try{const result=await api.createJoinCode(courseId,200,120);const url=`${window.location.origin}/app/settings#join=${encodeURIComponent(result.secret)}`;setLatestLink(url);await navigator.clipboard.writeText(url).catch(()=>undefined);setNotice(t('prof2.linkReady'));return url}catch(error:any){setNotice(error.message||t('prof2.linkError'));return''}finally{setLinkBusy('')}}
  async function createCourse(event:React.FormEvent){event.preventDefault();if(!form.code.trim()||!form.title.trim())return;setCreating(true);setNotice('');try{const aiPolicy:AIUsagePolicy={level:preset.level,summary:preset.summary,allowed:preset.allowed,prohibited:preset.prohibited,disclosureRequired:preset.disclosureRequired,needsConfirmation:false,provenance:'course_policy'};const result=await api.createCourse({code:form.code.trim(),title:form.title.trim(),term:form.term.trim()||undefined,outcomes:[],aiPolicy,status:'active'});setCourses(current=>[result.course,...current]);const studentLink=await createStudentLink(result.course.id);setForm({code:'',title:'',term:'',policyLevel:2});setShowCreate(false);setNotice(studentLink?t('prof2.courseReady'):t('prof2.courseReadyNoLink'));api.facultyAutomation().then(r=>setBrief(r.brief)).catch(()=>undefined)}catch(error:any){setNotice(error.message||t('prof2.courseError'))}finally{setCreating(false)}}
  async function askCopilot(query=copilotQuery){const clean=query.trim();if(!clean)return;setCopilotQuery(clean);setCopilotBusy(true);setCopilot(null);setNotice('');try{setCopilot(await api.facultyCopilot(clean))}catch(error:any){setNotice(error.message||t('prof2.copilotError'))}finally{setCopilotBusy(false)}}
  return <div className="space-y-7 max-w-7xl mx-auto">
    <section className="teacher-lite-hero panel-flat rounded-[28px] p-6 md:p-9"><div className="grid lg:grid-cols-[1fr_auto] gap-6 items-center"><div><div className="student-proof-chip"><GraduationCap size={14}/>ProfessorOS · {t('prof2.smartLite')}</div><h1 className="text-3xl md:text-5xl font-black tracking-[-.05em] mt-5">{t('prof2.heroTitle')}</h1><p className="body-copy mt-3 max-w-3xl">{t('prof2.heroDesc')}</p><div className="flex flex-wrap gap-2 mt-6"><Button onClick={()=>setShowCreate(v=>!v)}><Plus size={16}/>{showCreate?t('prof2.closeForm'):t('prof2.createCourse')}</Button>{courses[0]&&<Button asChild variant="outline"><Link to={`/app/course/${courses[0].id}?new=assignment`}><ClipboardPlus size={16}/>Assignment Drop</Link></Button>}</div></div><div className="h-24 w-24 rounded-[28px] brand-soft-bg grid place-items-center"><ShieldCheck size={38}/></div></div></section>
    {notice&&<div role="status" className="rounded-xl brand-soft-bg p-3 text-xs">{notice}</div>}
    {latestLink&&<div className="rounded-2xl border hairline p-3 flex flex-col sm:flex-row gap-2"><input className="field flex-1" dir="ltr" readOnly value={latestLink} aria-label={t('prof2.studentJoinLink')}/><Button variant="outline" onClick={()=>navigator.clipboard.writeText(latestLink).then(()=>setNotice(t('prof2.linkCopied')))}><Copy size={15}/>{t('prof2.copyLink')}</Button></div>}
    {showCreate&&<Card><CardContent><form onSubmit={createCourse} className="space-y-5"><div><div className="eyebrow">{t('prof2.quickSetup')}</div><h2 className="section-title mt-1">{t('prof2.newCourse')}</h2></div><div className="grid md:grid-cols-3 gap-3"><label><span className="text-xs font-semibold">{t('prof2.courseCode')}</span><input className="field mt-2" required maxLength={50} value={form.code} onChange={e=>setForm(c=>({...c,code:e.target.value}))} placeholder="BUS 342"/></label><label className="md:col-span-2"><span className="text-xs font-semibold">{t('prof2.courseName')}</span><input className="field mt-2" required maxLength={220} value={form.title} onChange={e=>setForm(c=>({...c,title:e.target.value}))} placeholder={t('prof2.courseExample')}/></label><label><span className="text-xs font-semibold">{t('prof2.term')}</span><input className="field mt-2" maxLength={100} value={form.term} onChange={e=>setForm(c=>({...c,term:e.target.value}))} placeholder={t('prof2.termExample')}/></label></div><fieldset><legend className="text-xs font-semibold">{t('prof2.allowedQuestion')}</legend><div className="grid md:grid-cols-3 gap-3 mt-3">{presets.map(item=><button key={item.level} type="button" onClick={()=>setForm(c=>({...c,policyLevel:item.level}))} className={`focus-ring text-start rounded-2xl border p-4 ${form.policyLevel===item.level?'brand-soft-bg border-[var(--brand)]':'hairline'}`}><span className="h-9 w-9 rounded-xl bg-[var(--panel)] grid place-items-center"><ShieldCheck size={16}/></span><strong className="block text-sm mt-3">L{item.level} · {item.title}</strong><span className="block text-[11px] leading-5 muted mt-2">{item.summary}</span></button>)}</div></fieldset><div className="rounded-2xl soft-bg p-4"><div className="flex items-center gap-2"><Sparkles size={15} className="brand-text"/><strong className="text-xs">{t('prof2.studentPolicy')}</strong></div><p className="text-xs leading-6 mt-2">{preset.summary}</p><div className="flex flex-wrap gap-2 mt-3">{preset.allowed.map(item=><span key={item} className="rounded-full bg-[var(--panel)] px-3 py-1 text-[10px] inline-flex items-center gap-1"><Check size={11}/>{item}</span>)}</div></div><div className="flex justify-end"><Button type="submit" disabled={creating||!form.code.trim()||!form.title.trim()}>{creating?<LoaderCircle size={15} className="animate-spin"/>:<Plus size={15}/>} {t('prof2.createSave')}</Button></div></form></CardContent></Card>}
    <section className="grid xl:grid-cols-[.9fr_1.1fr] gap-5"><Card className="overflow-hidden"><CardContent><div className="flex items-center gap-3"><span className="h-11 w-11 rounded-2xl brand-soft-bg grid place-items-center"><Activity size={18}/></span><div><div className="eyebrow">Class Pulse</div><h2 className="section-title mt-1">{t('prof2.attention')}</h2></div></div>{loading?<div className="py-12 grid place-items-center"><LoaderCircle className="animate-spin brand-text"/></div>:brief?<><div className="grid grid-cols-2 sm:grid-cols-4 gap-2 mt-5"><Pulse label={t('prof2.courses')} value={brief.courses}/><Pulse label={t('prof2.assignments')} value={brief.assignments}/><Pulse label={t('prof2.published')} value={brief.publishedAssignments}/><Pulse label={t('prof2.policyConfirmed')} value={brief.health.policyConfirmed}/></div><div className="mt-4 space-y-2">{brief.actions.slice(0,4).map(action=><Link key={action.id} to={action.path} className="focus-ring block rounded-xl border hairline p-3 hover:bg-[var(--panel-2)]"><div className="flex justify-between gap-3"><strong className="text-xs">{t('prof2.actionNeeded')}</strong><span className={`text-[9px] font-semibold ${action.priority==='critical'?'text-[var(--danger)]':action.priority==='important'?'text-[var(--warning)]':'brand-text'}`}>{t(action.priority==='critical'?'prof2.critical':action.priority==='important'?'prof2.important':'prof2.improve')}</span></div><p className="text-[10px] muted leading-5 mt-1">{t('prof2.openCourseAction')}</p></Link>)}{!brief.actions.length&&<div className="rounded-xl brand-soft-bg p-4 text-xs font-semibold">{t('prof2.noGaps')}</div>}</div></>:<p className="body-copy mt-4">{t('prof2.pulseEmpty')}</p>}</CardContent></Card>
      <Card className="overflow-hidden"><CardContent><div className="flex items-center gap-3"><span className="h-11 w-11 rounded-2xl brand-soft-bg grid place-items-center"><BrainCircuit size={19}/></span><div><div className="eyebrow">Teacher Copilot</div><h2 className="section-title mt-1">{t('prof2.askCourses')}</h2></div></div><p className="body-copy mt-3">{t('prof2.copilotDesc')}</p><div className="mt-4 flex gap-2"><textarea value={copilotQuery} onChange={e=>setCopilotQuery(e.target.value)} className="field min-h-24 flex-1" placeholder={t('prof2.copilotPlaceholder')}/><Button className="self-end" onClick={()=>askCopilot()} disabled={copilotBusy||!copilotQuery.trim()}>{copilotBusy?<LoaderCircle size={15} className="animate-spin"/>:<Send size={15}/>} {t('prof2.ask')}</Button></div><div className="flex flex-wrap gap-2 mt-3">{copilotPrompts.map(prompt=><button key={prompt} onClick={()=>askCopilot(prompt)} className="focus-ring rounded-full soft-bg px-3 py-1.5 text-[10px] font-semibold">{prompt}</button>)}</div>{copilot&&<div className="mt-5 rounded-2xl brand-soft-bg p-4"><div className="flex items-center gap-2 text-xs font-semibold"><Sparkles size={14}/>{t('prof2.recommendation')}</div><p className="text-sm leading-7 mt-2">{copilot.answer}</p>{copilot.suggestions.length>0&&<ul className="mt-3 space-y-1 text-xs leading-6">{copilot.suggestions.slice(0,6).map((item,index)=><li key={index}>• {item}</li>)}</ul>}{copilot.warnings[0]&&<div className="mt-3 text-[10px] text-[var(--warning)]">{copilot.warnings[0]}</div>}</div>}</CardContent></Card></section>
    <div className="grid md:grid-cols-3 gap-4"><LiteCard icon={ShieldCheck} title="AI Policy Builder" text={t('prof2.policyBuilderDesc')}/><LiteCard icon={ClipboardPlus} title="Assignment Drop" text={t('prof2.assignmentDropDesc')}/><LiteCard icon={Target} title={t('prof2.pulseNoSpy')} text={t('prof2.pulseNoSpyDesc')}/></div>
    <Card><CardContent><div className="flex items-center justify-between gap-3"><div><div className="eyebrow">{t('prof2.yourCourses')}</div><h2 className="section-title mt-1">{t('prof2.onePlace')}</h2></div><span className="text-[10px] muted">ProfessorOS</span></div>{loading?<div className="py-14 grid place-items-center"><LoaderCircle className="animate-spin brand-text"/></div>:courses.length?<div className="grid md:grid-cols-2 gap-3 mt-5">{courses.map(course=><div key={course.id} className="rounded-2xl border hairline p-4"><div className="flex items-center gap-3"><span className="h-11 w-11 rounded-2xl brand-soft-bg grid place-items-center"><BookOpen size={18}/></span><div className="min-w-0 flex-1"><strong className="block text-sm truncate">{course.code} · {course.title}</strong><span className="text-[10px] muted">L{course.aiPolicy.level} · {course.term||t('prof2.termUnknown')}</span></div><button onClick={()=>createStudentLink(course.id)} disabled={linkBusy===course.id} className="focus-ring rounded-xl soft-bg h-10 w-10 grid place-items-center disabled:opacity-50" aria-label={t('prof2.studentJoinLink')}>{linkBusy===course.id?<LoaderCircle size={15} className="animate-spin"/>:<Copy size={15}/>}</button><Button asChild size="sm" variant="ghost"><Link to={`/app/course/${course.id}`}><ChevronLeft size={16} className="directional-icon"/></Link></Button></div><div className="grid grid-cols-2 gap-2 mt-3"><Button asChild variant="outline" size="sm"><Link to={`/app/course/${course.id}?new=assignment`}><ClipboardPlus size={14}/>{t('prof2.newAssignment')}</Link></Button><Button variant="outline" size="sm" onClick={()=>createStudentLink(course.id)}><Link2 size={14}/>{t('prof2.studentLink')}</Button></div></div>)}</div>:<div className="rounded-2xl border border-dashed hairline p-10 text-center mt-5"><GraduationCap size={26} className="mx-auto brand-text"/><strong className="block mt-3">{t('prof2.firstCourse')}</strong><p className="text-xs muted mt-2">{t('prof2.firstCourseDesc')}</p><Button className="mt-4" onClick={()=>setShowCreate(true)}><Plus size={15}/>{t('prof2.createCourse')}</Button></div>}</CardContent></Card>
  </div>
}
function Pulse({label,value}:{label:string;value:string|number}){return <div className="rounded-xl bg-[var(--bg)] border hairline p-3 text-center"><div className="text-lg font-bold mono-number">{value}</div><div className="text-[9px] muted mt-1">{label}</div></div>}
function LiteCard({icon:Icon,title,text}:{icon:React.ElementType;title:string;text:string}){return <Card><CardContent><span className="h-12 w-12 rounded-2xl brand-soft-bg grid place-items-center"><Icon size={20}/></span><h2 className="text-base font-bold mt-5">{title}</h2><p className="text-xs leading-6 muted mt-2">{text}</p></CardContent></Card>}
