import React,{useEffect,useState}from'react';
import{Link,useParams}from'react-router';
import{BadgeCheck,ExternalLink,KeyRound,LoaderCircle,ShieldCheck}from'lucide-react';
import{api,ApiError}from'../lib/api';
import type{EvidenceCapsule,PublicPlatformShare}from'../types';
import{Button}from'../components/ui/button';
import{Card,CardContent}from'../components/ui/card';
import{useI18n}from'../lib/i18n';

export function PublicShare(){
 const{t}=useI18n();const{token=''}=useParams();const[share,setShare]=useState<PublicPlatformShare|null>(null);const[error,setError]=useState('');const[needsPassword,setNeedsPassword]=useState(false);const[password,setPassword]=useState('');const[busy,setBusy]=useState(false);
 useEffect(()=>{setShare(null);setError('');setNeedsPassword(false);api.publicShare(token).then(r=>setShare(r.share)).catch((e:any)=>{if(e instanceof ApiError&&e.code==='SHARE_PASSWORD_REQUIRED')setNeedsPassword(true);else setError(t('share.linkInvalid'))})},[token]);
 async function unlock(){if(!password)return;setBusy(true);setError('');try{const r=await api.accessPublicShare(token,password);setShare(r.share);setNeedsPassword(false)}catch(e:any){setError(e?.code==='SHARE_PASSWORD_INVALID'?t('share.passwordInvalid'):e?.message||t('share.unlockFailed'))}finally{setBusy(false)}}
 return <main className="min-h-screen bg-[var(--bg)] p-4 md:p-10"><div className="max-w-5xl mx-auto"><div className="flex items-center justify-between gap-4"><Link to="/" className="font-semibold">AcademicOS</Link><div className="text-[10px] muted flex items-center gap-1"><ShieldCheck size={13}/> {t('share.consentShare')}</div></div>
  {needsPassword?<PasswordCard password={password} setPassword={setPassword} unlock={unlock} busy={busy} error={error}/>:error?<Card className="mt-16"><CardContent className="py-16 text-center"><div className="font-semibold">{t('share.cannotOpen')}</div><p className="body-copy mt-2">{error}</p></CardContent></Card>:!share?<div className="mt-16 h-64 panel rounded-3xl animate-pulse"/>:<ShareContent share={share}/>}</div></main>
}
function PasswordCard({password,setPassword,unlock,busy,error}:{password:string;setPassword:(v:string)=>void;unlock:()=>void;busy:boolean;error:string}){const{t}=useI18n();return <Card className="mt-16 max-w-lg mx-auto"><CardContent className="py-10"><div className="h-12 w-12 rounded-2xl brand-soft-bg grid place-items-center"><KeyRound size={20}/></div><h1 className="text-xl font-semibold mt-4">{t('share.protectedTitle')}</h1><p className="body-copy mt-2">{t('share.protectedDesc')}</p><div className="mt-5 flex gap-2"><input type="password" autoComplete="current-password" className="field flex-1" value={password} onChange={e=>setPassword(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')unlock()}}/><Button onClick={unlock} disabled={busy||!password}>{busy?<LoaderCircle size={15} className="animate-spin"/>:null}{t('share.unlock')}</Button></div>{error&&<p className="text-xs text-[var(--danger)] mt-3">{error}</p>}</CardContent></Card>}
function ShareContent({share}:{share:PublicPlatformShare}){const capsule=isCapsule(share)?share.snapshot as unknown as EvidenceCapsule:null;const[verification,setVerification]=useState<{hashValid:boolean;signatureValid:boolean|null;signerTrusted:boolean|null;status:'signed_trusted'|'signed_untrusted'|'hash_valid'|'invalid';keyId?:string}|null>(null);useEffect(()=>{if(!capsule){setVerification(null);return}api.verifyEvidenceCapsule(capsule).then(r=>setVerification(r.verification)).catch(()=>setVerification(null))},[capsule?.integrity.hash]);return <Card className="mt-10 relative overflow-hidden"><CardContent className="p-6 md:p-10"><div className="flex items-start gap-3"><div className="h-12 w-12 rounded-2xl brand-soft-bg grid place-items-center shrink-0"><BadgeCheck size={21} className="brand-text"/></div><div className="min-w-0"><div className="eyebrow">Consent-based share · {capsule?'Evidence Capsule':share.kind}</div><h1 className="text-2xl md:text-3xl font-semibold tracking-[-0.03em] mt-1">{capsule?.project.title||share.label}</h1>{capsule&&<div className="text-xs muted mt-2">{capsule.project.course} · {capsule.project.status}</div>}</div></div>{share.watermark&&<div className="mt-5 rounded-xl border hairline bg-[var(--bg)] px-4 py-3 text-[11px] muted">Watermark: <span className="font-semibold text-[var(--ink)]">{share.watermark}</span></div>}{capsule?<CapsuleView capsule={capsule} verification={verification}/>:<GenericView snapshot={share.snapshot}/>}<ShareFooter share={share}/></CardContent></Card>}
function isCapsule(share:PublicPlatformShare){return share.kind==='project'&&share.snapshot&&String((share.snapshot as any).schemaVersion)==='1.0'&&!!(share.snapshot as any).integrity}
function CapsuleView({capsule,verification}:{capsule:EvidenceCapsule;verification:{hashValid:boolean;signatureValid:boolean|null;signerTrusted:boolean|null;status:'signed_trusted'|'signed_untrusted'|'hash_valid'|'invalid';keyId?:string}|null}){const{t}=useI18n();return <div className="mt-8 space-y-6"><div className="grid grid-cols-2 md:grid-cols-4 gap-3"><Metric label="Skills" value={capsule.skills.length}/><Metric label="Deliverables" value={capsule.deliverables.length}/><Metric label="Evidence" value={capsule.provenance.evidenceItems}/><Metric label="Human contributors" value={capsule.provenance.humanContributors}/></div>
 <section className="rounded-2xl bg-[var(--bg)] border hairline p-5"><div className="flex flex-col md:flex-row md:items-start justify-between gap-4"><div><div className="eyebrow">Integrity</div><h2 className="section-title mt-1">{t('share.integrityTitle')}</h2></div><span className={`self-start rounded-full px-3 py-1.5 text-[10px] font-semibold ${verification?.status==='invalid'?'bg-[#fde8e8] text-[#9f2b2b] dark:bg-[#3a1f1f] dark:text-[#ffb4b4]':capsule.integrity.signatureStatus==='signed'?'brand-soft-bg':'soft-bg muted'}`}>{verification?.status==='signed_trusted'?'Trusted AcademicOS signature':verification?.status==='signed_untrusted'?'Valid signature · signer untrusted':verification?.status==='hash_valid'?'SHA-256 integrity verified':verification?.status==='invalid'?'Integrity check failed':capsule.integrity.signatureStatus==='signed'?'Checking Ed25519 signature…':'Checking SHA-256…'}</span></div><code dir="ltr" className="block mt-4 text-[10px] leading-5 break-all">{capsule.integrity.hash}</code>{capsule.integrity.signature&&<div className="mt-3 text-[10px] muted break-all" dir="ltr">Signature: {capsule.integrity.signature}</div>}{capsule.integrity.keyId&&<div className="mt-2 text-[10px] muted" dir="ltr">Key ID: {capsule.integrity.keyId}</div>}<p className="text-[10px] leading-5 muted mt-4">{t('share.integrityNote')}</p></section>
 <div className="grid lg:grid-cols-2 gap-4"><section className="rounded-2xl border hairline p-5"><div className="eyebrow">Skill evidence</div><div className="mt-4 space-y-3">{capsule.skills.length?capsule.skills.map((s,i)=><div key={`${s.skill}_${i}`} className="pb-3 border-b hairline last:border-0 last:pb-0"><div className="flex justify-between gap-3"><span className="text-xs font-semibold">{s.skill}</span><span className="text-[9px] muted">{s.verificationLevel}</span></div><p className="text-[10px] leading-5 muted mt-1">{s.evidence}</p></div>):<div className="text-xs muted">{t('share.noSkillEvidence')}</div>}</div></section><section className="rounded-2xl border hairline p-5"><div className="eyebrow">Deliverables & Rubric</div><div className="mt-4 space-y-3">{capsule.deliverables.slice(0,6).map((d,i)=><div key={`${d.title}_${i}`} className="flex items-center justify-between gap-3 text-xs"><span className="font-semibold">{d.title}</span><span className="text-[9px] muted">{d.format} · {d.status}</span></div>)}</div><div className="mt-5 pt-4 border-t hairline text-[10px] muted">{capsule.rubric.length} {t('share.rubricSaved')}</div></section></div>
 {capsule.proofOfLearning.length>0&&<section className="rounded-2xl border hairline p-5"><div className="eyebrow">Proof of Learning</div><div className="mt-4 grid md:grid-cols-2 gap-3">{capsule.proofOfLearning.slice(0,8).map(x=><div key={x.id} className="rounded-xl bg-[var(--bg)] border hairline p-3"><div className="text-[10px] font-semibold">{x.source}</div><p className="text-[10px] leading-5 muted mt-1">{x.summary}</p></div>)}</div></section>}
 <div className="text-[10px] leading-5 muted">{capsule.disclosure}</div></div>}
function GenericView({snapshot}:{snapshot:Record<string,unknown>}){return <div className="mt-8 grid sm:grid-cols-2 gap-3">{Object.entries(snapshot||{}).map(([k,v])=><div key={k} className="rounded-xl bg-[var(--bg)] border hairline p-4"><div className="eyebrow">{k}</div><div className="text-sm mt-2 break-words">{typeof v==='object'?JSON.stringify(v):String(v??'—')}</div></div>)}</div>}
function Metric({label,value}:{label:string;value:number}){return <div className="rounded-2xl bg-[var(--bg)] border hairline p-4"><div className="text-[9px] muted">{label}</div><div className="text-xl font-semibold mt-2 mono-number">{value}</div></div>}
function ShareFooter({share}:{share:PublicPlatformShare}){const{t}=useI18n();return <div className="mt-8 border-t hairline pt-4 flex flex-wrap justify-between gap-3 text-[10px] muted"><span>{t('share.createdAt')} {new Date(share.createdAt).toLocaleString(document.documentElement.lang || undefined)}</span>{share.expiresAt&&<span>{t('share.expiresAt')} {new Date(share.expiresAt).toLocaleString(document.documentElement.lang || undefined)}</span>}<span>{share.viewCount??1} {t('share.views')}</span><span className="flex items-center gap-1"><ExternalLink size={11}/> {t('share.noOtherAccess')}</span></div>}
