import React,{useEffect,useState}from'react';
import{Link}from'react-router';
import{Bug,ExternalLink,Mail,ShieldCheck}from'lucide-react';
import{api}from'../lib/api';
import{Button}from'../components/ui/button';
import{Card,CardContent}from'../components/ui/card';
import{useI18n}from'../lib/i18n';

export function SecurityReport(){const{t}=useI18n();const[c,setC]=useState<{securityContactEmail:string|null;responsibleDisclosure:string|null;statusPath:string}|null>(null);useEffect(()=>{api.publicConfig().then(setC).catch(()=>setC({securityContactEmail:null,responsibleDisclosure:null,statusPath:'/status'}))},[]);return <main className="min-h-screen bg-[var(--bg)] p-4 md:p-10"><div className="max-w-3xl mx-auto"><Link to="/p/security" className="text-xs muted">{t("ui.security")}</Link><div className="mt-12 h-12 w-12 rounded-2xl tone-tile"><Bug size={20}/></div><h1 className="text-3xl md:text-4xl font-semibold mt-4">{t("ui.securityReporting")}</h1><p className="body-copy mt-3">{t('secrep.intro')}</p><Card className="mt-8"><CardContent><div className="flex items-center gap-2"><ShieldCheck size={17} className="brand-text"/><h2 className="section-title">{t('secrep.disclosureChannel')}</h2></div>{!c?<div className="h-20 soft-bg rounded-xl mt-4 animate-pulse"/>:<div className="mt-5 space-y-3">{c.securityContactEmail?<Button asChild variant="outline"><a href={`mailto:${c.securityContactEmail}?subject=${encodeURIComponent('AcademicOS security report')}`}><Mail size={15}/>{t('secrep.sendReport')}</a></Button>:<p className="body-copy">{t('secrep.noEmail')}</p>}{c.responsibleDisclosure?<Button asChild variant="ghost"><a href={c.responsibleDisclosure} target="_blank" rel="noreferrer"><ExternalLink size={15}/>{t("ui.responsibleDisclosure")}</a></Button>:<p className="text-[10px] muted">{t('secrep.noPolicy')}</p>}<Button asChild variant="ghost"><Link to={c.statusPath}>{t('secrep.serviceStatus')}</Link></Button></div>}</CardContent></Card></div></main>}
