import React,{useEffect,useState}from'react';
import{Headphones,LoaderCircle,ShieldAlert}from'lucide-react';
import{api}from'../lib/api';
import type{SupportTicket}from'../types';
import{PageHeader}from'../components/PageHeader';
import{Card,CardContent}from'../components/ui/card';
import{formatDateTime,useI18n}from'../lib/i18n';
import{runtimeEnumLabel}from'../lib/platform-locale';

export function SupportConsole(){const{t,locale}=useI18n();const[tickets,setTickets]=useState<SupportTicket[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[busy,setBusy]=useState('');
 function load(){setLoading(true);api.adminSupportTickets().then(r=>setTickets(r.tickets)).catch(e=>setError(e.message)).finally(()=>setLoading(false))}useEffect(load,[]);
 async function update(tk:SupportTicket,status:SupportTicket['status']){setBusy(tk.id);setError('');try{const r=await api.updateSupportTicket(tk.id,{status});setTickets(v=>v.map(x=>x.id===tk.id?r.ticket:x))}catch(e:any){setError(e.message)}finally{setBusy('')}}
 return <div className="space-y-6"><PageHeader eyebrow={t("ui.supportConsole")} title={t('supcon.title')} description={t('supcon.description')}/>{error&&<div className="rounded-xl border border-[var(--danger)]/20 p-3 text-sm text-[var(--danger)]">{error}</div>}<Card><CardContent><div className="flex items-center justify-between"><div className="flex items-center gap-2"><Headphones size={18} className="brand-text"/><h2 className="section-title">{t('supcon.tickets')}</h2></div>{loading?<LoaderCircle size={17} className="animate-spin brand-text"/>:<span className="text-xs muted">{tickets.filter(tk=>!['resolved','closed'].includes(tk.status)).length} {t('supcon.openLabel')}</span>}</div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[850px] text-xs"><thead><tr className="border-b hairline muted"><th className="text-start py-3">{t('supcon.colTicket')}</th><th className="text-start">{t('supcon.colUser')}</th><th className="text-start">{t('supcon.colCategory')}</th><th className="text-start">{t('supcon.colPriority')}</th><th className="text-start">{t('supcon.colStatus')}</th><th className="text-start">{t('supcon.colUpdated')}</th></tr></thead><tbody>{tickets.map(tk=><tr key={tk.id} className="border-b hairline align-top"><td className="py-4 pe-5 max-w-md"><div className="font-semibold">{tk.subject}</div><p className="muted leading-5 mt-1 line-clamp-2">{tk.message}</p><div className="text-[9px] muted mt-2 mono-number">{tk.id}</div></td><td className="py-4 pe-4"><div>{tk.displayName}</div><div className="text-[9px] muted mt-1">{tk.email||'—'}</div></td><td className="py-4">{runtimeEnumLabel(tk.category,locale)}</td><td className="py-4"><span className={tk.priority==='critical'?'text-[var(--danger)]':tk.priority==='important'?'text-[var(--warning)]':''}>{runtimeEnumLabel(tk.priority,locale)}</span></td><td className="py-4"><select disabled={busy===tk.id} value={tk.status} onChange={e=>update(tk,e.target.value as SupportTicket['status'])} className="field w-auto text-[10px]"><option value="open">{t("support.statusOpen")}</option><option value="in_progress">{t("support.statusInProgress")}</option><option value="resolved">{t("support.statusResolved")}</option><option value="closed">{t("support.statusClosed")}</option></select></td><td className="py-4 muted">{formatDateTime(tk.updatedAt,locale)}</td></tr>)}</tbody></table>{!loading&&!tickets.length&&<div className="py-16 text-center"><ShieldAlert className="mx-auto muted"/><p className="body-copy mt-3">{t('supcon.empty')}</p></div>}</div></CardContent></Card></div>}
