import React, { useMemo, useRef, useState } from "react";
import { useNavigate, useSearchParams } from "react-router";
import { ArrowRight, BookOpenCheck, Check, FileHeart, FilePenLine, FileText, Languages, LoaderCircle, Mic2, Paperclip, ShieldCheck, Sparkles, UploadCloud, X } from "lucide-react";
import { api } from "../lib/api";
import type { AcademicAssistanceMode, AcademicWorkMode } from "../types";
import { Button } from "../components/ui/button";
import { Card, CardContent } from "../components/ui/card";
import { LOCALES, useI18n } from "../lib/i18n";

const MAX = 20 * 1024 * 1024;
export function UploadAssignment() {
  const navigate = useNavigate(); const { t, meta } = useI18n(); const [params,setParams]=useSearchParams();
  const initialMode=params.get("mode")==="rescue"?"rescue":"write"; const [mode,setMode]=useState<AcademicWorkMode>(initialMode);
  const [assignmentText,setAssignmentText]=useState(""); const [draftText,setDraftText]=useState(""); const [assignmentFiles,setAssignmentFiles]=useState<File[]>([]); const [draftFiles,setDraftFiles]=useState<File[]>([]);
  const [language,setLanguage]=useState(meta.aiName); const [pages,setPages]=useState(12); const [topicNotes,setTopicNotes]=useState(""); const [assistanceMode,setAssistanceMode]=useState<AcademicAssistanceMode>("practice"); const [processing,setProcessing]=useState(false); const [error,setError]=useState("");
  const assignmentInput=useRef<HTMLInputElement>(null); const draftInput=useRef<HTMLInputElement>(null);
  const canStart=useMemo(()=>mode==="rescue"?Boolean(draftText.trim()||draftFiles.length):Boolean(assignmentText.trim()||assignmentFiles.length),[mode,assignmentText,assignmentFiles.length,draftText,draftFiles.length]);
  async function filePayload(file:File){if(file.size>MAX)throw new Error(`${file.name}: ${t("upload2.tooLarge")}`);const base64=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(reader.error);reader.onload=()=>resolve(String(reader.result).split(",")[1]||"");reader.readAsDataURL(file)});return{name:file.name,mimeType:file.type||"application/octet-stream",base64,size:file.size}}
  async function start(){if(!canStart)return;setProcessing(true);setError("");try{const labels=[assignmentText.trim()?`--- ASSIGNMENT ---\n${assignmentText.trim()}`:"",mode==="rescue"&&draftText.trim()?`--- EXISTING DRAFT ---\n${draftText.trim()}`:"",topicNotes.trim()?`--- STUDENT DECISIONS ---\n${topicNotes.trim()}`:""] .filter(Boolean).join("\n\n");const files=[...assignmentFiles,...draftFiles];const result=await api.createProject({textContext:labels||undefined,files:files.length?await Promise.all(files.map(filePayload)):undefined,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone});navigate(`/app/project/${result.project.id}?focus=writer`,{replace:true,state:{justCompiled:true,writerMode:mode,writerRequest:{mode,assistanceMode,language,desiredPages:pages,academicTone:"clear",topicNotes,existingDraft:mode==="rescue"?draftText:undefined}}})}catch(caught:any){setError(caught?.message||t("upload2.error"))}finally{setProcessing(false)}}
  function chooseMode(value:AcademicWorkMode){setMode(value);setParams({mode:value})}
  return <div className="mx-auto max-w-6xl space-y-6">
    <header className="text-center max-w-3xl mx-auto"><div className="inline-flex items-center gap-2 rounded-full brand-soft-bg px-3 py-1.5 text-[11px] font-semibold"><Sparkles size={14}/>{t("upload2.fast")}</div><h1 className="text-3xl md:text-5xl font-semibold tracking-[-.05em] mt-4">{t(mode==="rescue"?"upload2.rescueTitle":"upload2.writeTitle")}</h1><p className="body-copy mt-3">{t("upload2.desc")}</p></header>
    <div className="grid sm:grid-cols-2 gap-3 max-w-2xl mx-auto" role="tablist" aria-label={t("upload2.taskType")}><ModeButton selected={mode==="write"} icon={FilePenLine} title={t("upload2.writeMode")} detail={t("upload2.writeModeDesc")} onClick={()=>chooseMode("write")}/><ModeButton selected={mode==="rescue"} icon={FileHeart} title={t("upload2.rescueMode")} detail={t("upload2.rescueModeDesc")} onClick={()=>chooseMode("rescue")}/></div>
    <div className="grid xl:grid-cols-[1fr_360px] gap-5 items-start"><Card className="overflow-hidden"><CardContent className="p-0">
      <UploadBlock title={t(mode==="rescue"?"upload2.assignmentOptional":"upload2.assignment")} detail={t("upload2.fileTypes")} files={assignmentFiles} onPick={()=>assignmentInput.current?.click()} onDrop={(files)=>setAssignmentFiles(files.slice(0,5))} onRemove={(index)=>setAssignmentFiles(old=>old.filter((_,i)=>i!==index))} action={t("upload2.pickFiles")} remove={t("upload2.remove")}/><input ref={assignmentInput} type="file" multiple className="hidden" accept=".pdf,.docx,.pptx,.txt,.md,image/*" onChange={(e)=>setAssignmentFiles(Array.from(e.target.files||[]).slice(0,5))}/>
      <div className="p-5 border-b hairline"><label className="block"><span className="text-xs font-semibold">{t("upload2.pasteAssignment")}</span><textarea value={assignmentText} onChange={(e)=>setAssignmentText(e.target.value)} rows={5} className="field mt-2 resize-y" placeholder={t("upload2.assignmentPlaceholder")}/></label></div>
      {mode==="rescue"&&<><UploadBlock title={t("upload2.draftUpload")} detail={t("upload2.draftDetail")} files={draftFiles} onPick={()=>draftInput.current?.click()} onDrop={(files)=>setDraftFiles(files.slice(0,5))} onRemove={(index)=>setDraftFiles(old=>old.filter((_,i)=>i!==index))} action={t("upload2.pickFiles")} remove={t("upload2.remove")}/><input ref={draftInput} type="file" multiple className="hidden" accept=".pdf,.docx,.txt,.md" onChange={(e)=>setDraftFiles(Array.from(e.target.files||[]).slice(0,5))}/><div className="p-5 border-b hairline"><label className="block"><span className="text-xs font-semibold">{t("upload2.pasteDraft")}</span><textarea value={draftText} onChange={(e)=>setDraftText(e.target.value)} rows={8} className="field mt-2 resize-y" placeholder={t("upload2.draftPlaceholder")}/></label></div></>}
      <div className="p-5"><label className="block"><span className="text-xs font-semibold">{t("upload2.consider")}</span><textarea value={topicNotes} onChange={(e)=>setTopicNotes(e.target.value)} rows={3} className="field mt-2 resize-y" placeholder={t("upload2.considerPlaceholder")}/></label></div>
    </CardContent></Card>
    <aside className="space-y-4 xl:sticky xl:top-24"><Card><CardContent><div className="flex items-center gap-2"><Languages size={17} className="brand-text"/><h2 className="section-title">{t("upload2.projectShape")}</h2></div><label className="block mt-5"><span className="text-[11px] font-semibold">{t("upload2.writingLanguage")}</span><input list="project-languages" value={language} onChange={(e)=>setLanguage(e.target.value)} className="field mt-1.5" placeholder={t("upload2.anyLanguage")}/><datalist id="project-languages">{LOCALES.map(item=><option key={item.code} value={item.aiName}/>)}<option value="Deutsch"/><option value="Português"/><option value="日本語"/><option value="한국어"/><option value="فارسی"/></datalist><span className="text-[9px] muted mt-1 block">{t("upload2.anyLanguageNote")}</span></label><label className="block mt-4"><span className="text-[11px] font-semibold flex justify-between"><span>{t("upload2.pages")}</span><strong className="brand-text">{pages}</strong></span><input type="range" min="3" max="35" value={pages} onChange={(e)=>setPages(Number(e.target.value))} className="w-full mt-3 accent-[var(--brand)]"/></label><div className="mt-5 pt-4 border-t hairline"><div className="text-[11px] font-semibold mb-2">{t("upload2.assistance")}</div><AssistChoice selected={assistanceMode==="practice"} title={t("upload2.practice")} detail={t("upload2.practiceDesc")} onClick={()=>setAssistanceMode("practice")}/><AssistChoice selected={assistanceMode==="policy_strict"} title={t("upload2.strict")} detail={t("upload2.strictDesc")} onClick={()=>setAssistanceMode("policy_strict")}/></div></CardContent></Card>
      <Card className="brand-soft-bg"><CardContent><div className="flex items-center gap-2"><ShieldCheck size={17}/><h3 className="text-sm font-semibold">{t("upload2.promise")}</h3></div><div className="grid grid-cols-3 gap-2 mt-4 text-center"><SmallPromise icon={BookOpenCheck} label={t("upload2.project")}/><SmallPromise icon={FileText} label={t("upload2.explain")}/><SmallPromise icon={Mic2} label={t("upload2.viva")}/></div></CardContent></Card>
      {error&&<div role="alert" className="rounded-xl bg-red-500/10 text-[var(--danger)] p-3 text-xs leading-6">{error}</div>}<Button size="lg" className="w-full" onClick={start} disabled={!canStart||processing}>{processing?<><LoaderCircle size={18} className="animate-spin"/>{t("upload2.processing")}</>:<>{t(mode==="rescue"?"upload2.startRescue":"upload2.build")}<ArrowRight size={17} className="directional-icon"/></>}</Button><p className="text-[10px] leading-5 muted text-center">{t("upload2.truth")}</p>
    </aside></div>
  </div>
}
function ModeButton({selected,icon:Icon,title,detail,onClick}:{selected:boolean;icon:React.ElementType;title:string;detail:string;onClick:()=>void}){return <button type="button" role="tab" aria-selected={selected} onClick={onClick} className={`mode-choice focus-ring rounded-2xl border p-4 flex items-center gap-3 text-start ${selected?"is-selected":"hairline"}`}><span className="h-12 w-12 rounded-2xl brand-soft-bg grid place-items-center"><Icon size={20}/></span><span className="flex-1"><strong className="block text-sm">{title}</strong><span className="text-[11px] muted mt-1 block">{detail}</span></span>{selected&&<Check size={17} className="brand-text"/>}</button>}
function UploadBlock({title,detail,files,onPick,onDrop,onRemove,action,remove}:{title:string;detail:string;files:File[];onPick:()=>void;onDrop:(files:File[])=>void;onRemove:(index:number)=>void;action:string;remove:string}){return <div className="border-b hairline"><button type="button" onClick={onPick} onDragOver={(e)=>e.preventDefault()} onDrop={(e)=>{e.preventDefault();onDrop(Array.from(e.dataTransfer.files))}} className="upload-visual focus-ring w-full min-h-44 p-6 grid place-items-center text-center"><span><span className="h-14 w-14 rounded-2xl bg-white/75 grid place-items-center mx-auto shadow-sm"><UploadCloud size={23}/></span><strong className="block mt-4 text-sm">{title}</strong><span className="block text-[11px] muted mt-1">{detail}</span><span className="inline-flex items-center gap-1.5 mt-3 text-[10px] font-semibold brand-text"><Paperclip size={13}/>{action}</span></span></button>{files.length>0&&<div className="px-4 pb-4 flex flex-wrap gap-2">{files.map((file,index)=><span key={`${file.name}-${index}`} className="inline-flex items-center gap-2 rounded-full border hairline bg-[var(--panel)] px-3 py-1.5 text-[10px]"><FileText size={13}/><span className="max-w-44 truncate">{file.name}</span><button type="button" onClick={()=>onRemove(index)} aria-label={`${remove} ${file.name}`}><X size={12}/></button></span>)}</div>}</div>}
function AssistChoice({selected,title,detail,onClick}:{selected:boolean;title:string;detail:string;onClick:()=>void}){return <button type="button" onClick={onClick} className={`focus-ring w-full text-start rounded-xl border p-3 mb-2 ${selected?"brand-soft-bg border-[var(--brand)]/40":"hairline"}`}><div className="flex items-start gap-2"><span className={`h-4 w-4 mt-0.5 rounded-full border grid place-items-center ${selected?"border-[var(--brand)]":"hairline"}`}>{selected&&<span className="h-2 w-2 rounded-full brand-bg"/>}</span><span><strong className="block text-[11px]">{title}</strong><span className="block text-[9px] muted leading-4 mt-1">{detail}</span></span></div></button>}
function SmallPromise({icon:Icon,label}:{icon:React.ElementType;label:string}){return <div><span className="h-9 w-9 rounded-xl bg-white/60 grid place-items-center mx-auto"><Icon size={15}/></span><span className="text-[9px] font-semibold mt-1.5 block">{label}</span></div>}
