import React,{useEffect,useMemo,useState}from'react';
import{Ban,CheckCircle2,LoaderCircle,Search,ShieldCheck,UserRoundCog,X}from'lucide-react';
import{api}from'../lib/api';
import type{AdminUserRecord,UserRole}from'../types';
import{useAuth}from'../contexts/AuthContext';
import{PageHeader}from'../components/PageHeader';
import{Card,CardContent}from'../components/ui/card';
import{Button}from'../components/ui/button';
import{useI18n}from'../lib/i18n';

const academic:UserRole[]=['student','student_group_leader','teaching_assistant','professor','course_coordinator','department_admin','college_admin','ai_governance_officer','accreditation_officer','employer'];
function allowed(role?:UserRole):UserRole[]{if(role==='university_admin')return academic;if(role==='admin')return[...academic,'university_admin','support_agent','finance_admin','trust_safety_admin'];if(role==='superadmin'||role==='root_owner')return[...academic,'university_admin','national_admin','support_agent','finance_admin','trust_safety_admin','admin','superadmin'];return[]}
type Pending={user:AdminUserRecord;patch:{role?:UserRole;disabled?:boolean};label:string};
export function UserManagement(){
 const{t}=useI18n();
 const{user}=useAuth();const[items,setItems]=useState<AdminUserRecord[]>([]);const[loading,setLoading]=useState(true);const[query,setQuery]=useState('');const[error,setError]=useState('');const[pending,setPending]=useState<Pending|null>(null);const[reason,setReason]=useState('');const[saving,setSaving]=useState(false);const[nextPage,setNextPage]=useState<string|null>(null);const roles=allowed(user?.role);
 function load(pageToken?:string){setLoading(true);api.adminUsers(pageToken).then(r=>{setItems(v=>pageToken?[...v,...r.users.filter(x=>!v.some(y=>y.id===x.id))]:r.users);setNextPage(r.nextPageToken)}).catch(e=>setError(e.message)).finally(()=>setLoading(false))}useEffect(()=>load(),[]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return q?items.filter(x=>[x.displayName,x.email,x.role,x.id].filter(Boolean).join(' ').toLowerCase().includes(q)):items},[items,query]);
 async function apply(){if(!pending||!reason.trim())return;setSaving(true);setError('');try{const r=await api.updateAdminUser(pending.user.id,{...pending.patch,reason:reason.trim()});setItems(v=>v.map(x=>x.id===r.user.id?r.user:x));setPending(null);setReason('')}catch(e:any){setError(e.message)}finally{setSaving(false)}}
 return <div className="space-y-6"><PageHeader eyebrow="RBAC · Tenant scoped" title={t('users.pageTitle')} description={t('users.pageDesc')}/>
  {error&&<div className="rounded-xl border border-[var(--danger)]/20 p-3 text-sm text-[var(--danger)]">{error}</div>}
  <Card><CardContent><div className="flex flex-col md:flex-row md:items-center gap-3 justify-between"><div><div className="eyebrow">Directory</div><h2 className="section-title mt-1">{t('users.tenantUsers')}</h2></div><label className="relative w-full md:w-80"><Search size={15} className="absolute start-3 top-1/2 -translate-y-1/2 muted"/><input className="field ps-9" value={query} onChange={e=>setQuery(e.target.value)} placeholder={t('users.searchPh')}/></label></div>
  {loading&&!items.length?<div className="min-h-56 grid place-items-center"><LoaderCircle className="animate-spin brand-text"/></div>:<div className="mt-5 overflow-x-auto"><table className="w-full min-w-[860px] text-sm"><thead><tr className="border-b hairline text-[10px] muted"><th className="py-3 text-start font-medium">{t('users.colUser')}</th><th className="text-start font-medium">{t('users.colStatus')}</th><th className="text-start font-medium">{t('users.colRole')}</th><th className="text-start font-medium">{t('users.colLastLogin')}</th><th className="text-end font-medium">{t('users.colAction')}</th></tr></thead><tbody>{filtered.map(x=>{const protectedTarget=x.role==='root_owner'||(x.role==='superadmin'&&user?.role!=='root_owner')||x.id===user?.id;return <tr key={x.id} className="border-b hairline last:border-0"><td className="py-4"><div className="flex items-center gap-3"><span className="h-9 w-9 rounded-xl brand-soft-bg grid place-items-center"><UserRoundCog size={16}/></span><div><div className="font-semibold">{x.displayName||t('users.noName')}</div><div className="text-[10px] muted mt-1">{x.email||x.id} · {x.emailVerified?t('users.emailVerified'):t('users.emailUnverified')}</div></div></div></td><td><span className={`rounded-full px-2.5 py-1 text-[10px] font-semibold ${x.disabled?'bg-red-500/10 text-red-600':'brand-soft-bg brand-text'}`}>{x.disabled?t('users.suspended'):t('users.active')}</span></td><td><select className="field max-w-52 py-2" value={x.role} disabled={protectedTarget||!roles.length} onChange={e=>setPending({user:x,patch:{role:e.target.value as UserRole},label:t('users.changeRoleLabel').replace('{name}',String(x.displayName||x.email)).replace('{from}',String(x.role)).replace('{to}',String(e.target.value))})}><option value={x.role}>{x.role}</option>{roles.filter(r=>r!==x.role).map(r=><option key={r} value={r}>{r}</option>)}</select></td><td className="text-xs muted">{x.lastSignInAt?new Date(x.lastSignInAt).toLocaleString('ar-KW'):'—'}</td><td className="text-end"><Button size="sm" variant="outline" disabled={protectedTarget} onClick={()=>setPending({user:x,patch:{disabled:!x.disabled},label:x.disabled?t('users.reactivateLabel').replace('{name}',String(x.displayName||x.email)):t('users.suspendLabel').replace('{name}',String(x.displayName||x.email))})}>{x.disabled?<><CheckCircle2 size={14}/>{t('users.activate')}</>:<><Ban size={14}/>{t('users.suspend')}</>}</Button></td></tr>})}</tbody></table>{!filtered.length&&<div className="py-14 text-center body-copy">{t('users.noResults')}</div>}{nextPage&&<div className="pt-4 flex justify-center"><Button variant="outline" onClick={()=>load(nextPage)} disabled={loading}>{loading?<LoaderCircle size={15} className="animate-spin"/>:null}{t('users.loadNext')}</Button></div>}</div>}</CardContent></Card>
  {pending&&<div className="fixed inset-0 z-[90] grid place-items-center p-4" role="dialog" aria-modal="true" aria-labelledby="sensitive-action-title"><button className="absolute inset-0 bg-black/30 backdrop-blur-sm" onClick={()=>{setPending(null);setReason('')}} aria-label={t('users.close')}/><div className="relative panel rounded-2xl w-full max-w-lg p-5"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><ShieldCheck size={17} className="brand-text"/><h2 id="sensitive-action-title" className="section-title">{t('users.confirmSensitive')}</h2></div><p className="body-copy mt-2">{pending.label}</p></div><Button size="icon" variant="ghost" aria-label={t('users.closeDialog')} onClick={()=>{setPending(null);setReason('')}}><X size={17}/></Button></div><label className="block mt-5"><span className="text-[11px] font-semibold muted">{t('users.reasonLabel')}</span><textarea autoFocus className="field mt-1.5 min-h-24 resize-y" value={reason} onChange={e=>setReason(e.target.value)} placeholder={t('users.reasonPh')}/></label><Button className="w-full mt-4" disabled={saving||!reason.trim()} onClick={apply}>{saving?<LoaderCircle size={15} className="animate-spin"/>:<ShieldCheck size={15}/>}{t('users.confirmSave')}</Button></div></div>}
 </div>}
